let token=localStorage.getItem("id_token")||sessionStorage.getItem("id_token"),refreshToken=localStorage.getItem("refresh_token")||sessionStorage.getItem("refresh_token"),config,jobs=[],activeTask="";
if(token)localStorage.setItem("id_token",token);if(refreshToken)localStorage.setItem("refresh_token",refreshToken);sessionStorage.removeItem("id_token");sessionStorage.removeItem("refresh_token");
const jobsElement=document.querySelector("#adminJobs"),notice=document.querySelector("#jobNotice"),filter=document.querySelector("#jobFilter");
const protectedPanels=[...document.querySelectorAll(".admin-protected")];
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
function tokenExpiresSoon(){try{const part=token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");const claims=JSON.parse(atob(part.padEnd(Math.ceil(part.length/4)*4,"=")));return Number(claims.exp||0)*1000<=Date.now()+30000}catch{return true}}
async function refreshSession(){if(!refreshToken)return false;const body=new URLSearchParams({grant_type:"refresh_token",client_id:config.client_id,refresh_token:refreshToken});const result=await fetch(`https://${config.cognito_domain}/oauth2/token`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body}).then(response=>response.json());if(!result.id_token)return false;token=result.id_token;localStorage.setItem("id_token",token);return true}
async function api(path,options={},retry=true){const response=await fetch(config.api_url+path,{...options,headers:{authorization:`Bearer ${token}`,...(options.headers||{})}});if(response.status===401&&retry&&await refreshSession())return api(path,options,false);let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.message||`HTTP ${response.status}`);return data}
const formatTime=epoch=>epoch?new Date(Number(epoch)*1000).toLocaleString():"Unknown time";
function statusTone(status){status=String(status||"").toLowerCase();if(status==="completed")return "status-completed";if(status.includes("fail")||status.includes("error")||status.includes("cancel"))return "status-failed";if(status==="pending")return "status-pending";return "status-active"}
function middleTruncate(value,max=72){const text=Array.from(String(value??""));if(text.length<=max)return text.join("");return `${text.slice(0,max-25).join("")}…${text.slice(-24).join("")}`}
function matches(job){const needle=filter.value.trim().toLowerCase();return !needle||[job.task_id,job.source_name,job.user_email,job.user_id,job.status,job.job_type].some(value=>String(value||"").toLowerCase().includes(needle))}
function renderJobs(){const visible=jobs.filter(matches);notice.textContent=visible.length?`${visible.length} job${visible.length===1?"":"s"} in the retained seven-day operations index.`:"No indexed jobs match this view.";jobsElement.innerHTML=visible.map(job=>{const open=activeTask===job.task_id,id=`admin-job-${job.task_id}`;return `<li class="admin-job-record ${statusTone(job.status)}"><button class="admin-job-title" type="button" data-task="${esc(job.task_id)}" aria-expanded="${open}" aria-controls="${id}"><span class="admin-job-copy"><strong title="${esc(job.source_name)}">${esc(middleTruncate(job.source_name))}</strong><span>${esc(job.status)} · ${esc(formatTime(job.created_at))} · ${esc(job.user_email||job.user_id||"Unknown operator")}</span></span><span class="admin-job-indicator" aria-hidden="true">+</span></button><div id="${id}" class="admin-job-detail" data-detail="${esc(job.task_id)}" ${open?"":"hidden"}>${open?"Loading job details…":""}</div></li>`}).join("")}
function detailsHtml(job){const logs=(job.logs||[]).map(message=>`<div class="admin-log-message">${esc(message)}</div>`).join("")||'<div class="admin-log-message">No retained logs.</div>';return `${job.error?`<p class="admin-error"><strong>Error:</strong> ${esc(job.error)}</p>`:""}<dl><div><dt>Task ID</dt><dd>${esc(job.task_id)}</dd></div><div><dt>Status</dt><dd>${esc(job.status)}</dd></div><div><dt>Job type</dt><dd>${esc(job.job_type)}</dd></div><div><dt>Operator ID</dt><dd>${esc(job.user_id||"Unknown")}</dd></div><div><dt>Started</dt><dd>${esc(formatTime(job.created_at))}</dd></div><div><dt>Last update</dt><dd>${esc(formatTime(job.updated_at))}</dd></div><div><dt>Material</dt><dd>${esc(job.material_name||"—")}</dd></div><div><dt>Image preset</dt><dd>${esc(job.image_preset||"—")}</dd></div><div><dt>Abstract filter</dt><dd>${esc(job.abstract_filter||"none")}</dd></div></dl><h3>Runtime logs</h3><div class="admin-log-list">${logs}</div><div class="admin-job-actions"><button type="button" data-cancel="${esc(job.task_id)}" class="admin-cancel-job" ${job.queued?"":"disabled"}>${job.queued?"Cancel waiting job":"Job is not waiting in queue"}</button><p class="admin-delete-warning"><strong>Permanent deletion:</strong> Removes this history entry, its uploaded job input, generated outputs, and retained logs. Saved Swatch Palette Vault resources are not removed.</p><button type="button" data-delete="${esc(job.task_id)}" class="danger admin-delete-job">Delete Job and Assets</button></div>`}
async function openJob(taskId){if(activeTask===taskId){activeTask="";renderJobs();return}activeTask=taskId;renderJobs();const panel=jobsElement.querySelector(`[data-detail="${CSS.escape(taskId)}"]`);try{const job=await api(`/admin/jobs/${taskId}`);if(activeTask!==taskId)return;panel.innerHTML=detailsHtml(job);const summary=jobs.find(item=>item.task_id===taskId);if(summary){summary.status=job.status;summary.queued=job.queued}}catch(error){if(activeTask===taskId)panel.innerHTML=`<p class="admin-error">Could not load this job: ${esc(error.message)}</p>`}}
async function loadJobs(){const button=document.querySelector("#refreshJobs");button.disabled=true;notice.textContent="Refreshing authorized job activity…";try{const result=await api("/admin/jobs");jobs=result.jobs||[];document.querySelector("#adminEmail").textContent=result.admin_email||"Authorized operator";if(activeTask&&!jobs.some(job=>job.task_id===activeTask))activeTask="";renderJobs()}finally{button.disabled=false}}
async function loadUsers(){const container=document.querySelector("#adminUsers");try{const result=await api("/admin/users");document.querySelector("#userCount").textContent=String(result.count??0);container.innerHTML=(result.users||[]).map(user=>`<div class="admin-user"><strong>${esc(user.email||"Email unavailable")}</strong><small>${esc(user.status)} · ${user.enabled?"enabled":"disabled"} · joined ${esc(formatTime(user.created_at))}</small></div>`).join("")||"<p>No signed-up users.</p>"}catch(error){document.querySelector("#userCount").textContent="—";container.innerHTML=`<p class="admin-error">Could not load the user directory: ${esc(error.message)}</p>`}}
function renderService(state){const paused=state.status==="paused";document.querySelector("#serviceState").textContent=paused?"PAUSED":"ACTIVE";document.querySelector("#pauseService").disabled=paused;document.querySelector("#continueService").disabled=!paused;const resume=state.resumes_at?formatTime(state.resumes_at):"the next billing cycle";document.querySelector("#serviceNotice").textContent=paused?`Worker launches are paused. Automatic recovery is scheduled for ${resume}.`:"Processing is active and queued jobs may launch workers."}
async function loadService(){renderService(await api("/admin/service-control"))}
async function changeService(action){const label=action==="pause"?"pause all new worker launches":"continue or re-enable processing";if(!confirm(`Confirm that you want to ${label}.`))return;const buttons=[document.querySelector("#pauseService"),document.querySelector("#continueService")];buttons.forEach(button=>button.disabled=true);try{const state=await api("/admin/service-control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})});renderService(state);history.replaceState({},"",location.pathname)}catch(error){alert(`Could not change service availability: ${error.message}`);await loadService()}}
async function cancelJob(taskId){if(!confirm(`Cancel ${taskId} before a worker begins processing it?`))return;const button=jobsElement.querySelector(`[data-cancel="${CSS.escape(taskId)}"]`);button.disabled=true;button.textContent="Cancelling…";try{await api(`/admin/jobs/${taskId}/cancel`,{method:"POST"});const summary=jobs.find(job=>job.task_id===taskId);if(summary){summary.status="failed";summary.queued=false}activeTask="";renderJobs();await openJob(taskId)}catch(error){button.disabled=false;button.textContent="Cancel waiting job";alert(`Could not cancel job: ${error.message}`)}}
async function deleteJob(taskId){if(!confirm(`Permanently delete ${taskId}, its uploaded job input, generated outputs, and retained logs? This cannot be undone.`))return;const button=jobsElement.querySelector(`[data-delete="${CSS.escape(taskId)}"]`);button.disabled=true;button.textContent="Deleting Job and Assets…";try{const result=await api(`/admin/jobs/${taskId}`,{method:"DELETE"});jobs=jobs.filter(job=>job.task_id!==taskId);activeTask="";renderJobs();notice.textContent=`Deleted ${taskId} and ${result.deleted_assets||0} task-specific asset${result.deleted_assets===1?"":"s"}.`}catch(error){button.disabled=false;button.textContent="Delete Job and Assets";alert(`Could not delete job: ${error.message}`)}}
jobsElement.addEventListener("click",event=>{const deletion=event.target.closest("[data-delete]");if(deletion){deleteJob(deletion.dataset.delete);return}const cancel=event.target.closest("[data-cancel]");if(cancel){cancelJob(cancel.dataset.cancel);return}const row=event.target.closest("[data-task]");if(row)openJob(row.dataset.task)});
filter.addEventListener("input",renderJobs);document.querySelector("#refreshJobs").addEventListener("click",()=>loadJobs().catch(showFatal));
document.querySelector("#pauseService").addEventListener("click",()=>changeService("pause"));document.querySelector("#continueService").addEventListener("click",()=>changeService("resume"));
function showFatal(error){notice.innerHTML=`<span class="admin-error">Administration is unavailable: ${esc(error.message)}</span>`;jobsElement.replaceChildren()}
async function start(){config=await fetch("/config.json",{cache:"no-store"}).then(response=>response.json());if(!token||(tokenExpiresSoon()&&!await refreshSession()))return;await Promise.all([loadJobs(),loadUsers(),loadService()]);document.body.classList.add("admin-authorized");protectedPanels.forEach(panel=>panel.hidden=false);const requested=new URLSearchParams(location.search).get("service_action");if(["pause","continue","resume"].includes(requested))await changeService(requested)}
start().catch(showFatal);
