let config,resources,token=localStorage.getItem("id_token")||sessionStorage.getItem("id_token"),refreshToken=localStorage.getItem("refresh_token")||sessionStorage.getItem("refresh_token"),grid,image,corners=[],dragged=null,measurements=[],displayGains=[1,1,1],guestMode=!token,guestAccessToken=sessionStorage.getItem("color_lab_guest_access_token"),uploadedEntries=[];
if(token)localStorage.setItem("id_token",token);if(refreshToken)localStorage.setItem("refresh_token",refreshToken);sessionStorage.removeItem("id_token");sessionStorage.removeItem("refresh_token");
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const registeredAccess=$('#registeredAccess'),registeredContent=$('#registeredContent');
function showRegisteredAccess(authenticated){registeredAccess.hidden=true;registeredContent.hidden=false;window.stagingShellSetAuthenticated?.(authenticated);if(!authenticated){token=null;refreshToken=null;localStorage.removeItem('id_token');localStorage.removeItem('refresh_token')}}
const parameters={speed:["Speed","speed",100],max_power:["Maximum power","maxPower",30],min_power:["Minimum power","minPower",0],frequency:["Frequency","frequency",100000],pulse_width:["Pulse width","QPulseWidth",100],passes:["Passes","numPasses",1],interval:["Fill interval","interval",.05],angle:["Scan angle","angle",0]};
const integerDisplayParameters=new Set(['speed','frequency']);
const refinementDefaultSteps={speed:10,max_power:5,min_power:5,frequency:5000,pulse_width:10,passes:1,interval:.005,angle:5};
function displayAxisValue(parameter,value){const numeric=Number(value);return Number.isFinite(numeric)&&integerDisplayParameters.has(parameter)?Math.floor(numeric):numeric}
function setAxisBounds(parameter,lowInput,highInput,low,high){const integer=integerDisplayParameters.has(parameter);lowInput.step=integer?'1':'any';highInput.step=integer?'1':'any';lowInput.value=displayAxisValue(parameter,low);highInput.value=displayAxisValue(parameter,high)}
function normalizeAxisInputs(axis){const parameter=$(`#${axis}Parameter`).value,low=$(`#${axis}Low`),high=$(`#${axis}High`);setAxisBounds(parameter,low,high,low.value,high.value);return[Number(low.value),Number(high.value)]}
function expires(){try{const p=token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'),c=JSON.parse(atob(p.padEnd(Math.ceil(p.length/4)*4,'=')));return Number(c.exp||0)*1000<Date.now()+30000}catch{return true}}
async function refresh(){if(!refreshToken)return false;const body=new URLSearchParams({grant_type:'refresh_token',client_id:config.client_id,refresh_token:refreshToken}),r=await fetch(`https://${config.cognito_domain}/oauth2/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body}).then(r=>r.json());if(!r.id_token)return false;token=r.id_token;localStorage.setItem('id_token',token);return true}
async function api(path,options={},retry=true){const r=await fetch(config.api_url+path,{...options,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(options.headers||{})}});if(r.status===401&&retry&&await refresh())return api(path,options,false);const data=await r.json();if(!r.ok)throw new Error(data.message||`HTTP ${r.status}`);return data}
async function guestApi(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(guestAccessToken)headers['x-guest-capability']=guestAccessToken;const r=await fetch(config.api_url+path,{...options,headers}),data=await r.json();if(!r.ok)throw new Error(data.message||`HTTP ${r.status}`);return data}
async function upload(file,target){const body=new FormData();Object.entries(target.fields).forEach(([key,value])=>body.append(key,value));body.append('file',file);const response=await fetch(target.url,{method:'POST',body});if(!response.ok)throw new Error(`Material Library upload failed (${response.status})`)}
function lastUsedValues(name){return resources?.preferences?.[name]?.values||null}
async function saveLastUsed(name,values){if(guestMode)return;const result=await api('/account/preferences',{method:'PATCH',body:JSON.stringify({[name]:values})});resources.preferences=result.preferences||resources.preferences||{}}
function hasOption(select,value){return [...select.options].some(item=>item.value===String(value??''))}
function colorLabFormValues(){return{library_source:$('#librarySource').value,library_id:$('#library').value,entry_id:$('#entry').value,label_entry_id:$('#labelEntry').value,x_parameter:$('#xParameter').value,x_low:$('#xLow').value,x_high:$('#xHigh').value,y_parameter:$('#yParameter').value,y_low:$('#yLow').value,y_high:$('#yHigh').value,grid_width_mm:$('#gridWidth').value,grid_length_mm:$('#gridLength').value,white_background:$('#whitePaper').checked,review_action:$('#reviewAction').value,palette_name:$('#paletteName').value,palette_material:$('#paletteMaterial').value,measurement_grid_id:$('#measurementGridId').value}}
function restoreColorLabForm(values){if(!values)return;const source=$('#librarySource'),useSaved=values.library_source==='saved'&&hasOption(source,'saved')&&hasOption($('#library'),values.library_id);source.value=useSaved?'saved':'upload';syncLibrarySource();if(useSaved){$('#library').value=values.library_id;fillEntries();if(hasOption($('#entry'),values.entry_id))chooseEntry(values.entry_id)}for(const [id,key] of [['xParameter','x_parameter'],['yParameter','y_parameter'],['reviewAction','review_action']])if(hasOption($('#'+id),values[key]))$('#'+id).value=values[key];for(const [id,key] of [['xLow','x_low'],['xHigh','x_high'],['yLow','y_low'],['yHigh','y_high'],['gridWidth','grid_width_mm'],['gridLength','grid_length_mm'],['paletteName','palette_name'],['paletteMaterial','palette_material'],['measurementGridId','measurement_grid_id']])if(values[key]!==undefined)$('#'+id).value=values[key];normalizeAxisInputs('x');normalizeAxisInputs('y');const shortId=String(values.measurement_grid_id||'').slice(0,8);if(hasOption($('#recentGridSelect'),shortId))$('#recentGridSelect').value=shortId;$('#whitePaper').checked=Boolean(values.white_background);estimate();$('#reviewAction').dispatchEvent(new Event('change'))}
const opt=(v,l)=>new Option(l,v);
function usingSavedLibrary(){return !guestMode&&$('#librarySource').value==='saved'}
function selectedEntry(){const selectedId=$('#entry').value;if(selectedId==='')return null;if(!usingSavedLibrary())return uploadedEntries.find(entry=>String(entry.entry_id)===selectedId);const lib=(resources.material_libraries||[]).find(x=>x.library_id===$('#library').value);return lib?.summary?.entries?.find(entry=>String(entry.entry_id)===selectedId)}
function baselineValue(parameter){const spec=parameters[parameter];if(!spec)return null;const raw=selectedEntry()?.settings?.[spec[1]],value=Number(raw);return raw!==undefined&&raw!==null&&raw!==''&&Number.isFinite(value)?value:spec[2]}
function populateAxis(axis){const parameter=$(`#${axis}Parameter`).value,value=baselineValue(parameter);if(value===null)return;setAxisBounds(parameter,$(`#${axis}Low`),$(`#${axis}High`),value,value)}
function populateRanges(){populateAxis('x');populateAxis('y')}
function applyStartingSetting(){const entry=selectedEntry();if(!entry)return;populateRanges();const x=$('#xParameter').value,y=$('#yParameter').value;$('#gridResult').textContent=`Loaded ${entry.description}. Sweep bounds now match its ${parameters[x]?.[0]||x} and ${parameters[y]?.[0]||y} values.`}
function entryColor(entry){const explicit=String(entry?.hex||'').toUpperCase();if(/^#[0-9A-F]{6}$/.test(explicit))return explicit;return resources.palette.find(color=>color.name.toLowerCase()===String(entry?.description||'').trim().toLowerCase())?.hex||''}
function closeEntryPicker(){$('#entryPickerMenu').hidden=true;$('#entryPickerButton').setAttribute('aria-expanded','false')}
function chooseEntry(entryId){$('#entry').value=String(entryId);const entry=selectedEntry(),chip=$('#entryPickerButton .mini-swatch'),copy=$('#entryPickerButton .setting-picker-copy'),hex=entryColor(entry);chip.style.background=hex||'';copy.textContent=entry?`${entry.description} · ${entry.material||'Material'}`:'Choose a setting…';closeEntryPicker();applyStartingSetting()}
function fillEntries(){const lib=(resources.material_libraries||[]).find(x=>x.library_id===$('#library').value),entries=usingSavedLibrary()?(lib?.summary?.entries||[]):uploadedEntries,select=$('#entry'),menu=$('#entryPickerMenu'),button=$('#entryPickerButton');select.replaceChildren(opt('','Choose a setting…'),...entries.map(entry=>opt(String(entry.entry_id),`${entry.material||'Material'} · ${entry.description}`)));select.disabled=!entries.length;button.disabled=!entries.length;menu.innerHTML=entries.map(entry=>{const hex=entryColor(entry);return `<button class="setting-picker-option" type="button" role="option" data-entry-id="${esc(entry.entry_id)}"><span class="mini-swatch"${hex?` style="background:${esc(hex)}"`:''}></span><span class="setting-picker-copy"><strong>${esc(entry.description||'Unnamed setting')}</strong><small>${esc(entry.material||'Material')}</small></span></button>`}).join('')||'<div class="setting-picker-option">No settings found</div>';$('#entryPickerButton .mini-swatch').style.background='';$('#entryPickerButton .setting-picker-copy').textContent='Choose a setting…';closeEntryPicker();populateRanges()}
function syncLibrarySource(){const saved=usingSavedLibrary();$('#libraryUploadRow').hidden=saved;$('#libraryFile').disabled=saved;$('#libraryFile').required=!saved;$('#librarySavedRow').hidden=!saved;$('#library').disabled=!saved;$('#library').required=saved;if(!saved)$('#library').value='';fillEntries()}
function fillLibrarySources(){const libraries=resources.material_libraries||[];$('#library').replaceChildren(opt('','Choose a saved palette…'),...libraries.map(item=>opt(item.library_id,item.name)));$('#librarySource').replaceChildren(opt('upload','Upload a new LightBurn Material Library'),...(libraries.length?[opt('saved','Use a saved Swatch Palette')]:[]));syncLibrarySource()}
$('#librarySource').onchange=syncLibrarySource;
$('#entryPickerButton').onclick=()=>{if($('#entryPickerButton').disabled)return;const opening=$('#entryPickerMenu').hidden;closeEntryPicker();if(opening){$('#entryPickerMenu').hidden=false;$('#entryPickerButton').setAttribute('aria-expanded','true')}};
$('#entryPickerMenu').onclick=event=>{const option=event.target.closest('[data-entry-id]');if(option)chooseEntry(option.dataset.entryId)};
document.addEventListener('click',event=>{if(!event.target.closest('.setting-picker'))closeEntryPicker()});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeEntryPicker()});
$('#libraryFile').onchange=async event=>{uploadedEntries=[];const file=event.target.files[0];if(!file){fillEntries();return}try{const documentNode=new DOMParser().parseFromString(await file.text(),'application/xml');if(documentNode.querySelector('parsererror'))throw new Error('The selected file is not valid XML');let entryId=0;for(const material of documentNode.querySelectorAll('Material')){const materialName=material.getAttribute('name')||material.getAttribute('Name')||'Material';for(const entry of [...material.children].filter(node=>node.tagName==='Entry')){const cut=[...entry.children].find(node=>node.tagName==='CutSetting'),settings={};if(!cut)continue;for(const node of cut.children)if(node.hasAttribute('Value'))settings[node.tagName]=node.getAttribute('Value');uploadedEntries.push({entry_id:entryId++,material:materialName,description:entry.getAttribute('Desc')||entry.getAttribute('desc')||'Unnamed setting',settings})}}if(!uploadedEntries.length)throw new Error('No Material Library settings were found');fillEntries();$('#gridResult').textContent=`Loaded ${uploadedEntries.length} settings from ${file.name}.`}catch(error){fillEntries();$('#gridResult').textContent=`Could not read Material Library: ${error.message}`}};
function fillParameters(){for(const id of ['xParameter','yParameter','refineXParameter','refineYParameter'])$('#'+id).replaceChildren(...Object.entries(parameters).map(([v,p])=>opt(v,p[0])));$('#xParameter').value='speed';$('#yParameter').value='frequency';$('#refineXParameter').value='speed';$('#refineYParameter').value='frequency';populateRanges()}
function layout(){const w=Number($('#gridWidth').value),l=Number($('#gridLength').value),options=[];for(let r=2;r<=29;r++)for(let c=2;c<=29;c++)if(r*c<=29)options.push([r*c,Math.min(w/c,l/r),r,c]);return options.sort((a,b)=>b[0]-a[0]||b[1]-a[1])[0]}
function estimate(){const [n,size,r,c]=layout();$('#cellSize').value=size.toFixed(2);$('#gridEstimate').textContent=`${r} rows × ${c} columns = ${n} gapless cells.`}
function activateGrid(loaded){grid=loaded;sessionStorage.setItem('color_discovery_grid',JSON.stringify(grid));$('#measurementGridId').value=grid.grid_id;const select=$('#recentGridSelect');if([...select.options].some(option=>option.value===grid.grid_id.slice(0,8)))select.value=grid.grid_id.slice(0,8);$('#measure').disabled=!image;if(image)draw();saveLastUsed('last_color_lab_form',colorLabFormValues()).catch(()=>{})}
async function populateGridChoices(){const result=await api('/color-discovery/grids'),select=$('#recentGridSelect'),placeholder=new Option('Choose a recent grid…','');select.replaceChildren(placeholder,...result.grids.map(item=>new Option(`${item.short_id} · ${[item.material,item.setting_description,`${item.cell_count} cells`].filter(Boolean).join(' · ')}`,item.short_id)));if(grid?.grid_id&&[...select.options].some(option=>option.value===grid.grid_id.slice(0,8)))select.value=grid.grid_id.slice(0,8)}
$('#recentGridSelect').onchange=()=>{if($('#recentGridSelect').value)$('#measurementGridId').value=$('#recentGridSelect').value};
$('#library').onchange=fillEntries;$('#entry').onchange=applyStartingSetting;$('#xParameter').onchange=()=>populateAxis('x');$('#yParameter').onchange=()=>populateAxis('y');for(const axis of ['x','y'])for(const suffix of ['Low','High'])$(`#${axis}${suffix}`).onchange=()=>normalizeAxisInputs(axis);for(const id of ['gridWidth','gridLength'])$('#'+id).oninput=estimate;
$('#gridForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter,out=$('#gridResult'),saved=usingSavedLibrary(),file=$('#libraryFile').files[0],[xLow,xHigh]=normalizeAxisInputs('x'),[yLow,yHigh]=normalizeAxisInputs('y');b.disabled=true;out.textContent='Generating durable LightBurn grid…';try{const payload={library_id:saved?$('#library').value:'',entry_id:Number($('#entry').value),x_parameter:$('#xParameter').value,x_low:xLow,x_high:xHigh,y_parameter:$('#yParameter').value,y_low:yLow,y_high:yHigh,grid_width_mm:Number($('#gridWidth').value),grid_length_mm:Number($('#gridLength').value)};let created;if(saved){created=await api('/color-discovery/grids',{method:'POST',body:JSON.stringify(payload)})}else{if(!file)throw new Error('Upload a LightBurn Material Library');const request=guestMode?guestApi:api,grant=await request(guestMode?'/guest/color-discovery/uploads':'/color-discovery/uploads',{method:'POST',body:JSON.stringify({material_name:file.name,material_content_type:file.type||'application/octet-stream'})});if(guestMode){guestAccessToken=grant.guest_access_token;sessionStorage.setItem('color_lab_guest_access_token',guestAccessToken)}await upload(file,grant.material);payload.upload_token=grant.upload_token;payload.material_key=grant.material.key;created=await request(`${guestMode?'/guest':''}/color-discovery/grids/${grant.task_id}`,{method:'POST',body:JSON.stringify(payload)})}activateGrid(created);if(!guestMode)await populateGridChoices();out.innerHTML=`Grid ${esc(grid.grid_id)} is ready.<span class="color-lab-downloads"><a class="staging-action-button color-lab-download-button" href="${esc(grid.downloads.lightburn)}" download>Download LightBurn Project</a><a class="staging-action-button color-lab-download-button" href="${esc(grid.downloads.metadata)}" download>Download Metadata</a></span>`}catch(error){out.textContent=`Could not generate grid: ${error.message}`}finally{b.disabled=false}};
async function loadSelectedGrid(){const out=$('#loadGridResult'),reference=$('#measurementGridId').value.trim();if(!reference)throw new Error('Choose or enter a Grid ID before selecting the photograph');if(grid?.grid_id&&(grid.grid_id.toLowerCase()===reference.toLowerCase()||grid.grid_id.slice(0,8).toLowerCase()===reference.toLowerCase()))return grid;out.textContent='Loading saved grid metadata…';const loaded=guestMode?await guestApi(`/guest/color-discovery/grids/${encodeURIComponent(reference)}`):await api(`/color-discovery/grids/${encodeURIComponent(reference)}`);activateGrid(loaded);return loaded}
const canvas=$('#canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
function reset(){const i=Math.min(canvas.width,canvas.height)*.04;corners=[[i,i],[canvas.width-i,i],[canvas.width-i,canvas.height-i],[i,canvas.height-i]];draw()}
function median(values){const ordered=[...values].sort((a,b)=>a-b);return ordered.length?ordered[Math.floor(ordered.length/2)]:0}
function percentile(values,ratio){const ordered=[...values].sort((a,b)=>a-b);return ordered.length?ordered[Math.max(0,Math.min(ordered.length-1,Math.floor((ordered.length-1)*ratio)))]:0}
function autoAlignGrid(){if(!image)return false;displayGains=[1,1,1];ctx.drawImage(image,0,0,canvas.width,canvas.height);const frame=ctx.getImageData(0,0,canvas.width,canvas.height).data,step=Math.max(2,Math.round(Math.min(canvas.width,canvas.height)/240)),pixel=(x,y)=>{const offset=(y*canvas.width+x)*4;return[frame[offset],frame[offset+1],frame[offset+2]]},border=[];for(let x=0;x<canvas.width;x+=step){border.push(pixel(x,0),pixel(x,canvas.height-1))}for(let y=0;y<canvas.height;y+=step){border.push(pixel(0,y),pixel(canvas.width-1,y))}const background=[0,1,2].map(channel=>median(border.map(value=>value[channel]))),borderDistances=border.map(value=>Math.hypot(value[0]-background[0],value[1]-background[1],value[2]-background[2])),threshold=Math.max(24,percentile(borderDistances,.9)+12),rows=[];for(let y=step;y<canvas.height-step;y+=step){const xs=[];for(let x=step;x<canvas.width-step;x+=step){const value=pixel(x,y);if(Math.hypot(value[0]-background[0],value[1]-background[1],value[2]-background[2])>=threshold)xs.push(x)}if(xs.length>=Math.max(3,Math.round(canvas.width/step*.04)))rows.push({y,left:percentile(xs,.03),right:percentile(xs,.97)})}if(rows.length<8)return false;const ys=rows.map(row=>row.y),low=percentile(ys,.04),high=percentile(ys,.96),span=high-low;if(span<canvas.height*.18)return false;const top=rows.filter(row=>row.y<=low+span*.14),bottom=rows.filter(row=>row.y>=high-span*.14);if(!top.length||!bottom.length)return false;const proposed=[[median(top.map(row=>row.left)),median(top.map(row=>row.y))],[median(top.map(row=>row.right)),median(top.map(row=>row.y))],[median(bottom.map(row=>row.right)),median(bottom.map(row=>row.y))],[median(bottom.map(row=>row.left)),median(bottom.map(row=>row.y))]],area=Math.abs(proposed.reduce((sum,point,index)=>{const next=proposed[(index+1)%4];return sum+point[0]*next[1]-next[0]*point[1]},0))/2;if(area<canvas.width*canvas.height*.08||proposed[1][0]-proposed[0][0]<canvas.width*.15||proposed[2][0]-proposed[3][0]<canvas.width*.15)return false;corners=proposed;draw();return true}
function overlayGrid(){const metadata=grid?.metadata;if(!metadata||corners.length!==4)return;const rows=Number(metadata.rows),columns=Number(metadata.columns);ctx.save();ctx.lineWidth=1.5;ctx.strokeStyle='rgba(131,240,106,.88)';for(let column=1;column<columns;column++){const start=point(column/columns,0),end=point(column/columns,1);ctx.beginPath();ctx.moveTo(...start);ctx.lineTo(...end);ctx.stroke()}for(let row=1;row<rows;row++){const start=point(0,row/rows),end=point(1,row/rows);ctx.beginPath();ctx.moveTo(...start);ctx.lineTo(...end);ctx.stroke()}const radius=Math.max(8,Math.min(15,Math.min(canvas.width/columns,canvas.height/rows)*.12));ctx.font=`700 ${Math.max(9,Math.round(radius*.9))}px Courier New,monospace`;ctx.textAlign='center';ctx.textBaseline='middle';for(let row=0;row<rows;row++)for(let column=0;column<columns;column++){const index=row*columns+column+1,[x,y]=point((column+.5)/columns,(row+.5)/rows);ctx.fillStyle='rgba(9,14,8,.78)';ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#83f06a';ctx.stroke();ctx.fillStyle='#f2ecd0';ctx.fillText(String(index),x,y)}ctx.restore()}
function drawPhoto(){ctx.drawImage(image,0,0,canvas.width,canvas.height);if(displayGains.some((gain,index)=>Math.abs(gain-1)>.0001)){const frame=ctx.getImageData(0,0,canvas.width,canvas.height),pixels=frame.data;for(let offset=0;offset<pixels.length;offset+=4)for(let channel=0;channel<3;channel++)pixels[offset+channel]=Math.max(0,Math.min(255,Math.round(pixels[offset+channel]*displayGains[channel])));ctx.putImageData(frame,0,0)}}
function draw(){if(!image)return;drawPhoto();ctx.strokeStyle='#83f06a';ctx.lineWidth=3;ctx.beginPath();corners.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.stroke();overlayGrid();for(const [x,y] of corners){ctx.fillStyle='#83f06a';ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fill()}}
$('#gridPhoto').onchange=async e=>{const file=e.target.files[0],out=$('#loadGridResult');if(!file)return;$('#measure').disabled=true;try{const loaded=await loadSelectedGrid(),img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const scale=Math.min(1000/img.naturalWidth,700/img.naturalHeight,1);canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);image=img;displayGains=[1,1,1];canvas.hidden=false;reset();$('#autoAlign').disabled=false;$('#resetCorners').disabled=false;const aligned=autoAlignGrid();$('#measure').disabled=false;out.textContent=`Grid ${loaded.grid_id} loaded with ${loaded.metadata.cells.length} cells. ${aligned?'The overlay was aligned automatically; drag any corner to correct it.':'Automatic alignment was uncertain; position the four corners manually.'}`;URL.revokeObjectURL(url)};img.onerror=()=>{out.textContent='Could not load the selected photograph.';URL.revokeObjectURL(url)};img.src=url}catch(error){out.textContent=`Could not load grid: ${error.message}`;e.target.value=''}};$('#autoAlign').onclick=()=>{$('#loadGridResult').textContent=autoAlignGrid()?'Overlay aligned automatically. Drag any corner to correct it.':'Automatic alignment was uncertain; keep adjusting the corners manually.'};$('#resetCorners').onclick=reset;
canvas.onpointerdown=e=>{const q=canvas.getBoundingClientRect(),x=(e.clientX-q.left)*canvas.width/q.width,y=(e.clientY-q.top)*canvas.height/q.height;dragged=corners.reduce((a,p,i)=>Math.hypot(p[0]-x,p[1]-y)<a.d?{i,d:Math.hypot(p[0]-x,p[1]-y)}:a,{i:null,d:Infinity}).i;canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(dragged===null)return;const q=canvas.getBoundingClientRect();corners[dragged]=[(e.clientX-q.left)*canvas.width/q.width,(e.clientY-q.top)*canvas.height/q.height];draw()};canvas.onpointerup=canvas.onpointercancel=()=>dragged=null;
function point(u,v){const t=[corners[0][0]*(1-u)+corners[1][0]*u,corners[0][1]*(1-u)+corners[1][1]*u],b=[corners[3][0]*(1-u)+corners[2][0]*u,corners[3][1]*(1-u)+corners[2][1]*u];return[t[0]*(1-v)+b[0]*v,t[1]*(1-v)+b[1]*v]}
function rgb(x,y){const d=ctx.getImageData(Math.max(0,Math.round(x)-2),Math.max(0,Math.round(y)-2),5,5).data,s=[0,0,0];for(let i=0;i<d.length;i+=4){s[0]+=d[i];s[1]+=d[i+1];s[2]+=d[i+2]}return s.map(v=>Math.round(v/(d.length/4)))}
function insideGrid(x,y){let inside=false;for(let i=0,j=corners.length-1;i<corners.length;j=i++){const [xi,yi]=corners[i],[xj,yj]=corners[j],cross=(yi>y)!==(yj>y)&&x<(xj-xi)*(y-yi)/(yj-yi)+xi;if(cross)inside=!inside}return inside}
function whiteBalanceGains(){if(!$('#whitePaper').checked)return{gains:[1,1,1],reference:null};const pixels=ctx.getImageData(0,0,canvas.width,canvas.height).data,candidates=[],step=Math.max(3,Math.round(Math.min(canvas.width,canvas.height)/180));for(let y=0;y<canvas.height;y+=step)for(let x=0;x<canvas.width;x+=step){if(insideGrid(x,y))continue;const offset=(Math.round(y)*canvas.width+Math.round(x))*4,r=pixels[offset],g=pixels[offset+1],b=pixels[offset+2],brightness=(r+g+b)/3;if(brightness>=120)candidates.push({rgb:[r,g,b],brightness})}if(candidates.length<20)return{gains:[1,1,1],reference:null};candidates.sort((a,b)=>b.brightness-a.brightness);const brightest=candidates.slice(0,Math.max(20,Math.ceil(candidates.length*.15))),reference=[0,1,2].map(channel=>{const values=brightest.map(item=>item.rgb[channel]).sort((a,b)=>a-b);return values[Math.floor(values.length/2)]}),target=(reference[0]+reference[1]+reference[2])/3,gains=reference.map(value=>Math.max(.6,Math.min(1.67,target/Math.max(value,1))));return{gains,reference}}
function balancedRgb(value,gains){return value.map((channel,index)=>Math.max(0,Math.min(255,Math.round(channel*gains[index]))))}
function hexRgb(hex){return[1,3,5].map(index=>parseInt(hex.slice(index,index+2),16))}
function rgbLab(rgb){const linear=rgb.map(value=>{const channel=value/255;return channel<=.04045?channel/12.92:((channel+.055)/1.055)**2.4}),x=(linear[0]*.4124564+linear[1]*.3575761+linear[2]*.1804375)/.95047,y=linear[0]*.2126729+linear[1]*.7151522+linear[2]*.072175,z=(linear[0]*.0193339+linear[1]*.119192+linear[2]*.9503041)/1.08883,f=value=>value>.008856?Math.cbrt(value):7.787*value+16/116,fx=f(x),fy=f(y),fz=f(z);return[116*fy-16,500*(fx-fy),200*(fy-fz)]}
function labChroma(lab){return Math.hypot(lab[1],lab[2])}
function labDistance(left,right){return Math.hypot(left[0]-right[0],left[1]-right[1],left[2]-right[2])}
function labHue(lab){return(Math.atan2(lab[2],lab[1])*180/Math.PI+360)%360}
function hueDistance(left,right){const difference=Math.abs(left-right);return Math.min(difference,360-difference)}
function rgbHsv(rgb){const[red,green,blue]=rgb.map(value=>value/255),maximum=Math.max(red,green,blue),minimum=Math.min(red,green,blue),delta=maximum-minimum;let hue=0;if(delta)hue=maximum===red?60*((green-blue)/delta%6):maximum===green?60*((blue-red)/delta+2):60*((red-green)/delta+4);return{hue:(hue+360)%360,saturation:maximum?delta/maximum:0,value:maximum}}
function nearestOfficial(hex){const sampleRgb=hexRgb(hex),sampleLab=rgbLab(sampleRgb),sampleChroma=labChroma(sampleLab),sampleHsv=rgbHsv(sampleRgb),chromatic=sampleChroma>=8&&sampleHsv.saturation>=.12,ranked=resources.palette.map(item=>{const rgb=hexRgb(item.hex),lab=rgbLab(rgb),hsv=rgbHsv(rgb),hsv_hue_difference=hueDistance(sampleHsv.hue,hsv.hue),distance=labDistance(sampleLab,lab);return{...item,lab,hsv,hsv_hue_difference,distance,match_score:distance+hsv_hue_difference*.2}}),colored=chromatic?ranked.filter(item=>labChroma(item.lab)>=8&&item.hsv.saturation>=.12):ranked,closestHue=colored.length?Math.min(...colored.map(item=>item.hsv_hue_difference)):Infinity,hueNeighbors=chromatic?colored.filter(item=>item.hsv_hue_difference<=Math.min(45,closestHue+6)):colored,candidates=hueNeighbors.length?hueNeighbors:colored;return(candidates.length?candidates:ranked).reduce((best,item)=>!best||item.match_score<best.match_score?item:best,null)}
function officialOrder(cell){return resources.palette.findIndex(color=>color.hex.toUpperCase()===cell.official.hex.toUpperCase())}
function sortMeasurements(){measurements.sort((left,right)=>officialOrder(left)-officialOrder(right)||left.index-right.index)}
function measurementCard(c,m){return `<article class="cell${c.enabled?'':' disabled'}" data-cell="${c.index}" role="button" tabindex="0" aria-pressed="${c.enabled}"><strong>Cell ${c.index}</strong><input class="cell-square detected-picker" type="color" value="${esc(c.observed_hex)}" aria-label="Choose detected color for cell ${c.index}" style="--detected-color:${c.observed_hex}"><input class="cell-hex detected-hex" value="${esc(c.observed_hex)}" maxlength="7" aria-label="Cell ${c.index} detected hex"><small>${esc(m.x_parameter)} ${c.overrides[m.x_parameter]} · ${esc(m.y_parameter)} ${c.overrides[m.y_parameter]}</small></article>`}
function renderMeasurements(){const m=grid.metadata;$('#cells').innerHTML=resources.palette.map(official=>{const candidates=measurements.filter(cell=>cell.official.hex.toUpperCase()===official.hex.toUpperCase());return candidates.length?`<section class="official-group"><h3 class="official-group-title"><i class="official-group-chip" style="background:${official.hex}"></i>${esc(official.name)} · ${official.hex}</h3><div class="official-group-cards">${candidates.map(cell=>measurementCard(cell,m)).join('')}</div></section>`:''}).join('');$('#savePalette').hidden=false}
function originalAxisStep(values){return values?.length>1?Math.abs(Number(values.at(-1))-Number(values[0]))/(values.length-1):0}
function refinementCenter(item,parameter){const field=parameters[parameter]?.[1],raw=item.overrides?.[parameter]??item.laser_settings?.settings?.[field],value=Number(raw);return Number.isFinite(value)?value:Number(parameters[parameter]?.[2]||0)}
function refinementStep(parameter){const m=grid.metadata;if(parameter===m.x_parameter)return originalAxisStep(m.x_values);if(parameter===m.y_parameter)return originalAxisStep(m.y_values);return refinementDefaultSteps[parameter]??1}
function populateRefineAxis(item,axis){const parameter=$(`#refine${axis}Parameter`).value,center=refinementCenter(item,parameter),step=refinementStep(parameter);$(`#refine${axis}LowLabel`).textContent=`${parameters[parameter]?.[0]||parameter} minimum`;$(`#refine${axis}HighLabel`).textContent=`${parameters[parameter]?.[0]||parameter} maximum`;setAxisBounds(parameter,$(`#refine${axis}Low`),$(`#refine${axis}High`),center-step,center+step)}
function populateRefineBounds(item){const m=grid.metadata;$('#refineXParameter').value=m.x_parameter;$('#refineYParameter').value=m.y_parameter;populateRefineAxis(item,'X');populateRefineAxis(item,'Y')}
function toggleCell(card,force){const item=measurements.find(c=>c.index===Number(card.dataset.cell));if($('#reviewAction').value==='refine'){const enabling=force??!item.enabled;measurements.forEach(cell=>cell.enabled=false);item.enabled=enabling;if(enabling)populateRefineBounds(item)}else item.enabled=force??!item.enabled;renderMeasurements()}
$('#cells').onclick=e=>{const card=e.target.closest('[data-cell]');if(!card||e.target.matches('input'))return;toggleCell(card)};$('#cells').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-cell]')){e.preventDefault();toggleCell(e.target)}};
$('#cells').oninput=e=>{if(!e.target.matches('.detected-hex,.detected-picker'))return;const card=e.target.closest('[data-cell]'),item=measurements.find(c=>c.index===Number(card.dataset.cell)),hex=e.target.value.trim().toUpperCase(),valid=/^#[0-9A-F]{6}$/.test(hex);e.target.classList.toggle('invalid',!valid);if(!valid)return;item.observed_hex=hex;item.official=nearestOfficial(hex);const picker=card.querySelector('.detected-picker'),text=card.querySelector('.detected-hex');picker.value=hex;text.value=hex;picker.style.setProperty('--detected-color',hex);text.classList.remove('invalid')};
$('#cells').onchange=e=>{if(!e.target.matches('.detected-hex,.detected-picker')||e.target.classList.contains('invalid'))return;sortMeasurements();renderMeasurements()};
$('#measure').onclick=()=>{ctx.drawImage(image,0,0,canvas.width,canvas.height);const balance=whiteBalanceGains(),m=grid.metadata;measurements=m.cells.map(c=>{const [x,y]=point((c.column-.5)/m.columns,(c.row-.5)/m.rows),color=balancedRgb(rgb(x,y),balance.gains),observed_hex='#'+color.map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase();return{...c,observed_hex,official:nearestOfficial(observed_hex),enabled:true}});displayGains=balance.gains;sortMeasurements();draw();renderMeasurements();$('#paletteName').value=`Color Discovery ${grid.grid_id.slice(0,8)}`;$('#paletteMaterial').value=m.material||'Discovered colors';const detail=$('#whitePaper').checked?(balance.reference?` White Background reference RGB ${balance.reference.join(', ')} applied. The photograph preview now shows the same correction used for measurement.`:' White Background was selected, but not enough bright paper was visible; no correction was applied.'):' ';$('#captureResult').textContent=`Measured ${measurements.length} cells locally.${detail}`};
$('#reviewAction').onchange=()=>{const action=$('#reviewAction').value,refining=action==='refine';document.querySelectorAll('.palette-save-field').forEach(field=>field.hidden=refining);$('#refineBounds').hidden=!refining;$('#saveEnabled').hidden=refining;$('#refineGrid').hidden=!refining;$('#saveEnabled').textContent=action==='save'?'Save Enabled Swatches':'Export Selected Settings';if(refining){measurements.forEach(cell=>cell.enabled=false);renderMeasurements();$('#saveResult').textContent='Select one swatch to use as the center of the refinement grid.'}else $('#saveResult').textContent=`Select the swatches to ${action==='save'?'save':'export'}; only one may be assigned to each official Rasterizer color.`};
for(const axis of ['X','Y']){$(`#refine${axis}Parameter`).onchange=()=>{const item=measurements.find(cell=>cell.enabled);if(item)populateRefineAxis(item,axis)};for(const suffix of ['Low','High'])$(`#refine${axis}${suffix}`).onchange=()=>{const parameter=$(`#refine${axis}Parameter`).value,low=$(`#refine${axis}Low`),high=$(`#refine${axis}High`);setAxisBounds(parameter,low,high,low.value,high.value)}}
$('#refineGrid').onclick=async()=>{const enabled=measurements.filter(cell=>cell.enabled),out=$('#saveResult'),button=$('#refineGrid');if(enabled.length!==1){out.textContent=`Refine Grid requires exactly one enabled swatch; ${enabled.length} are currently enabled.`;return}const x=$('#refineXParameter').value,y=$('#refineYParameter').value;if(x===y){out.textContent='Choose two different parameters for the refinement grid columns and rows.';return}setAxisBounds(x,$('#refineXLow'),$('#refineXHigh'),$('#refineXLow').value,$('#refineXHigh').value);setAxisBounds(y,$('#refineYLow'),$('#refineYHigh'),$('#refineYLow').value,$('#refineYHigh').value);const bounds=[$('#refineXLow'),$('#refineXHigh'),$('#refineYLow'),$('#refineYHigh')].map(input=>Number(input.value));if(bounds.some(value=>!Number.isFinite(value))){out.textContent='Enter valid minimum and maximum values for both refinement axes.';return}button.disabled=true;out.textContent=`Generating a finer grid around cell ${enabled[0].index}…`;try{const payload={refine_from_grid_id:grid.grid_id,refine_cell_index:enabled[0].index,refine_x_parameter:x,refine_y_parameter:y,refine_x_low:bounds[0],refine_x_high:bounds[1],refine_y_low:bounds[2],refine_y_high:bounds[3]},created=guestMode?await guestApi(`/guest/color-discovery/grids/${grid.grid_id}/refine`,{method:'POST',body:JSON.stringify(payload)}):await api('/color-discovery/grids',{method:'POST',body:JSON.stringify(payload)});activateGrid(created);if(!guestMode)await populateGridChoices();const refinement=created.metadata.refinement;measurements=[];$('#cells').replaceChildren();$('#savePalette').hidden=true;out.innerHTML=`Refinement grid ${esc(created.grid_id)} is ready using the displayed refinement bounds.<span class="color-lab-downloads"><a class="staging-action-button color-lab-download-button" href="${esc(created.downloads.lightburn)}" download>Download Refined LightBurn Project</a><a class="staging-action-button color-lab-download-button" href="${esc(created.downloads.metadata)}" download>Download Refined Metadata</a></span>`;$('#gridResult').innerHTML=out.innerHTML;$('#captureResult').textContent=`Refinement grid created from cell ${refinement.cell_index} of ${refinement.grid_id.slice(0,8)}. Engrave it, then select its Grid ID and photograph for another measurement.`}catch(error){out.textContent=`Could not refine grid: ${error.message}`}finally{button.disabled=false}};
function snapshotElement(documentNode,snapshot,tag='CutSetting'){const element=documentNode.createElement(tag);element.setAttribute('type',snapshot?.type||'Setting');for(const [name,value] of Object.entries(snapshot?.settings||{})){const field=documentNode.createElement(name);field.setAttribute('Value',String(value));element.append(field)}for(const sublayer of snapshot?.sub_layers||[])element.append(snapshotElement(documentNode,sublayer,'SubLayer'));return element}
function exportColorPalette(enabled){const documentNode=document.implementation.createDocument('', 'LightBurnLibrary'),root=documentNode.documentElement,material=documentNode.createElement('Material'),materialName=$('#paletteMaterial').value.trim(),paletteName=$('#paletteName').value.trim();if(!paletteName)throw new Error('Provide a palette name');if(!materialName)throw new Error('Provide a material name');material.setAttribute('name',materialName);root.append(material);for(const cell of enabled){const paletteIndex=resources.palette.findIndex(item=>item.hex.toUpperCase()===cell.official.hex.toUpperCase()),description=cell.official.name,entry=documentNode.createElement('Entry'),cut=snapshotElement(documentNode,cell.laser_settings);entry.setAttribute('Thickness','-1.0000');entry.setAttribute('Desc',description);entry.setAttribute('NoThickTitle',`${description} ${cell.observed_hex}`);let index=cut.querySelector('index');if(!index){index=documentNode.createElement('index');cut.append(index)}index.setAttribute('Value',String(paletteIndex));let name=cut.querySelector('name');if(!name){name=documentNode.createElement('name');cut.append(name)}name.setAttribute('Value',description);entry.append(cut);material.append(entry)}const xml='<?xml version="1.0" encoding="utf-8"?>\n'+new XMLSerializer().serializeToString(documentNode),blob=new Blob([xml],{type:'application/xml'}),url=URL.createObjectURL(blob),link=document.createElement('a'),stem=paletteName.replace(/[^A-Za-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'color-lab-palette';link.href=url;link.download=`${stem}.clb`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
$('#savePalette').onsubmit=async e=>{e.preventDefault();const enabled=measurements.filter(c=>c.enabled),duplicates=new Map(),action=$('#reviewAction').value;if(!enabled.length){$('#saveResult').textContent=`Enable at least one swatch before ${action==='save'?'saving':'exporting'}.`;return}for(const cell of enabled){if(!/^#[0-9A-F]{6}$/.test(cell.observed_hex)||!resources.palette.some(color=>color.hex.toUpperCase()===cell.official.hex.toUpperCase())){$('#saveResult').textContent=`Cell ${cell.index} has an invalid detected or official hex value.`;return}const prior=duplicates.get(cell.official.hex.toUpperCase());if(prior){$('#saveResult').textContent=`Cells ${prior.index} and ${cell.index} both use ${cell.official.name}. Disable one or choose a different official color before continuing.`;return}duplicates.set(cell.official.hex.toUpperCase(),cell)}const button=e.submitter;button.disabled=true;try{if(action==='export'){exportColorPalette(enabled);$('#saveResult').textContent=`Exported ${enabled.length} unique settings to a LightBurn .clb file.`;return}if(guestMode)throw new Error('Sign in to save palettes to Swatch Palette Vault');$('#saveResult').textContent='Saving enabled swatches to Swatch Palette Vault…';const saved=await api('/account/color-palettes/discovered',{method:'POST',body:JSON.stringify({grid_id:grid.grid_id,palette_name:$('#paletteName').value,material_name:$('#paletteMaterial').value,swatches:enabled.map(c=>({index:c.index,observed_hex:c.observed_hex,rasterizer_hex:c.official.hex}))})});resources=await api('/account/resources');$('#saveResult').innerHTML=`Saved ${saved.saved_count} unique swatches as <a href="/vault.html">${esc(saved.name)}</a>.`}catch(error){$('#saveResult').textContent=`Could not ${action==='save'?'save':'export'} palette: ${error.message}`}finally{button.disabled=false}};
async function start(){config=await fetch('/config.json',{cache:'no-store'}).then(r=>r.json());if(token&&expires()){try{if(!await refresh())token=''}catch{token=''}if(!token)localStorage.removeItem('id_token')}guestMode=!token;try{resources=guestMode?await guestApi('/guest/config'):await api('/account/resources');resources.material_libraries=resources.material_libraries||[];showRegisteredAccess(!guestMode);fillLibrarySources();fillParameters();estimate();if(guestMode){document.querySelector('#recentGridSelect').closest('label').hidden=true;document.querySelectorAll('.account-save-option').forEach(option=>option.remove());$('#reviewAction').value='export'}else await populateGridChoices();try{grid=JSON.parse(sessionStorage.getItem('color_discovery_grid')||'null')}catch{grid=null}$('#recentGridSelect').value='';$('#measurementGridId').value='';$('#reviewAction').dispatchEvent(new Event('change'));$('#notice').textContent=guestMode?'Guest mode: upload a LightBurn Material Library to generate and measure grids. Selected settings can be exported as a .clb file, but cannot be saved to Swatch Palette Vault.':'Signed in. Use a saved Swatch Palette or upload a Material Library to begin.'}catch(error){showRegisteredAccess(!guestMode);$('#notice').textContent=`Could not initialize Color Lab: ${error.message}`}}
function colorLabEntries(){if(!usingSavedLibrary())return uploadedEntries;return(resources.material_libraries||[]).find(item=>item.library_id===$('#library').value)?.summary?.entries||[]}
function syncColorLabLabelChoices(metadataChoices){const source=selectedEntry(),choices=metadataChoices||((source&&colorLabEntries().filter(item=>item.material===source.material))||[]),select=$('#labelEntry'),previous=select.value;select.replaceChildren(...choices.map(item=>opt(String(item.entry_id),item.description||'Unnamed setting')));select.disabled=!choices.length;const automatic=choices.find(item=>String(item.description||'').trim().toLowerCase()==='labels')||source||choices[0];if([...select.options].some(item=>item.value===previous))select.value=previous;else if(automatic)select.value=String(automatic.entry_id)}
const fillColorLabEntries=fillEntries;
fillEntries=()=>{fillColorLabEntries();syncColorLabLabelChoices()};
const chooseColorLabEntry=chooseEntry;
chooseEntry=entryId=>{chooseColorLabEntry(entryId);syncColorLabLabelChoices()};
const activateColorLabGrid=activateGrid;
activateGrid=loaded=>{activateColorLabGrid(loaded);syncColorLabLabelChoices(loaded?.metadata?.label_options)};
function addColorLabLabelSelection(path,options){if(!String(path).includes('/color-discovery/grids')||String(options.method||'GET').toUpperCase()!=='POST'||!options.body)return options;const payload=JSON.parse(options.body);payload.label_entry_id=Number($('#labelEntry').value);return{...options,body:JSON.stringify(payload)}}
const colorLabGuestApiRequest=guestApi;
guestApi=(path,options={})=>colorLabGuestApiRequest(path,addColorLabLabelSelection(path,options));
const colorLabApiRequest=api;
api=async(path,options={},retry=true)=>{options=addColorLabLabelSelection(path,options);const result=await colorLabApiRequest(path,options,retry),method=String(options.method||'GET').toUpperCase();if(method==='POST'&&(path==='/color-discovery/grids'||path.startsWith('/color-discovery/grids/')||path==='/account/color-palettes/discovered'))queueMicrotask(()=>saveLastUsed('last_color_lab_form',colorLabFormValues()).catch(()=>{}));return result};
const exportColorPaletteFile=exportColorPalette;
exportColorPalette=enabled=>{exportColorPaletteFile(enabled);saveLastUsed('last_color_lab_form',colorLabFormValues()).catch(()=>{})};
$('#measure').addEventListener('click',()=>queueMicrotask(()=>saveLastUsed('last_color_lab_form',colorLabFormValues()).catch(()=>{})));
const startColorLab=start;
start=async()=>{await startColorLab();if(!guestMode){const values=lastUsedValues('last_color_lab_form');restoreColorLabForm(values);syncColorLabLabelChoices();if(hasOption($('#labelEntry'),values?.label_entry_id))$('#labelEntry').value=String(values.label_entry_id)}};
start().catch(e=>{showRegisteredAccess(!guestMode);$('#notice').textContent=`Could not initialize Color Lab: ${e.message}`});
