let token=localStorage.getItem("id_token")||sessionStorage.getItem("id_token"),refreshToken=localStorage.getItem("refresh_token")||sessionStorage.getItem("refresh_token"),config,pollTimer,pollLimitTimer;
if(token)localStorage.setItem("id_token",token);if(refreshToken)localStorage.setItem("refresh_token",refreshToken);sessionStorage.removeItem("id_token");sessionStorage.removeItem("refresh_token");
const LOG_POLL_LIMIT_MS=30*60*1000;
let activeTask=new URLSearchParams(location.search).get("task")||"",renderedTask="",renderedLogs=[],detailsElement=null,logsRequested=false;
const jobsElement=document.querySelector("#jobs"),noticeElement=document.querySelector("#notice");
const registeredAccess=document.querySelector("#registeredAccess"),registeredContent=document.querySelector("#registeredContent");
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
function showRegisteredAccess(authenticated){registeredAccess.hidden=authenticated;registeredContent.hidden=!authenticated;window.stagingShellSetAuthenticated?.(authenticated);if(!authenticated){token=null;refreshToken=null;localStorage.removeItem("id_token");localStorage.removeItem("refresh_token")}}
function tokenExpiresSoon(){try{const part=token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");const claims=JSON.parse(atob(part.padEnd(Math.ceil(part.length/4)*4,"=")));return Number(claims.exp||0)*1000<=Date.now()+30000}catch{return true}}
async function refreshSession(){if(!refreshToken)return false;const body=new URLSearchParams({grant_type:"refresh_token",client_id:config.client_id,refresh_token:refreshToken});const result=await fetch(`https://${config.cognito_domain}/oauth2/token`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body}).then(response=>response.json());if(!result.id_token)return false;token=result.id_token;localStorage.setItem("id_token",token);return true}
async function api(path,options={},retry=true){const response=await fetch(config.api_url+path,{...options,headers:{authorization:`Bearer ${token}`,...(options.headers||{})}});if(response.status===401&&retry&&await refreshSession())return api(path,options,false);const data=await response.json();if(!response.ok)throw new Error(data.message||`HTTP ${response.status}`);return data}
const formatTime=epoch=>epoch?new Date(epoch*1000).toLocaleString():"Unknown time";
const formatEndTime=job=>job.ended_at?formatTime(job.ended_at):["completed","failed"].includes(String(job.status||"").toLowerCase())?"Unknown time":"In progress";
function formatDuration(job){const start=Number(job.created_at),recordedEnd=Number(job.ended_at),terminal=["completed","failed"].includes(String(job.status||"").toLowerCase());if(!Number.isFinite(start)||start<=0)return "Unknown";if((!Number.isFinite(recordedEnd)||recordedEnd<=0)&&terminal)return "Unknown";const active=!Number.isFinite(recordedEnd)||recordedEnd<=0,end=active?Date.now()/1000:recordedEnd,total=Math.max(0,Math.floor(end-start)),days=Math.floor(total/86400),hours=Math.floor(total%86400/3600),minutes=Math.floor(total%3600/60),seconds=total%60,parts=[];if(days)parts.push(`${days}d`);if(hours||days)parts.push(`${hours}h`);if(minutes||hours||days)parts.push(`${minutes}m`);parts.push(`${seconds}s`);return `${parts.join(" ")}${active?" (in progress)":""}`}
function statusTone(status){status=String(status||"").toLowerCase();if(status==="completed")return "status-completed";if(status.includes("fail")||status.includes("error"))return "status-failed";if(status==="pending")return "status-pending";return "status-active"}
function jobTypeLabel(jobType){const labels={rasterizer:"Rasterizer",holographic_artwork:"Holographic Etching Lab"};return labels[jobType]||String(jobType||"Rasterizer").replaceAll("_"," ")}
function middleTruncate(value,maxLength=64){const characters=Array.from(String(value??""));if(characters.length<=maxLength)return characters.join("");const tailLength=Math.min(22,Math.floor((maxLength-1)/2)),headLength=maxLength-tailLength-1;return `${characters.slice(0,headLength).join("")}…${characters.slice(-tailLength).join("")}`}
function hasValue(value){return value!==undefined&&value!==null&&String(value).trim()!==""}
function parsedValue(value){if(typeof value!=="string")return value;try{return JSON.parse(value)}catch{return value}}
function formattedValue(value){const parsed=parsedValue(value);if(parsed&&typeof parsed==="object"){const entries=Object.entries(parsed);return entries.length?entries.map(([key,item])=>`${esc(key)} → ${esc(item)}`).join("<br>"):"None"}return esc(parsed)}
function definitionList(entries){const visible=entries.filter(([,value])=>hasValue(value));return visible.length?`<dl>${visible.map(([label,value])=>`<div class="detail-pair"><dt>${esc(label)}</dt><dd>${formattedValue(value)}</dd></div>`).join("")}</dl>`:"<p>None recorded.</p>"}
function parametersHtml(parameters){const values=parameters||{},usesWidth=Number(values.new_width)>0&&!(Number(values.new_height)>0),usesHeight=Number(values.new_height)>0&&!(Number(values.new_width)>0),dimension=usesWidth?["New width",values.new_width]:usesHeight?["New height",values.new_height]:null;return definitionList([["Pixel square mm",values.pixel_square_mm],dimension,["Image preset",values.image_preset],["Abstract filter",values.abstract_filter],["Abstract filter parameters",values.abstract_filter_parameters],["Geometry style",values.geometry_style],["Geometry style parameters",values.geometry_style_parameters]].filter(Boolean))}
function vaultSettingsHtml(parameters,materialName){const values=parameters||{},material=materialName||values.material,parsedOverrides=parsedValue(values.color_name_overrides),parsedSelected=parsedValue(values.selected_color_hexes),selectedHexes=Array.isArray(parsedSelected)?new Set(parsedSelected.map(color=>String(color).toUpperCase())):null;if(!parsedOverrides||typeof parsedOverrides!=="object"||Array.isArray(parsedOverrides))return definitionList([["Material",material],["Color name overrides",values.color_name_overrides]]);const swatches=Object.entries(parsedOverrides).filter(([color,name])=>hasValue(name)&&(selectedHexes===null||selectedHexes.has(String(color).toUpperCase()))).map(([color,name])=>{const hex=String(color).toUpperCase(),displayHex=/^#[0-9A-F]{6}$/.test(hex)?hex:"#303842";return `<div class="job-mini-swatch" style="--job-swatch-color:${esc(displayHex)}" title="${esc(name)}"><span class="job-mini-swatch-hex">${esc(hex)}</span><span class="job-mini-swatch-name">${esc(name)}</span></div>`}).join("");return `${material?`<p class="job-swatch-material"><strong>Material</strong><span>${esc(material)}</span></p>`:""}<div class="job-mini-swatch-grid">${swatches||"<p>None recorded.</p>"}</div>`}
function detailsTemplate(){return '<div class="job-details-grid"><section class="job-details-summary"><p class="status" data-job-status></p><h3 data-job-source></h3><div class="outputs job-primary-downloads" data-job-outputs></div><div class="job-time"><p><strong>Start Time:</strong> <span data-job-start-time></span></p><p><strong>End Time:</strong> <span data-job-end-time></span></p><p><strong>Job Duration:</strong> <span data-job-duration></span></p></div><p class="job-type"><strong>Job type:</strong> <span data-job-type></span></p></section><section class="job-details-column"><h3>Parameters</h3><div data-job-parameters></div></section><section class="job-details-column job-swatch-settings"><h3>Swatch Settings</h3><div data-job-vault-settings></div></section></div><p data-job-error hidden><strong>Error:</strong> <span></span></p><h3>Logs</h3><div class="log-controls"><button type="button" data-load-logs>Load logs</button><span class="log-note" data-log-note>Logs are loaded only when requested.</span></div><div class="job-log-list" data-job-logs aria-live="polite" aria-relevant="additions"></div><div class="job-delete-actions"><p class="retention-warning"><strong>Seven-day retention:</strong> Job history and files created or uploaded only for this job are automatically removed after seven days. You may delete them sooner below. Saved Material Libraries and palettes in the Swatch Palette Vault are not removed.</p><button class="danger" type="button" data-delete-job>Delete job and assets</button></div>'}
function renderList(jobs){noticeElement.textContent=jobs.length?`${jobs.length} retained history record${jobs.length===1?"":"s"}. Select a row to view its details.`:"No retained jobs.";jobsElement.innerHTML=jobs.map(job=>{const panelId=`job-details-${esc(job.task_id)}`,open=job.task_id===activeTask;return `<li class="job-record ${statusTone(job.status)}"><button class="job" data-task="${esc(job.task_id)}" aria-expanded="${open}" aria-controls="${panelId}"><span class="job-copy"><strong title="${esc(job.source_name)}">${esc(middleTruncate(job.source_name))}</strong><span data-job-summary>${esc(job.status)} · ${esc(formatTime(job.created_at))}</span></span><span class="job-indicator" aria-hidden="true">+</span></button><div id="${panelId}" class="job-details" data-details-for="${esc(job.task_id)}" ${open?"":"hidden"}>${open?"Loading job details…":""}</div></li>`}).join("")}
function setText(selector,value){const element=detailsElement?.querySelector(selector),text=String(value??"");if(element&&element.textContent!==text)element.textContent=text}
function updateHtml(selector,value){const element=detailsElement?.querySelector(selector),html=String(value??"");if(element&&element.dataset.content!==html){element.innerHTML=html;element.dataset.content=html}}
function logPayload(message){return String(message??"").replace(/^\[\d{2}:\d{2}:\d{2}\]\s?/,"")}
function displayedLogs(logs){const hiddenSections=new Set(["palette_names","material_library_layers","lightburn_layers","requested_limit_colors","effective_limit_colors"]);let hiddenIndent=null;return (logs||[]).map(value=>String(value??"")).filter(message=>{const payload=logPayload(message),content=payload.trimStart(),indent=payload.length-content.length;if(hiddenIndent!==null){if(content==="--- end job_settings.yaml ---"||content&&indent<=hiddenIndent)hiddenIndent=null;else return false}const section=content.match(/^([a-z_]+):\s*$/i);if(section&&hiddenSections.has(section[1].toLowerCase())){hiddenIndent=indent;return false}if(/^(?:requested_limit_colors|effective_limit_colors):/i.test(content))return false;if(/^Material layer '.*' assigned to LightBurn layer \d+:/i.test(content))return false;return true})}
function updateLogs(logs){const container=detailsElement?.querySelector("[data-job-logs]");if(!container)return;const messages=displayedLogs(logs);const prefixMatches=renderedLogs.length<=messages.length&&renderedLogs.every((value,index)=>value===messages[index]);if(!prefixMatches){container.replaceChildren();renderedLogs=[]}const fragment=document.createDocumentFragment();for(let index=renderedLogs.length;index<messages.length;index++){const message=document.createElement("div");message.className="job-log-message";message.textContent=messages[index];fragment.append(message)}container.append(fragment);if(!messages.length&&!container.childNodes.length){const empty=document.createElement("div");empty.className="job-log-message job-log-empty";empty.textContent="No retained runtime logs.";container.append(empty)}renderedLogs=messages}
function closeActive(){clearTimeout(pollTimer);clearTimeout(pollLimitTimer);for(const button of jobsElement.querySelectorAll("[data-task]")){button.setAttribute("aria-expanded","false");const panel=jobsElement.querySelector(`[data-details-for="${CSS.escape(button.dataset.task)}"]`);if(panel)panel.hidden=true}activeTask="";renderedTask="";renderedLogs=[];detailsElement=null;logsRequested=false;history.replaceState({},"","/history.html")}
function stopLogPolling(){clearTimeout(pollTimer);clearTimeout(pollLimitTimer);logsRequested=false;const button=detailsElement?.querySelector("[data-load-logs]"),note=detailsElement?.querySelector("[data-log-note]");if(button){button.disabled=false;button.textContent="Load logs"}if(note)note.textContent="Log polling stopped. Load logs to check again."}
function openRow(taskId){const button=jobsElement.querySelector(`[data-task="${CSS.escape(taskId)}"]`);if(!button)return null;for(const other of jobsElement.querySelectorAll("[data-task]")){const open=other===button;other.setAttribute("aria-expanded",String(open));const panel=jobsElement.querySelector(`[data-details-for="${CSS.escape(other.dataset.task)}"]`);if(panel)panel.hidden=!open}detailsElement=jobsElement.querySelector(`[data-details-for="${CSS.escape(taskId)}"]`);return button}
function outputBasename(output){return String(output?.name||"download").replaceAll("\\","/").split("/").pop()||"download"}
function rasterOutputRank(output){const name=outputBasename(output).toLowerCase();return name.endsWith(".svg")?0:name.endsWith(".lbrn2")?1:2}
function renderOutputs(outputs){const ordered=[...(outputs||[])].sort((left,right)=>rasterOutputRank(left)-rasterOutputRank(right)||outputBasename(left).localeCompare(outputBasename(right)));return ordered.map(output=>{const label=`Download ${outputBasename(output)}`;return `<p><a class="staging-action-button" href="${esc(output.download_url)}" title="${esc(label)}">${esc(label)}</a><span class="output-size">${(Number(output.bytes||0)/1048576).toFixed(2)} MB</span></p>`}).join("")||"<p>No retained outputs.</p>"}
function renderJob(job,button){if(renderedTask!==job.task_id){detailsElement.innerHTML=detailsTemplate();renderedTask=job.task_id;renderedLogs=[]}button.closest(".job-record").className=`job-record ${statusTone(job.status)}`;setText("[data-job-status]",job.status);setText("[data-job-source]",job.source_name);setText("[data-job-start-time]",formatTime(job.created_at));setText("[data-job-end-time]",formatEndTime(job));setText("[data-job-duration]",formatDuration(job));setText("[data-job-type]",jobTypeLabel(job.job_type));updateHtml("[data-job-parameters]",parametersHtml(job.run_parameters));updateHtml("[data-job-vault-settings]",vaultSettingsHtml(job.run_parameters,job.material_name));const error=detailsElement.querySelector("[data-job-error]");error.hidden=!job.error;setText("[data-job-error] span",job.error);updateHtml("[data-job-outputs]",renderOutputs(job.outputs));button.querySelector("[data-job-summary]").textContent=`${job.status} · ${formatTime(job.created_at)}`;if(job.logs_included)updateLogs(job.logs);const loadButton=detailsElement.querySelector("[data-load-logs]"),note=detailsElement.querySelector("[data-log-note]"),active=["pending","processing","uploading"].includes(job.status);loadButton.textContent=logsRequested&&active?"Stop polling":logsRequested?"Logs loaded":"Load logs";loadButton.disabled=logsRequested&&!active;note.textContent=logsRequested&&active?"Updating every three seconds for up to 30 minutes. Click Stop polling to stop sooner.":logsRequested?"Logs loaded. This job is complete.":"Logs are loaded only when requested."}
async function fetchJob(taskId,includeLogs=false){const button=openRow(taskId);if(!button)return;try{const job=await api(`/account/jobs/${taskId}${includeLogs?"?include_logs=true":""}`);if(activeTask!==taskId)return;renderJob(job,button);if(includeLogs&&["pending","processing","uploading"].includes(job.status))pollTimer=setTimeout(()=>fetchJob(taskId,true),3000)}catch(error){if(activeTask!==taskId)return;if(renderedTask!==taskId)detailsElement.textContent=`Could not load job: ${error.message}`;else setText("[data-job-status]",`Could not refresh job: ${error.message}`)}}
async function showJob(taskId){clearTimeout(pollTimer);clearTimeout(pollLimitTimer);const button=jobsElement.querySelector(`[data-task="${CSS.escape(taskId)}"]`);if(!button)return;if(activeTask===taskId&&button.getAttribute("aria-expanded")==="true")return closeActive();activeTask=taskId;renderedTask="";renderedLogs=[];logsRequested=false;openRow(taskId);detailsElement.textContent="Loading job details…";history.replaceState({},"",`/history.html?task=${encodeURIComponent(taskId)}`);await fetchJob(taskId,false)}
async function loadLogs(){if(!activeTask)return;if(logsRequested){stopLogPolling();return}logsRequested=true;const taskId=activeTask;clearTimeout(pollLimitTimer);pollLimitTimer=setTimeout(()=>{if(activeTask===taskId&&logsRequested)closeActive()},LOG_POLL_LIMIT_MS);const button=detailsElement.querySelector("[data-load-logs]");if(button){button.disabled=true;button.textContent="Loading logs…"}await fetchJob(activeTask,true)}
async function deleteJob(){if(!activeTask||!confirm("Delete this job history entry and all of its retained input and output assets? This cannot be undone."))return;const taskId=activeTask,button=detailsElement.querySelector("[data-delete-job]");button.disabled=true;button.textContent="Deleting…";try{const result=await api(`/account/jobs/${taskId}`,{method:"DELETE"});const row=jobsElement.querySelector(`[data-task="${CSS.escape(taskId)}"]`)?.closest(".job-record");closeActive();row?.remove();const count=jobsElement.children.length;noticeElement.textContent=`${count} retained history record${count===1?"":"s"}. Deleted ${result.deleted_assets||0} retained asset${result.deleted_assets===1?"":"s"}.`}catch(error){button.disabled=false;button.textContent="Delete job and assets";alert(`Could not delete job: ${error.message}`)}}
async function start(){config=await fetch("/config.json",{cache:"no-store"}).then(response=>response.json());if(!token){showRegisteredAccess(false);return}if(tokenExpiresSoon()){try{if(!await refreshSession()){showRegisteredAccess(false);return}}catch{showRegisteredAccess(false);return}}try{const result=await api("/account/jobs"),jobs=result.jobs||[];showRegisteredAccess(true);if(activeTask&&!jobs.some(job=>job.task_id===activeTask))activeTask="";renderList(jobs);if(activeTask){const taskId=activeTask;activeTask="";await showJob(taskId)}}catch(error){if(/401|unauthor|token|session/i.test(error.message)){showRegisteredAccess(false);return}showRegisteredAccess(true);noticeElement.textContent=`Could not load Job History: ${error.message}`}}
jobsElement.onclick=event=>{const remove=event.target.closest("[data-delete-job]");if(remove){deleteJob();return}const load=event.target.closest("[data-load-logs]");if(load){loadLogs();return}const button=event.target.closest("[data-task]");if(button)showJob(button.dataset.task)};
start().catch(error=>{if(!token){showRegisteredAccess(false);return}showRegisteredAccess(true);noticeElement.textContent=`Could not load Job History: ${error.message}`});
