let config,resources,token=localStorage.getItem("id_token")||sessionStorage.getItem("id_token"),refreshToken=localStorage.getItem("refresh_token")||sessionStorage.getItem("refresh_token"),calibration,photoImage,corners=[],measurements=[],guestMode=!token,guestAccessToken=sessionStorage.getItem("holographic_guest_access_token"),uploadedEntries=[];
if(token)localStorage.setItem("id_token",token);if(refreshToken)localStorage.setItem("refresh_token",refreshToken);sessionStorage.removeItem("id_token");sessionStorage.removeItem("refresh_token");
const $=selector=>document.querySelector(selector),esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
function tokenExpiresSoon(){try{const part=token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");const claims=JSON.parse(atob(part.padEnd(Math.ceil(part.length/4)*4,"=")));return Number(claims.exp||0)*1000<=Date.now()+30000}catch{return true}}
async function refreshSession(){if(!refreshToken)return false;const body=new URLSearchParams({grant_type:"refresh_token",client_id:config.client_id,refresh_token:refreshToken});const result=await fetch(`https://${config.cognito_domain}/oauth2/token`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body}).then(r=>r.json());if(!result.id_token)return false;token=result.id_token;localStorage.setItem("id_token",token);return true}
async function api(path,options={},retry=true){const response=await fetch(config.api_url+path,{...options,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...(options.headers||{})}});if(response.status===401&&retry&&await refreshSession())return api(path,options,false);const data=await response.json();if(!response.ok)throw new Error(data.message||`HTTP ${response.status}`);return data}
async function guestApi(path,options={}){const headers={"content-type":"application/json",...(options.headers||{})};if(guestAccessToken)headers["x-guest-capability"]=guestAccessToken;const response=await fetch(config.api_url+path,{...options,headers});const data=await response.json();if(!response.ok)throw new Error(data.message||`HTTP ${response.status}`);return data}
async function upload(file,target){const body=new FormData();Object.entries(target.fields).forEach(([key,value])=>body.append(key,value));body.append("file",file);const response=await fetch(target.url,{method:"POST",body});if(!response.ok)throw new Error(`Material Library upload failed (${response.status})`)}
function lastUsedValues(name){return resources?.preferences?.[name]?.values||null}
async function saveLastUsed(name,values){if(guestMode)return;const result=await api("/account/preferences",{method:"PATCH",body:JSON.stringify({[name]:values})});resources.preferences=result.preferences||resources.preferences||{}}
function hasOption(select,value){return [...select.options].some(item=>item.value===String(value??""))}
function holographicLabFormValues(){return{calibration_source:$("#calibrationSource").value,library_id:$("#calibrationLibrary").value,entry_id:$("#calibrationEntry").value,label_entry_id:$("#calibrationLabelEntry").value,material_name:$("#calibrationMaterial").value,cut_mode:$("#calibrationCutMode").value,laser_source:$("#laserSource").value,lens_field_mm:$("#lensField").value,columns:$("#gridColumns").value,rows:$("#gridRows").value,cell_mm:$("#cellSize").value,interval_low:$("#intervalLow").value,interval_high:$("#intervalHigh").value,sweep_parameter:$("#sweepParameter").value,sweep_low:$("#sweepLow").value,sweep_high:$("#sweepHigh").value,profile_name:$("#profileName").value,capture_camera:$("#captureCamera").value,capture_distance:$("#captureDistance").value,capture_angle:$("#captureAngle").value,capture_lighting:$("#captureLighting").value,capture_notes:$("#captureNotes").value}}
function restoreHolographicLabForm(values){if(!values)return;const source=$("#calibrationSource"),useSaved=values.calibration_source==="saved"&&hasOption(source,"saved")&&hasOption($("#calibrationLibrary"),values.library_id);source.value=useSaved?"saved":"upload";syncCalibrationSource();if(useSaved){$("#calibrationLibrary").value=values.library_id;fillCalibrationEntries();if(hasOption($("#calibrationEntry"),values.entry_id))$("#calibrationEntry").value=String(values.entry_id)}for(const [id,key] of [["calibrationMaterial","material_name"],["lensField","lens_field_mm"],["gridColumns","columns"],["gridRows","rows"],["cellSize","cell_mm"],["intervalLow","interval_low"],["intervalHigh","interval_high"],["sweepLow","sweep_low"],["sweepHigh","sweep_high"],["profileName","profile_name"],["captureCamera","capture_camera"],["captureDistance","capture_distance"],["captureAngle","capture_angle"],["captureLighting","capture_lighting"],["captureNotes","capture_notes"]])if(values[key]!==undefined)$("#"+id).value=values[key];for(const [id,key] of [["calibrationCutMode","cut_mode"],["laserSource","laser_source"],["sweepParameter","sweep_parameter"]])if(hasOption($("#"+id),values[key]))$("#"+id).value=values[key]}
function option(value,label){return new Option(label,value)}
function fillResources(){const libraries=resources.material_libraries||[];$("#calibrationLibrary").replaceChildren(option("","Choose a saved palette…"),...libraries.map(item=>option(item.library_id,item.name)));$("#calibrationSource").replaceChildren(option("upload","Upload a new LightBurn Material Library"),...(libraries.length?[option("saved","Use a saved Swatch Palette")]:[]));syncCalibrationSource()}
function updateRasterizerRecipeLink(recipeId=sessionStorage.getItem("last_holographic_recipe_id")){const link=$("#runRecipeInRasterizer");link.href=recipeId?`/?recipe=${encodeURIComponent(recipeId)}`:"/";link.textContent=recipeId?"Run Rasterizer with This Fauxlographic Palette":"Open Rasterizer"}
function syncCalibrationSource(){const saved=!guestMode&&$("#calibrationSource").value==="saved";$("#calibrationUploadRow").hidden=saved;$("#calibrationFile").disabled=saved;$("#calibrationFile").required=!saved;$("#calibrationLibraryRow").hidden=!saved;$("#calibrationLibrary").disabled=!saved;$("#calibrationLibrary").required=saved;if(saved)fillCalibrationEntries();else{$("#calibrationLibrary").value="";fillUploadedEntries()}}
function fillCalibrationEntries(){const library=(resources.material_libraries||[]).find(item=>item.library_id===$("#calibrationLibrary").value),entries=library?.summary?.entries||[];$("#calibrationEntry").replaceChildren(option("","Choose a setting…"),...entries.map(item=>option(String(item.entry_id),`${item.material||"Material"} · ${item.description}`)));$("#calibrationEntry").disabled=!entries.length;if(library?.material_name)$("#calibrationMaterial").value=library.material_name}
function fillUploadedEntries(){$("#calibrationEntry").replaceChildren(option("","Choose a setting…"),...uploadedEntries.map(item=>option(String(item.entry_id),`${item.material||"Material"} · ${item.description}`)));$("#calibrationEntry").disabled=!uploadedEntries.length}
$("#calibrationSource").onchange=syncCalibrationSource;
$("#calibrationLibrary").onchange=fillCalibrationEntries;
$("#calibrationFile").onchange=async event=>{uploadedEntries=[];const file=event.target.files[0];if(!file){fillUploadedEntries();return}try{const documentNode=new DOMParser().parseFromString(await file.text(),"application/xml");if(documentNode.querySelector("parsererror"))throw new Error("The selected file is not valid XML");let entryId=0;for(const material of documentNode.querySelectorAll("Material")){const materialName=material.getAttribute("name")||material.getAttribute("Name")||"Material";for(const entry of [...material.children].filter(node=>node.tagName==="Entry")){uploadedEntries.push({entry_id:entryId++,material:materialName,description:entry.getAttribute("Desc")||entry.getAttribute("desc")||"Unnamed setting"})}}if(!uploadedEntries.length)throw new Error("No Material Library settings were found");fillUploadedEntries();$("#calibrationMaterial").value=uploadedEntries[0].material;$("#calibrationResult").textContent=`Loaded ${uploadedEntries.length} settings from ${file.name}.`}catch(error){fillUploadedEntries();$("#calibrationResult").textContent=`Could not read Material Library: ${error.message}`}};
$("#calibrationEntry").onchange=()=>{const entries=$("#calibrationSource").value==="saved"?((resources.material_libraries||[]).find(item=>item.library_id===$("#calibrationLibrary").value)?.summary?.entries||[]):uploadedEntries,entry=entries.find(item=>Number(item.entry_id)===Number($("#calibrationEntry").value));if(entry?.material)$("#calibrationMaterial").value=entry.material};
$("#calibrationForm").onsubmit=async event=>{event.preventDefault();const result=$("#calibrationResult"),button=event.submitter,useSaved=!guestMode&&$("#calibrationSource").value==="saved",file=$("#calibrationFile").files[0];button.disabled=true;result.textContent="Building durable calibration files…";try{const payload={library_id:useSaved?$("#calibrationLibrary").value:"",entry_id:Number($("#calibrationEntry").value),material_name:$("#calibrationMaterial").value,cut_mode:$("#calibrationCutMode").value,laser_source:$("#laserSource").value,lens_field_mm:Number($("#lensField").value),columns:Number($("#gridColumns").value),rows:Number($("#gridRows").value),cell_mm:Number($("#cellSize").value),interval_low:Number($("#intervalLow").value),interval_high:Number($("#intervalHigh").value),sweep_parameter:$("#sweepParameter").value,sweep_low:Number($("#sweepLow").value),sweep_high:Number($("#sweepHigh").value)};if(useSaved){calibration=await api("/holographic/calibrations",{method:"POST",body:JSON.stringify(payload)})}else{if(!file)throw new Error("Upload a LightBurn Material Library");const request=guestMode?guestApi:api,grant=await request(guestMode?"/guest/holographic/calibration-uploads":"/holographic/calibration-uploads",{method:"POST",body:JSON.stringify({material_name:file.name,material_content_type:file.type||"application/octet-stream"})});if(guestMode){guestAccessToken=grant.guest_access_token;sessionStorage.setItem("holographic_guest_access_token",guestAccessToken)}await upload(file,grant.material);payload.upload_token=grant.upload_token;payload.material_key=grant.material.key;calibration=await request(`${guestMode?"/guest":""}/holographic/calibrations/${grant.task_id}`,{method:"POST",body:JSON.stringify(payload)})}sessionStorage.setItem("holographic_calibration",JSON.stringify(calibration));const stem=`holographic_calibration_${calibration.calibration_id}`;result.innerHTML=`Calibration grid ${esc(calibration.calibration_id)} is ready.<span class="holographic-downloads"><a class="staging-action-button holographic-download-button" href="${esc(calibration.downloads.svg)}" download="${stem}.svg">Download ${stem}.svg</a><a class="staging-action-button holographic-download-button" href="${esc(calibration.downloads.lightburn)}" download="${stem}.lbrn2">Download ${stem}.lbrn2</a></span>`;$("#captureResult").textContent="Engrave this grid, photograph it, and choose the photo below."}catch(error){result.textContent=`Could not build calibration grid: ${error.message}`}finally{button.disabled=false}};
const canvas=$("#captureCanvas"),context=canvas.getContext("2d",{willReadFrequently:true});
function defaultCorners(){const inset=Math.min(canvas.width,canvas.height)*.04;corners=[[inset,inset],[canvas.width-inset,inset],[canvas.width-inset,canvas.height-inset],[inset,canvas.height-inset]];drawPhoto()}
function overlayGrid(){const metadata=calibration?.metadata;if(!metadata||corners.length!==4)return;const columns=Number(metadata.columns),rows=Number(metadata.rows);if(!columns||!rows)return;context.save();context.lineWidth=1.5;context.strokeStyle="rgba(131,240,106,.88)";for(let column=1;column<columns;column++){const start=bilinear(column/columns,0),end=bilinear(column/columns,1);context.beginPath();context.moveTo(...start);context.lineTo(...end);context.stroke()}for(let row=1;row<rows;row++){const start=bilinear(0,row/rows),end=bilinear(1,row/rows);context.beginPath();context.moveTo(...start);context.lineTo(...end);context.stroke()}const radius=Math.max(8,Math.min(15,Math.min(canvas.width/columns,canvas.height/rows)*.12));context.font=`700 ${Math.max(9,Math.round(radius*.9))}px Courier New,monospace`;context.textAlign="center";context.textBaseline="middle";for(let row=0;row<rows;row++)for(let column=0;column<columns;column++){const index=row*columns+column+1,[x,y]=bilinear((column+.5)/columns,(row+.5)/rows);context.fillStyle="rgba(9,14,8,.78)";context.beginPath();context.arc(x,y,radius,0,Math.PI*2);context.fill();context.strokeStyle="#83f06a";context.stroke();context.fillStyle="#f2ecd0";context.fillText(String(index),x,y)}context.restore()}
function drawPhoto(){if(!photoImage)return;context.clearRect(0,0,canvas.width,canvas.height);context.drawImage(photoImage,0,0,canvas.width,canvas.height);if(corners.length){context.strokeStyle="#83f06a";context.lineWidth=3;context.beginPath();corners.forEach(([x,y],index)=>index?context.lineTo(x,y):context.moveTo(x,y));context.closePath();context.stroke();overlayGrid();corners.forEach(([x,y],index)=>{context.fillStyle="#83f06a";context.beginPath();context.arc(x,y,9,0,Math.PI*2);context.fill();context.fillStyle="#071007";context.fillText(String(index+1),x-3,y+4)})}}
$("#gridPhoto").onchange=event=>{const file=event.target.files[0];if(!file)return;const image=new Image();image.onload=()=>{const scale=Math.min(1000/image.naturalWidth,700/image.naturalHeight,1);canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));photoImage=image;canvas.hidden=false;defaultCorners();$("#resetCorners").disabled=false;$("#analyzePhoto").disabled=!calibration;$("#captureResult").textContent="Drag each green corner onto the photographed grid boundary so the numbered overlay matches the cells, then measure the colors."};image.src=URL.createObjectURL(file)};
let dragged=null;canvas.onpointerdown=event=>{const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*canvas.width/rect.width,y=(event.clientY-rect.top)*canvas.height/rect.height;dragged=corners.reduce((best,point,index)=>Math.hypot(point[0]-x,point[1]-y)<best.distance?{index,distance:Math.hypot(point[0]-x,point[1]-y)}:best,{index:null,distance:Infinity}).index;canvas.setPointerCapture(event.pointerId)};canvas.onpointermove=event=>{if(dragged===null)return;const rect=canvas.getBoundingClientRect();corners[dragged]=[Math.max(0,Math.min(canvas.width,(event.clientX-rect.left)*canvas.width/rect.width)),Math.max(0,Math.min(canvas.height,(event.clientY-rect.top)*canvas.height/rect.height))];drawPhoto()};canvas.onpointerup=canvas.onpointercancel=()=>{dragged=null};
$("#resetCorners").onclick=defaultCorners;
function bilinear(u,v){const top=[corners[0][0]*(1-u)+corners[1][0]*u,corners[0][1]*(1-u)+corners[1][1]*u],bottom=[corners[3][0]*(1-u)+corners[2][0]*u,corners[3][1]*(1-u)+corners[2][1]*u];return [top[0]*(1-v)+bottom[0]*v,top[1]*(1-v)+bottom[1]*v]}
function sampledRgb(x,y){const radius=Math.max(2,Math.round(Math.min(canvas.width,canvas.height)/250)),data=context.getImageData(Math.max(0,Math.round(x)-radius),Math.max(0,Math.round(y)-radius),Math.min(radius*2+1,canvas.width-Math.max(0,Math.round(x)-radius)),Math.min(radius*2+1,canvas.height-Math.max(0,Math.round(y)-radius))).data,total=data.length/4,sums=[0,0,0];for(let i=0;i<data.length;i+=4){sums[0]+=data[i];sums[1]+=data[i+1];sums[2]+=data[i+2]}return sums.map(value=>Math.round(value/total))}
function renderMeasurements(){$("#recipeGrid").innerHTML=measurements.map(item=>`<label class="recipe-card" data-index="${item.index}"><input class="keepRecipe" type="checkbox" checked><input class="recipeName" value="Fauxlographic ${String(item.index).padStart(2,"0")}"><span class="chip" style="background:${item.observed_hex}"></span><small>${item.observed_hex} · ${Number(item.interval_mm).toFixed(3)} mm · ${Number(item.angle_degrees).toFixed(1)}°</small></label>`).join("");$("#saveRecipes").disabled=!measurements.length}
$("#analyzePhoto").onclick=()=>{if(!calibration||!photoImage)return;context.drawImage(photoImage,0,0,canvas.width,canvas.height);const {columns,rows,cells}=calibration.metadata;measurements=cells.map(cell=>{const [x,y]=bilinear((Number(cell.column)-.5)/columns,(Number(cell.row)-.5)/rows),rgb=sampledRgb(x,y);return {...cell,observed_rgb:rgb,observed_hex:"#"+rgb.map(value=>value.toString(16).padStart(2,"0")).join("").toUpperCase()}});drawPhoto();renderMeasurements();$("#captureResult").textContent=`Measured ${measurements.length} cells locally. Review the fauxlographic swatch colors below.`};
function guestPalette(selected){const known=new Map((calibration.metadata.cells||[]).map(cell=>[Number(cell.index),cell]));const recipes=selected.map(item=>{const rgb=item.observed_rgb.map(value=>Math.max(0,Math.min(255,Number(value)||0)));return {name:item.name,observed_rgb:rgb,observed_hex:"#"+rgb.map(value=>Math.round(value).toString(16).padStart(2,"0")).join("").toUpperCase(),...known.get(Number(item.index))}});return {kind:"holographic_calibration_profile",schema_version:2,status:"recipe_palette_ready",self_contained:true,profile_id:crypto.randomUUID(),profile_name:$("#profileName").value.trim(),grid:calibration.metadata,capture:{camera:$("#captureCamera").value,distance_mm:$("#captureDistance").value,viewing_angle:$("#captureAngle").value,lighting:$("#captureLighting").value,notes:$("#captureNotes").value},black_setting:calibration.metadata.embedded_black_setting||null,recipes}}
function downloadGuestPalette(profile){const blob=new Blob([JSON.stringify(profile,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a"),stem=(profile.profile_name||"holographic-swatch-palette").replace(/[^A-Za-z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")||"holographic-swatch-palette";link.href=url;link.download=`${stem}.json`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
$("#saveRecipes").onclick=async()=>{const result=$("#recipeResult"),button=$("#saveRecipes"),selected=[...$("#recipeGrid").querySelectorAll(".recipe-card")].filter(card=>card.querySelector(".keepRecipe").checked).map(card=>{const measured=measurements.find(item=>item.index===Number(card.dataset.index));return {index:measured.index,name:card.querySelector(".recipeName").value.trim(),observed_rgb:measured.observed_rgb}});button.disabled=true;result.textContent=guestMode?"Preparing Fauxlographic Swatch Palette download…":"Saving Fauxlographic Swatch Palette…";try{if(!selected.length)throw new Error("Keep at least one measured calibration cell");if(!$("#profileName").value.trim())throw new Error("Provide a Fauxlographic Swatch Palette name");if(guestMode){const profile=guestPalette(selected);downloadGuestPalette(profile);result.textContent=`Downloaded ${profile.recipes.length} fauxlographic swatches. Guest palettes are not retained; keep this file to import after signing in.`}else{const saved=await api("/account/holographic-recipes/measured",{method:"POST",body:JSON.stringify({calibration_id:calibration.calibration_id,profile_name:$("#profileName").value,capture:{camera:$("#captureCamera").value,distance_mm:$("#captureDistance").value,viewing_angle:$("#captureAngle").value,lighting:$("#captureLighting").value,notes:$("#captureNotes").value},measurements:selected})});result.textContent=`Saved ${saved.recipe_count} fauxlographic swatches to the Swatch Palette Vault.`;sessionStorage.setItem("last_holographic_recipe_id",saved.recipe_id);updateRasterizerRecipeLink(saved.recipe_id);resources=await api("/account/resources");fillResources()}}catch(error){result.textContent=`Could not ${guestMode?"download":"save"} Fauxlographic Swatch Palette: ${error.message}`}finally{button.disabled=false}};
async function start(){config=await fetch("/config.json",{cache:"no-store"}).then(r=>r.json());if(token&&tokenExpiresSoon()&&!await refreshSession()){token="";localStorage.removeItem("id_token")}guestMode=!token;resources=guestMode?{material_libraries:[]}:await api("/account/resources");fillResources();updateRasterizerRecipeLink();try{calibration=JSON.parse(sessionStorage.getItem("holographic_calibration")||"null")}catch{calibration=null}if(calibration){$("#calibrationResult").textContent=`Calibration ${calibration.calibration_id} is retained in this browser session.`;$("#analyzePhoto").disabled=!photoImage}if(guestMode){$("#saveRecipes").textContent="Download Fauxlographic Swatch Palette";$("#runRecipeInRasterizer").textContent="Open Rasterizer";$("#notice").textContent="Guest mode: upload a LightBurn Material Library to build a calibration grid. Your measured Fauxlographic Swatch Palette can be downloaded, but it is not retained."}else{$("#notice").textContent="Signed in. Choose a saved Swatch Palette or upload a new Material Library, then complete the calibration loop."}}
function syncCalibrationLabelChoices(){const saved=!guestMode&&$("#calibrationSource").value==="saved",entries=saved?((resources.material_libraries||[]).find(item=>item.library_id===$("#calibrationLibrary").value)?.summary?.entries||[]):uploadedEntries,source=entries.find(item=>String(item.entry_id)===$("#calibrationEntry").value),choices=source?entries.filter(item=>item.material===source.material):[],select=$("#calibrationLabelEntry"),previous=select.value;select.replaceChildren(...choices.map(item=>option(String(item.entry_id),item.description||"Unnamed setting")));select.disabled=!choices.length;const automatic=choices.find(item=>String(item.description||"").trim().toLowerCase()==="labels")||source||choices[0];if([...select.options].some(item=>item.value===previous))select.value=previous;else if(automatic)select.value=String(automatic.entry_id)}
new MutationObserver(syncCalibrationLabelChoices).observe($("#calibrationEntry"),{childList:true});
$("#calibrationEntry").addEventListener("change",syncCalibrationLabelChoices);
function addHolographicLabelSelection(path,options){if(!String(path).includes("/holographic/calibrations")||String(options.method||"GET").toUpperCase()!=="POST"||!options.body)return options;const payload=JSON.parse(options.body);payload.label_entry_id=Number($("#calibrationLabelEntry").value);return{...options,body:JSON.stringify(payload)}}
const holographicGuestApiRequest=guestApi;
guestApi=(path,options={})=>holographicGuestApiRequest(path,addHolographicLabelSelection(path,options));
const holographicApiRequest=api;
api=async(path,options={},retry=true)=>{options=addHolographicLabelSelection(path,options);const result=await holographicApiRequest(path,options,retry),method=String(options.method||"GET").toUpperCase();if(method==="POST"&&(path==="/holographic/calibrations"||path.startsWith("/holographic/calibrations/")||path==="/account/holographic-recipes/measured"))queueMicrotask(()=>saveLastUsed("last_holographic_lab_form",holographicLabFormValues()).catch(()=>{}));return result};
const startHolographicLab=start;
start=async()=>{await startHolographicLab();if(!guestMode){const values=lastUsedValues("last_holographic_lab_form");restoreHolographicLabForm(values);syncCalibrationLabelChoices();if(hasOption($("#calibrationLabelEntry"),values?.label_entry_id))$("#calibrationLabelEntry").value=String(values.label_entry_id)}};
start().catch(error=>$("#notice").textContent=`Could not initialize Fauxlographic Lab: ${error.message}`);
