let config,resources={},pollTimer,previewFrame;
let token=localStorage.getItem("id_token")||sessionStorage.getItem("id_token");
let refreshToken=localStorage.getItem("refresh_token")||sessionStorage.getItem("refresh_token");
let layers=[],activeLayer=0;
const COLORS=["#f45b69","#ffb34d","#8bd450","#43c7bb","#5596f6","#b56ce2"];
const GEARS=[24,30,32,36,40,42,45,48,56,60];
const TRACK_TEETH={circle:96,oval:105,rounded_square:120,rounded_triangle:105,custom:120};
const $=value=>document.querySelector(value);
const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));

function newLayer(index){return{name:`Drawing ${index+1}`,track:["circle","oval","rounded_triangle"][index%3],custom_svg:null,gear_teeth:[40,32,56][index%3],pen_hole:[5,4,6][index%3],side:"inside",start_mark:index+1,direction:index%2?"counterclockwise":"clockwise",rotation_quarter_turns:index%4,include_track:false,output_mode:"line",fill_thickness_mm:1.2}}
function palettes(){return(resources.material_libraries||[]).filter(item=>item.library_intent==="processing_palette")}
function palette(){return palettes().find(item=>item.library_id===$("#processingPalette").value)}
function materialNames(item){return[...new Set([...(item?.summary?.logical_material_names||[]),...(item?.summary?.entries||[]).map(entry=>entry.material)].map(v=>String(v||"").trim()).filter(Boolean))]}
function entries(){const material=$("#processingMaterial").value;return(palette()?.summary?.entries||[]).filter(entry=>String(entry.material||"")===material)}
function roleEntry(role){const item=palette(),material=$("#processingMaterial").value,assignments=(resources.preferences?.processing_palette_role_assignments||{})[item?.library_id]||{},roles=assignments.materials&&typeof assignments.materials==="object"?(assignments.materials[material]||{}):assignments,value=String(roles[role]||"").trim();return entries().find(entry=>String(entry.entry_ref||"")===value)||entries().find(entry=>String(entry.description||"").trim().toLowerCase()===role.toLowerCase())}
function populatePalettes(){const list=palettes();$("#processingPalette").innerHTML=list.map(item=>`<option value="${esc(item.library_id)}">${esc(item.name)}</option>`).join("");populateMaterials()}
function populateMaterials(){const names=materialNames(palette());$("#processingMaterial").innerHTML=names.map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join("");populateSettings()}
function populateSettings(){const line=entries().filter(entry=>String(entry.type||"").toLowerCase()==="cut"),fill=entries().filter(entry=>String(entry.type||"").toLowerCase()==="scan");$("#scoreSetting").innerHTML=line.map(entry=>`<option value="${esc(entry.entry_ref)}">${esc(entry.description)}</option>`).join("");$("#fillSetting").innerHTML=fill.map(entry=>`<option value="${esc(entry.entry_ref)}">${esc(entry.description)}</option>`).join("");const preferredLine=roleEntry("Score")||roleEntry("Cut"),preferredFill=roleEntry("Fill");if(preferredLine)$("#scoreSetting").value=preferredLine.entry_ref;if(preferredFill)$("#fillSetting").value=preferredFill.entry_ref;updatePaletteStatus()}
function updatePaletteStatus(){const needsLine=layers.some(layer=>layer.output_mode==="line"||layer.include_track),needsFill=layers.some(layer=>layer.output_mode==="fill"),valid=palette()&&(!needsLine||$("#scoreSetting").value)&&(!needsFill||$("#fillSetting").value);$("#generate").disabled=!valid;$("#paletteStatus").textContent=!palette()?"Import or create a Processing Palette before generating.":needsFill&&!$("#fillSetting").value?"This material needs a LightBurn Fill setting for filled ribbons.":needsLine&&!$("#scoreSetting").value?"This material needs a LightBurn Line setting.":"Role assignments initialize the Line and Fill selections when available."}

function options(values,current){return values.map(([value,label])=>`<option value="${value}" ${String(current)===String(value)?"selected":""}>${label}</option>`).join("")}
function layerCard(layer,index){return`<article class="layer-card" data-layer="${index}"><div class="layer-heading"><div><h3>Drawing ${index+1}</h3><p>${esc(layer.name)}</p></div><div class="layer-actions"><button type="button" class="spiralgrap-button" data-action="duplicate">Duplicate</button><button type="button" class="spiralgrap-button" data-action="up" ${index===0?"disabled":""}>Earlier</button><button type="button" class="spiralgrap-button" data-action="down" ${index===layers.length-1?"disabled":""}>Later</button><button type="button" class="spiralgrap-button" data-action="remove" ${layers.length===1?"disabled":""}>Remove</button></div></div><div class="layer-controls">
<label>Drawing name<input data-field="name" maxlength="80" value="${esc(layer.name)}"></label>
<label>Track plate<select data-field="track">${options([["circle","96 · Circle"],["oval","105 · Oval"],["rounded_triangle","105 · Rounded triangle"],["rounded_square","120 · Rounded square"],["custom","Custom closed SVG"]],layer.track)}</select></label>
<label class="custom-track" ${layer.track==="custom"?"":"hidden"}>Custom track SVG<input data-field="custom_file" type="file" accept="image/svg+xml,.svg"></label><p class="custom-status" ${layer.track==="custom"?"":"hidden"}>${layer.custom_svg?`Loaded ${esc(layer.custom_svg.name)}. The largest closed path is used.`:"Choose an SVG containing at least one closed path."}</p>
<label>Rolling gear<select data-field="gear_teeth">${options(GEARS.map(value=>[value,`${value} · Gear ${value}`]),layer.gear_teeth)}</select></label>
<label>Pen hole<select data-field="pen_hole">${options([1,2,3,4,5,6].map(value=>[value,`${value} · ${value===1?"near center":value===6?"near edge":"offset"}`]),layer.pen_hole)}</select></label>
<label>Rolling position<select data-field="side">${options([["inside","Inside the track"],["outside","Outside the track"]],layer.side)}</select></label>
<label>Starting mark<select data-field="start_mark">${options([1,2,3,4,5,6,7,8].map(value=>[value,`Mark ${value}`]),layer.start_mark)}</select></label>
<label>Rolling direction<select data-field="direction">${options([["clockwise","Clockwise"],["counterclockwise","Counterclockwise"]],layer.direction)}</select></label>
<label>Track orientation<select data-field="rotation_quarter_turns">${options([[0,"0°"],[1,"90°"],[2,"180°"],[3,"270°"]],layer.rotation_quarter_turns)}</select></label>
<label>Output mode<select data-field="output_mode">${options([["line","Line / Cut · open path"],["fill","Filled ribbon · closed path"]],layer.output_mode)}</select></label>
<label class="fill-thickness" ${layer.output_mode==="fill"?"":"hidden"}>Ribbon thickness (mm)<input data-field="fill_thickness_mm" type="number" min="0.1" max="25" step="0.1" value="${layer.fill_thickness_mm}"></label>
<label class="check-control"><input data-field="include_track" type="checkbox" ${layer.include_track?"checked":""}> Include track outline</label>
</div></article>`}
function syncSlider(){activeLayer=Math.max(0,Math.min(activeLayer,layers.length-1));$("#layerPreviewSlider").max=String(layers.length);$("#layerPreviewSlider").value=String(activeLayer+1);$("#layerPreviewPosition").textContent=`Drawing ${activeLayer+1} of ${layers.length}`;$("#layerPreviewName").textContent=layers[activeLayer]?.name||"Drawing"}
function renderLayers(){$("#layerList").innerHTML=layers.map(layerCard).join("");syncSlider();updatePaletteStatus();schedulePreview()}

function builtInPoints(track){const count=720,points=[];for(let i=0;i<count;i++){const t=Math.PI*2*i/count;let x,y;if(track==="circle"){x=.5*Math.cos(t);y=.5*Math.sin(t)}else if(track==="oval"){x=.5*Math.cos(t);y=.34*Math.sin(t)}else if(track==="rounded_triangle"){const r=.39+.07*Math.cos(3*t);x=r*Math.sin(t);y=-r*Math.cos(t)}else{const p=4,r=.49/(Math.abs(Math.cos(t))**p+Math.abs(Math.sin(t))**p)**(1/p);x=r*Math.cos(t);y=r*Math.sin(t)}points.push([x,y])}points.push(points[0]);return points}
function rotatePoints(points,turns){const angle=turns*Math.PI/2,c=Math.cos(angle),s=Math.sin(angle);return points.map(([x,y])=>[x*c-y*s,x*s+y*c])}
function geometryPoints(svg){
  const documentNode=new DOMParser().parseFromString(svg,"image/svg+xml"),host=document.createElement("div");
  host.style.cssText="position:fixed;left:-10000px;top:-10000px;visibility:hidden";
  host.innerHTML=new XMLSerializer().serializeToString(documentNode.documentElement);document.body.append(host);
  try{
    let best=null,bestLength=0;
    for(const node of host.querySelectorAll("path,circle,ellipse,rect,polygon,polyline")){
      if(typeof node.getTotalLength!=="function")continue;
      const length=node.getTotalLength(),first=node.getPointAtLength(0),last=node.getPointAtLength(length);
      if(Math.hypot(first.x-last.x,first.y-last.y)>Math.max(.01,length*.0001))continue;
      if(length>bestLength){best=node;bestLength=length}
    }
    if(!best)throw new Error("The custom track must contain a closed vector path.");
    const points=[];for(let i=0;i<=720;i++){const point=best.getPointAtLength(bestLength*i/720);points.push([point.x,point.y])}
    const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),extent=Math.max(maxX-minX,maxY-minY)||1,cx=(minX+maxX)/2,cy=(minY+maxY)/2;
    return points.map(([x,y])=>[(x-cx)/extent,(y-cy)/extent]);
  }finally{host.remove()}
}
function trackPoints(layer){if(layer.track!=="custom")return rotatePoints(builtInPoints(layer.track),layer.rotation_quarter_turns);if(!layer.custom_svg)return rotatePoints(builtInPoints("circle"),layer.rotation_quarter_turns);if(!layer._trackPoints)layer._trackPoints=rotatePoints(geometryPoints(layer.custom_svg.svg),layer.rotation_quarter_turns);return layer._trackPoints}
function cumulative(points){const values=[0];for(let i=1;i<points.length;i++)values.push(values[i-1]+Math.hypot(points[i][0]-points[i-1][0],points[i][1]-points[i-1][1]));return values}
function sample(points,lengths,distance){const total=lengths.at(-1),target=((distance%total)+total)%total;let low=0,high=lengths.length-1;while(low+1<high){const mid=(low+high)>>1;if(lengths[mid]<=target)low=mid;else high=mid}const span=lengths[high]-lengths[low]||1,f=(target-lengths[low])/span,a=points[low],b=points[high],dx=b[0]-a[0],dy=b[1]-a[1],m=Math.hypot(dx,dy)||1;return[a[0]+dx*f,a[1]+dy*f,dx/m,dy/m]}
function gcd(a,b){while(b)[a,b]=[b,a%b];return a}
function curvePoints(layer){const track=trackPoints(layer),lengths=cumulative(track),perimeter=lengths.at(-1),trackTeeth=TRACK_TEETH[layer.track],gear=Number(layer.gear_teeth),gearRadius=perimeter/(2*Math.PI)*gear/trackTeeth,penRadius=gearRadius*[0,.2,.36,.52,.68,.82,.94][Number(layer.pen_hole)],loops=gear/gcd(trackTeeth,gear),samples=Math.min(10000,Math.max(1200,loops*trackTeeth*5)),phase=(Number(layer.start_mark)-1)*Math.PI/4,roll=layer.direction==="clockwise"?-1:1,side=layer.side==="inside"?-1:1,result=[];for(let i=0;i<=samples;i++){const distance=perimeter*loops*i/samples,[x,y,tx,ty]=sample(track,lengths,distance),nx=ty,ny=-tx,cx=x+nx*gearRadius*side,cy=y+ny*gearRadius*side,angle=phase+roll*side*distance/gearRadius;result.push([cx+Math.cos(angle)*penRadius,cy+Math.sin(angle)*penRadius])}return result}
function bounds(points){const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);return[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)]}
function drawLayer(canvas,layer,index,alpha=1,clear=false){const context=canvas.getContext("2d");if(clear)context.clearRect(0,0,canvas.width,canvas.height);let curve,track;try{curve=curvePoints(layer);track=layer.include_track?trackPoints(layer):null}catch{return}const b=bounds(track?[...curve,...track]:curve),extent=Math.max(b[2]-b[0],b[3]-b[1])||1,scale=canvas.width*.84/extent,cx=(b[0]+b[2])/2,cy=(b[1]+b[3])/2;context.save();context.globalAlpha=alpha;context.translate(canvas.width/2-cx*scale,canvas.height/2-cy*scale);context.scale(scale,scale);context.beginPath();curve.forEach(([x,y],i)=>i?context.lineTo(x,y):context.moveTo(x,y));context.strokeStyle=COLORS[index%COLORS.length];context.lineJoin="round";context.lineCap="round";context.lineWidth=layer.output_mode==="fill"?Math.max(.002,Number(layer.fill_thickness_mm)/(Number($("#diameter").value)||150)*extent):.0025;context.stroke();if(track){context.beginPath();track.forEach(([x,y],i)=>i?context.lineTo(x,y):context.moveTo(x,y));context.closePath();context.globalAlpha=alpha*.4;context.lineWidth=.002;context.stroke()}context.restore()}
function schedulePreview(){cancelAnimationFrame(previewFrame);previewFrame=requestAnimationFrame(()=>{drawLayer($("#activePreview"),layers[activeLayer],activeLayer,1,true);const canvas=$("#stackPreview"),context=canvas.getContext("2d");context.clearRect(0,0,canvas.width,canvas.height);layers.forEach((layer,index)=>drawLayer(canvas,layer,index,.68,false))})}

async function normalizeSvg(file){if(!file||!(file.type==="image/svg+xml"||file.name.toLowerCase().endsWith(".svg")))throw new Error("Choose an SVG file.");if(file.size>65536)throw new Error("Custom SVG files must be no larger than 64 KB.");const text=await file.text(),doc=new DOMParser().parseFromString(text,"image/svg+xml"),root=doc.documentElement;if(root.nodeName.toLowerCase()==="parsererror"||root.localName!=="svg")throw new Error("The custom SVG could not be read.");const allowed=new Set(["svg","g","path","rect","circle","ellipse","polygon","polyline"]);for(const element of doc.querySelectorAll("*")){const name=element.localName?.toLowerCase();if(!allowed.has(name))throw new Error(`SVG element <${name||"unknown"}> is not supported.`);for(const attribute of [...element.attributes]){const key=attribute.name.toLowerCase(),value=attribute.value.toLowerCase();if(key.startsWith("on")||key.includes("href")||value.includes("url(")||value.includes("javascript:")||value.includes("data:"))throw new Error("Embedded or external SVG content is not supported.")}}const svg=new XMLSerializer().serializeToString(root);geometryPoints(svg);return{name:file.name.slice(0,120),svg}}
function payload(){return{project_name:$("#projectName").value,diameter_mm:$("#diameter").value,workbed_width_mm:$("#workbedWidth").value,workbed_height_mm:$("#workbedHeight").value,processing_palette_id:$("#processingPalette").value,material:$("#processingMaterial").value,score_entry_ref:$("#scoreSetting").value,fill_entry_ref:$("#fillSetting").value,layers:layers.map(({_trackPoints,...layer})=>layer)}}
function tokenExpiresSoon(){try{const part=token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");const claims=JSON.parse(atob(part.padEnd(Math.ceil(part.length/4)*4,"=")));return Number(claims.exp||0)*1000<=Date.now()+30000}catch{return true}}
async function refreshSession(){if(!refreshToken)return false;const body=new URLSearchParams({grant_type:"refresh_token",client_id:config.client_id,refresh_token:refreshToken}),result=await fetch(`https://${config.cognito_domain}/oauth2/token`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body}).then(r=>r.json());if(!result.id_token)return false;token=result.id_token;localStorage.setItem("id_token",token);return true}
async function api(path,options={},retry=true){const response=await fetch(config.api_url+path,{...options,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...(options.headers||{})}});if(response.status===401&&retry&&await refreshSession())return api(path,options,false);const data=await response.json();if(!response.ok)throw new Error(data.message||`HTTP ${response.status}`);return data}
async function poll(taskId){clearTimeout(pollTimer);try{const job=await api(`/jobs/${taskId}`);$("#status").textContent=`${job.status.toUpperCase()} · ${taskId}`;if(job.status==="completed"){$("#generate").disabled=false;$("#outputs").innerHTML=(job.outputs||[]).map(output=>`<a class="spiralgrap-button" href="${esc(output.download_url)}">Download ${esc(String(output.name||"output").split("/").pop())}</a>`).join("");return}if(job.status==="failed")throw new Error(job.error||"SpiralGraph generation failed");pollTimer=setTimeout(()=>poll(taskId),3000)}catch(error){$("#status").textContent=`ERROR · ${error.message}`;$("#status").classList.add("error");$("#generate").disabled=false}}

function syncDimensions(){const diameter=Math.max(20,Math.min(1000,Number($("#diameter").value)||150));for(const input of [$("#workbedWidth"),$("#workbedHeight")]){input.min=String(diameter);if(Number(input.value)<diameter)input.value=String(diameter)}schedulePreview()}
$("#processingPalette").addEventListener("change",populateMaterials);$("#processingMaterial").addEventListener("change",populateSettings);$("#scoreSetting").addEventListener("change",updatePaletteStatus);$("#fillSetting").addEventListener("change",updatePaletteStatus);$("#diameter").addEventListener("input",syncDimensions);
$("#addLayer").addEventListener("click",()=>{if(layers.length>=6)return;layers.push(newLayer(layers.length));activeLayer=layers.length-1;renderLayers()});
$("#layerList").addEventListener("click",event=>{const card=event.target.closest("[data-layer]"),button=event.target.closest("[data-action]");if(!card||!button)return;const index=Number(card.dataset.layer),action=button.dataset.action;if(action==="duplicate"&&layers.length<6){layers.splice(index+1,0,structuredClone(layers[index]));layers[index+1].name+=` copy`;activeLayer=index+1}else if(action==="remove"&&layers.length>1){layers.splice(index,1)}else if(action==="up"&&index>0){[layers[index-1],layers[index]]=[layers[index],layers[index-1]];activeLayer=index-1}else if(action==="down"&&index<layers.length-1){[layers[index+1],layers[index]]=[layers[index],layers[index+1]];activeLayer=index+1}renderLayers()});
$("#layerList").addEventListener("input",event=>{const card=event.target.closest("[data-layer]"),field=event.target.dataset.field;if(!card||!field||field==="custom_file")return;const layer=layers[Number(card.dataset.layer)];layer[field]=event.target.type==="checkbox"?event.target.checked:event.target.type==="number"?Number(event.target.value):["gear_teeth","pen_hole","start_mark","rotation_quarter_turns"].includes(field)?Number(event.target.value):event.target.value;delete layer._trackPoints;if(["track","output_mode"].includes(field))renderLayers();else{syncSlider();updatePaletteStatus();schedulePreview()}});
$("#layerList").addEventListener("change",async event=>{if(event.target.dataset.field!=="custom_file")return;const layer=layers[Number(event.target.closest("[data-layer]").dataset.layer)];try{layer.custom_svg=await normalizeSvg(event.target.files[0]);delete layer._trackPoints;renderLayers()}catch(error){alert(error.message);event.target.value=""}});
$("#layerPreviewSlider").addEventListener("input",event=>{activeLayer=Number(event.target.value)-1;syncSlider();schedulePreview()});
$("#spiralgrapForm").addEventListener("submit",async event=>{event.preventDefault();$("#generate").disabled=true;$("#outputs").innerHTML="";$("#status").classList.remove("error");$("#status").textContent="Submitting SpiralGraph job…";try{const result=await api("/spiralgraph/jobs",{method:"POST",body:JSON.stringify(payload())});history.replaceState({},"",`${location.pathname}?task=${encodeURIComponent(result.task_id)}`);poll(result.task_id)}catch(error){$("#status").textContent=`ERROR · ${error.message}`;$("#status").classList.add("error");$("#generate").disabled=false}});
async function start(){config=await fetch("/config.json",{cache:"no-store"}).then(r=>r.json());if(!token||tokenExpiresSoon()&&!await refreshSession()){const state=crypto.randomUUID();sessionStorage.setItem("oauth_state",state);$("#loginLink").href=`https://${config.cognito_domain}/oauth2/authorize?client_id=${encodeURIComponent(config.client_id)}&response_type=code&scope=${encodeURIComponent("openid email")}&redirect_uri=${encodeURIComponent(config.callback_url)}&state=${encodeURIComponent(state)}`;$("#registeredAccess").hidden=false;return}resources=await api("/account/resources");$("#registeredContent").hidden=false;layers=[newLayer(0),newLayer(1),newLayer(2)];populatePalettes();renderLayers();const task=new URLSearchParams(location.search).get("task");if(task)poll(task)}
start().catch(error=>{$("#registeredContent").hidden=false;$("#status").textContent=`ERROR · ${error.message}`;$("#status").classList.add("error")});
