import {createHardwarePreview} from "./spiralgraph/hardware-preview-v1.js";
import {createCanvasPreview} from "./spiralgraph/canvas-preview-v1.js";
import {createDrawingEditor} from "./spiralgraph/drawing-editor-v1.js";
import {COLORS,GEARS,constrainWorkbedToDiameter,createDrawingState,newLayer} from "./spiralgraph/state-v1.js";

let config,resources={},pollTimer,canvasPreview;
let token=localStorage.getItem("id_token")||sessionStorage.getItem("id_token");
let refreshToken=localStorage.getItem("refresh_token")||sessionStorage.getItem("refresh_token");
const $=value=>document.querySelector(value);
const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const drawingState=createDrawingState();
const getLayers=drawingState.getLayers,getActiveLayerIndex=drawingState.getActiveLayerIndex,setActiveLayerIndex=drawingState.setActiveLayerIndex;

function palettes(){return(resources.material_libraries||[]).filter(item=>item.library_intent==="processing_palette")}
function palette(){return palettes().find(item=>item.library_id===$("#processingPalette").value)}
function colorPalettes(){return(resources.material_libraries||[]).filter(item=>item.library_intent==="color_palette")}
function colorPalette(){return colorPalettes().find(item=>item.library_id===$("#colorPalette").value)}
function settingMode(entry){return["scan","fill"].includes(String(entry?.type||"").toLowerCase())?"fill":"line"}
function paletteSwatches(){const item=colorPalette();if(!item)return COLORS.map((hex,index)=>({hex:hex.toUpperCase(),name:`Built-in swatch ${index+1}`,mode:""}));const mapping=(resources.preferences?.material_library_color_assignments||{})[item.library_id],entries=item.summary?.entries||[],result=[],seen=new Set();for(const entry of entries){const match=Object.entries(mapping||{}).find(([,name])=>String(name).trim().toLowerCase()===String(entry.description||"").trim().toLowerCase()),hex=String(match?.[0]||(mapping?"":entry.hex||"")).toUpperCase();if(!/^#[0-9A-F]{6}$/.test(hex)||seen.has(hex))continue;seen.add(hex);result.push({hex,name:entry.description||hex,mode:settingMode(entry),type:entry.type||"Cut"})}return result}
function applySwatchMode(layer){if(!colorPalette())return;const swatch=paletteSwatches().find(item=>item.hex===String(layer.swatch_hex||"").toUpperCase());if(swatch)layer.output_mode=swatch.mode}
function materialNames(item){return[...new Set([...(item?.summary?.logical_material_names||[]),...(item?.summary?.entries||[]).map(entry=>entry.material)].map(v=>String(v||"").trim()).filter(Boolean))]}
function entries(){const material=$("#processingMaterial").value;return(palette()?.summary?.entries||[]).filter(entry=>String(entry.material||"")===material)}
function roleEntry(role){const item=palette(),material=$("#processingMaterial").value,assignments=(resources.preferences?.processing_palette_role_assignments||{})[item?.library_id]||{},roles=assignments.materials&&typeof assignments.materials==="object"?(assignments.materials[material]||{}):assignments,value=String(roles[role]||"").trim();return entries().find(entry=>String(entry.entry_ref||"")===value)||entries().find(entry=>String(entry.description||"").trim().toLowerCase()===role.toLowerCase())}
function populatePalettes(){const list=palettes();$("#processingPalette").innerHTML=list.map(item=>`<option value="${esc(item.library_id)}">${esc(item.name)}</option>`).join("");$("#colorPalette").innerHTML='<option value="">Built-in SpiralGraph colors</option>'+colorPalettes().map(item=>`<option value="${esc(item.library_id)}">${esc(item.name)}</option>`).join("");populateMaterials()}
function populateMaterials(){const names=materialNames(palette());$("#processingMaterial").innerHTML=names.map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join("");populateSettings()}
function populateSettings(){const line=entries().filter(entry=>String(entry.type||"").toLowerCase()==="cut"),fill=entries().filter(entry=>String(entry.type||"").toLowerCase()==="scan");$("#scoreSetting").innerHTML=line.map(entry=>`<option value="${esc(entry.entry_ref)}">${esc(entry.description)}</option>`).join("");$("#fillSetting").innerHTML=fill.map(entry=>`<option value="${esc(entry.entry_ref)}">${esc(entry.description)}</option>`).join("");const preferredLine=roleEntry("Score")||roleEntry("Cut"),preferredFill=roleEntry("Fill");if(preferredLine)$("#scoreSetting").value=preferredLine.entry_ref;if(preferredFill)$("#fillSetting").value=preferredFill.entry_ref;updatePaletteStatus()}
function updatePaletteStatus(){const layers=getLayers(),selectedPalette=colorPalette(),needsLine=layers.some(layer=>layer.output_mode==="line"||layer.include_track),needsFill=layers.some(layer=>layer.output_mode==="fill"),swatches=paletteSwatches(),selected=layers.map(layer=>String(layer.swatch_hex||"").toUpperCase()),swatchesValid=!selectedPalette||selected.every(hex=>swatches.some(item=>item.hex===hex)),fallbackValid=palette()&&(!needsLine||$("#scoreSetting").value)&&(!needsFill||$("#fillSetting").value),valid=selectedPalette?swatchesValid:fallbackValid;document.querySelectorAll(".processing-fallback").forEach(control=>control.hidden=Boolean(selectedPalette));$("#generate").disabled=!valid;$("#paletteStatus").textContent=selectedPalette?swatchesValid?"Each drawing uses its selected swatch for preview, SVG, LightBurn color, laser settings, and automatic Line or Fill mode.":"Choose an available swatch for every drawing.":!palette()?"Import or create a Processing Palette, or select a Color Palette.":needsFill&&!$("#fillSetting").value?"This material needs a LightBurn Fill setting for filled ribbons.":needsLine&&!$("#scoreSetting").value?"This material needs a LightBurn Line setting.":"Processing Palette role assignments initialize the fallback Line and Fill selections."}

function schedulePreview(){canvasPreview.schedulePreview()}
const hardwarePreview=createHardwarePreview({getActiveLayer:()=>getLayers()[getActiveLayerIndex()],getActiveLayerIndex,schedulePreview});
canvasPreview=createCanvasPreview({colors:COLORS,getLayers,getActiveLayerIndex,getDiameter:()=>$("#diameter").value,renderHardware:()=>hardwarePreview.render()});
const drawingEditor=createDrawingEditor({colors:COLORS,gears:GEARS,escapeHtml:esc,getLayers,getActiveLayerIndex,setActiveLayerIndex,newLayer,paletteSwatches,colorPalette,applySwatchMode,updatePaletteStatus,schedulePreview});
const {renderLayers}=drawingEditor;

function payloadLayer(source){const{_trackPoints,...layer}=source;return layer}
function payload(){const colorPaletteId=$("#colorPalette").value;return{project_name:$("#projectName").value,diameter_mm:$("#diameter").value,workbed_width_mm:$("#workbedWidth").value,workbed_height_mm:$("#workbedHeight").value,processing_palette_id:$("#processingPalette").value,color_palette_id:colorPaletteId,material:$("#processingMaterial").value,score_entry_ref:$("#scoreSetting").value,fill_entry_ref:$("#fillSetting").value,layers:getLayers().map(payloadLayer)}}
function tokenExpiresSoon(){try{const part=token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");const claims=JSON.parse(atob(part.padEnd(Math.ceil(part.length/4)*4,"=")));return Number(claims.exp||0)*1000<=Date.now()+30000}catch{return true}}
async function refreshSession(){if(!refreshToken)return false;const body=new URLSearchParams({grant_type:"refresh_token",client_id:config.client_id,refresh_token:refreshToken}),result=await fetch(`https://${config.cognito_domain}/oauth2/token`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body}).then(r=>r.json());if(!result.id_token)return false;token=result.id_token;localStorage.setItem("id_token",token);return true}
async function api(path,options={},retry=true){const response=await fetch(config.api_url+path,{...options,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...(options.headers||{})}});if(response.status===401&&retry&&await refreshSession())return api(path,options,false);const data=await response.json();if(!response.ok)throw new Error(data.message||`HTTP ${response.status}`);return data}
async function poll(taskId){clearTimeout(pollTimer);try{const job=await api(`/jobs/${taskId}`);$("#status").textContent=`${job.status.toUpperCase()} · ${taskId}`;if(job.status==="completed"){$("#generate").disabled=false;$("#outputs").innerHTML=(job.outputs||[]).map(output=>`<a class="spiralgrap-button" href="${esc(output.download_url)}">Download ${esc(String(output.name||"output").split("/").pop())}</a>`).join("");return}if(job.status==="failed")throw new Error(job.error||"SpiralGraph generation failed");pollTimer=setTimeout(()=>poll(taskId),3000)}catch(error){$("#status").textContent=`ERROR · ${error.message}`;$("#status").classList.add("error");$("#generate").disabled=false}}

function syncDimensions(){constrainWorkbedToDiameter($("#diameter"),[$("#workbedWidth"),$("#workbedHeight")]);schedulePreview()}
$("#processingPalette").addEventListener("change",populateMaterials);$("#processingMaterial").addEventListener("change",populateSettings);$("#scoreSetting").addEventListener("change",updatePaletteStatus);$("#fillSetting").addEventListener("change",updatePaletteStatus);$("#colorPalette").addEventListener("change",()=>{const swatches=paletteSwatches();getLayers().forEach((layer,index)=>{layer.swatch_hex=swatches[index%Math.max(1,swatches.length)]?.hex||COLORS[index%COLORS.length];applySwatchMode(layer)});renderLayers()});$("#diameter").addEventListener("input",syncDimensions);
$("#spiralgrapForm").addEventListener("submit",async event=>{event.preventDefault();$("#generate").disabled=true;$("#outputs").innerHTML="";$("#status").classList.remove("error");$("#status").textContent="Submitting SpiralGraph job…";try{const result=await api("/spiralgraph/jobs",{method:"POST",body:JSON.stringify(payload())});history.replaceState({},"",`${location.pathname}?task=${encodeURIComponent(result.task_id)}`);poll(result.task_id)}catch(error){$("#status").textContent=`ERROR · ${error.message}`;$("#status").classList.add("error");$("#generate").disabled=false}});
async function start(){config=await fetch("/config.json",{cache:"no-store"}).then(r=>r.json());if(!token||tokenExpiresSoon()&&!await refreshSession()){const state=crypto.randomUUID();sessionStorage.setItem("oauth_state",state);$("#loginLink").href=`https://${config.cognito_domain}/oauth2/authorize?client_id=${encodeURIComponent(config.client_id)}&response_type=code&scope=${encodeURIComponent("openid email")}&redirect_uri=${encodeURIComponent(config.callback_url)}&state=${encodeURIComponent(state)}`;$("#registeredAccess").hidden=false;return}resources=await api("/account/resources");$("#registeredContent").hidden=false;drawingState.resetLayers();populatePalettes();renderLayers();const task=new URLSearchParams(location.search).get("task");if(task)poll(task)}
start().catch(error=>{$("#registeredContent").hidden=false;$("#status").textContent=`ERROR · ${error.message}`;$("#status").classList.add("error")});
