let token=localStorage.getItem("id_token")||sessionStorage.getItem("id_token"),refreshToken=localStorage.getItem("refresh_token")||sessionStorage.getItem("refresh_token"),config,resources;
if(token)localStorage.setItem("id_token",token);if(refreshToken)localStorage.setItem("refresh_token",refreshToken);sessionStorage.removeItem("id_token");sessionStorage.removeItem("refresh_token");
const notice=document.querySelector("#notice"),materials=document.querySelector("#materials"),recipes=document.querySelector("#recipes"),depth=document.querySelector("#depth");
const registeredAccess=document.querySelector("#registeredAccess"),registeredContent=document.querySelector("#registeredContent");
const selectedSettings=new Map(),recipeProfiles=new Map(),materialMappingDrafts=new Map(),selectedCount=document.querySelector("#selectedCount"),clearSelected=document.querySelector("#clearSelected"),selectedActions=document.querySelector("#selectedActions"),selectedActionsPanel=document.querySelector("#selectedActionsPanel"),selectionAction=document.querySelector("#selectionAction");
const communityPublishPanel=document.querySelector("#communityPublishPanel"),communitySwatches=document.querySelector("#communitySwatches");let communityContext=null;
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
function showRegisteredAccess(authenticated){registeredAccess.hidden=authenticated;registeredContent.hidden=!authenticated;window.stagingShellSetAuthenticated?.(authenticated);if(!authenticated){token=null;refreshToken=null;localStorage.removeItem("id_token");localStorage.removeItem("refresh_token")}}
function tokenExpiresSoon(){try{const part=token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");const claims=JSON.parse(atob(part.padEnd(Math.ceil(part.length/4)*4,"=")));return Number(claims.exp||0)*1000<=Date.now()+30000}catch{return true}}
async function refreshSession(){if(!refreshToken)return false;const body=new URLSearchParams({grant_type:"refresh_token",client_id:config.client_id,refresh_token:refreshToken});const result=await fetch(`https://${config.cognito_domain}/oauth2/token`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body}).then(r=>r.json());if(!result.id_token)return false;token=result.id_token;localStorage.setItem("id_token",token);return true}
async function api(path,options={},retry=true){const response=await fetch(config.api_url+path,{...options,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...(options.headers||{})}});if(response.status===401&&retry&&await refreshSession())return api(path,options,false);const data=await response.json();if(!response.ok)throw new Error(data.message||`HTTP ${response.status}`);return data}
async function rawApi(path,options={},retry=true){const response=await fetch(config.api_url+path,{...options,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...(options.headers||{})}});if(response.status===401&&retry&&await refreshSession())return rawApi(path,options,false);return response}
function importSizeMessage(kind,limit){const size=`${(limit/(1024*1024)).toFixed(1).replace(/\.0$/,"")} MB`;return kind==="material"?`This LightBurn Material Library exceeds the ${size} upload limit. Save a copy in LightBurn, remove materials you don't plan to import from that copy, export it as a .clb file, and start a new import.`:`This Fauxlographic Palette exceeds the ${size} upload limit. Export a smaller palette with only the swatches and capture details you need, then start a new import.`}
async function upload(file,target){if(Number.isFinite(target.max_file_bytes)&&file.size>target.max_file_bytes)throw new Error(importSizeMessage(target.kind,target.max_file_bytes));const body=new FormData();Object.entries(target.fields).forEach(([key,value])=>body.append(key,value));body.append("file",file);let response;try{response=await fetch(target.url,{method:"POST",body})}catch{throw new Error("The upload was interrupted.")}if(!response.ok)throw new Error(response.status===403?"This upload session is no longer valid.":`We couldn't upload the file (HTTP ${response.status}). Check its size and format.`)}
function importErrorMessage(error){const message=String(error?.message||error),label=document.querySelector("#paletteAction").textContent.trim();if(message==='This import session is no longer available. Start the import again.')return `This import session is no longer available. Click "${label}" again to start a new upload.`;if(/upload capability|import capability|upload session is no longer valid/i.test(message))return `This upload session is no longer valid. Click "${label}" again to retry.`;if(message==="We couldn't verify the uploaded file.")return `${message} Click "${label}" again to upload it again.`;if(message==='The uploaded file is empty.')return `${message} Choose a non-empty file, then click "${label}" again.`;if(/^The uploaded file exceeds the [\d.]+ MB limit\.$/.test(message))return `${message} Choose a smaller file, then click "${label}" again.`;if(message==="The upload was interrupted.")return `The upload was interrupted. Check your connection, then click "${label}" again to retry.`;if(message.startsWith("We couldn't upload the file (HTTP "))return `${message} Click "${label}" again to retry.`;return message}
function depthDirectionLabel(value){const depth=Number(value);if(Math.abs(depth-50)<.05)return "Neutral";const amount=Math.round(Math.abs(depth-50)*2);return `${amount}% ${depth<50?"Farther":"Closer"}`}
function orderedDepthEntries(item){const order=new Map((resources.palette||[]).flatMap((swatch,index)=>[[String(swatch.name).toLowerCase(),index],[String(swatch.hex).toUpperCase(),index]]));return [...(item.entries||[])].sort((left,right)=>(order.get(String(left.name).toLowerCase())??order.get(String(left.hex).toUpperCase())??1000)-(order.get(String(right.name).toLowerCase())??order.get(String(right.hex).toUpperCase())??1000)||String(left.name).localeCompare(String(right.name)))}
function depthCard(item){const entries=orderedDepthEntries(item),panelId=`depth-settings-${item.palette_id}`;return `<div class="card depth-palette-card" data-depth="${item.palette_id}"><div class="library-title-row"><input class="depthName" value="${esc(item.name)}" aria-label="Depth Palette name"><button class="saveDepth" type="button">Save</button></div><span class="palette-kind">Depth palette</span><p class="muted">${entries.length} settings</p><div class="actions library-card-actions"><button class="toggleDepthEntries" type="button" aria-expanded="false" aria-controls="${panelId}">Settings</button><button class="deleteDepth danger" type="button">Delete</button></div><div id="${panelId}" class="depth-palette-entries" hidden>${entries.map(entry=>`<div class="depth-palette-entry" data-depth-hex="${esc(entry.hex)}" role="button" tabindex="0" aria-expanded="false"><div class="depth-entry-identity"><input class="entryEnabled" type="checkbox" ${entry.enabled!==false?"checked":""} aria-label="Enable ${esc(entry.name)}"><span class="entry-mini-swatch" style="background:${esc(entry.hex)}" aria-hidden="true"></span><strong>${esc(entry.name)}</strong><span class="entry-accordion-indicator" aria-hidden="true">+</span></div><div class="depth-entry-editor" hidden><label>Depth <output class="depthValue">${esc(depthDirectionLabel(entry.depth??50))}</output><input class="entryDepth" type="range" min="0" max="100" step="0.1" value="${Number(entry.depth??50)}"></label><label>Influence <output class="influenceValue">${Number(entry.influence??0)}%</output><input class="entryInfluence" type="range" min="0" max="100" step="1" value="${Number(entry.influence??0)}"></label><p class="entry-save-note">Draft retained. Use the Save button at the top of this palette to save all edited settings.</p></div></div>`).join("")}</div></div>`}
const editableSettingOrder=["speed","minPower","maxPower","maxPower2","frequency","QPulseWidth","interval","angle","numPasses","anglePerPass","crossHatch","bidir","scanOpt","floodFill","overscan"];
const colorPaletteSettingFields=[
  {label:"Min Power",keys:["minPower"]},
  {label:"Max Power",keys:["maxPower"]},
  {label:"Speed",keys:["speed"]},
  {label:"Frequency",keys:["frequency"]},
  {label:"QPulse Duration",keys:["QPulseWidth","qPulseDuration","qPulseWidth"]},
  {label:"Line Interval",keys:["interval"]},
  {label:"Scan Angle",keys:["angle"]},
  {label:"Angles per Pass",keys:["anglePerPass"]},
  {label:"Bidirectional",keys:["bidir"],options:[["0","Off"],["1","On"]]},
  {label:"Cross Hatch",keys:["crossHatch"],options:[["0","Off"],["1","On"]]},
  {label:"Fill Strategy",keys:["scanOpt"],exactOptions:true,options:[["","Fill all shapes"],["byGroup","Fill groups together"],["individual","Fill individual shapes"]]},
  {label:"Flood Fill",keys:["floodFill"],exactOptions:true,options:[["","Off"],["1","On"]]},
  {label:"Passes",keys:["numPasses"],min:"1",step:"1"},
];
function booleanSettingOptions(field,existingKey,value){if(!existingKey)return [["","Not specified"],...field.options];const normalized=value.trim().toLowerCase();if(normalized==="true")return [["false","Off"],[value,"On"]];if(normalized==="false")return [[value,"Off"],["true","On"]];if(/^[+-]?\d+$/.test(normalized)){return Number(normalized)===0?[[value,"Off"],["1","On"]]:[["0","Off"],[value,"On"]]}return [[value,`Imported (${value})`],...field.options]}
function selectSettingOptions(field,existingKey,value){if(!field.exactOptions)return booleanSettingOptions(field,existingKey,value);if(!existingKey||field.options.some(([option])=>option===value))return field.options;return [[value,`Imported (${value})`],...field.options]}
function colorPaletteSettingMarkup(settings){return colorPaletteSettingFields.map(field=>{const existingKey=field.keys.find(candidate=>Object.prototype.hasOwnProperty.call(settings,candidate)),key=existingKey||field.keys[0],storedValue=existingKey?String(settings[existingKey]??""):"",value=storedValue!==""?storedValue:String(field.defaultValue??"");if(field.options){const options=selectSettingOptions(field,existingKey,value);return `<label>${esc(field.label)}<select data-setting="${esc(key)}">${options.map(([option,label])=>`<option value="${esc(option)}" ${option===value?"selected":""}>${esc(label)}</option>`).join("")}</select></label>`}return `<label>${esc(field.label)}<input type="number" step="${field.step||'any'}"${field.min?` min="${field.min}"`:""} data-setting="${esc(key)}" value="${esc(value)}"></label>`}).join("")}
function importedSettingMarkup(settings){const hidden=new Set(["LinkPath"]),keys=[...editableSettingOrder.filter(key=>key in settings&&!hidden.has(key)),...Object.keys(settings).filter(key=>!editableSettingOrder.includes(key)&&!hidden.has(key)).sort()];return keys.map(key=>`<label>${esc(key)}<input data-setting="${esc(key)}" value="${esc(settings[key])}"></label>`).join("")}
function officialSwatch(hex){return (resources.palette||[]).find(item=>String(item.hex).toUpperCase()===String(hex||"").toUpperCase())||null}
function defaultSwatchHex(description){const name=String(description||"").trim().toLowerCase(),match=(resources.palette||[]).find(item=>String(item.name||"").trim().toLowerCase()===name);return match?String(match.hex).toUpperCase():""}
function materialMappingState(item){let state=materialMappingDrafts.get(item.library_id);if(state)return state;state=new Map();const mapping=(resources.preferences?.material_library_color_assignments||{})[item.library_id],hasMapping=Boolean(mapping),claimed=new Set();for(const entry of item.summary?.entries||[]){const match=Object.entries(mapping||{}).find(([color,name])=>!claimed.has(String(color).toUpperCase())&&String(name).trim().toLowerCase()===String(entry.description).trim().toLowerCase()),fallback=String(hasMapping?"":entry.hex||"").toUpperCase(),hex=String(match?.[0]||(!claimed.has(fallback)?fallback:"")).toUpperCase();if(hex)claimed.add(hex);state.set(String(entry.entry_id),hex)}materialMappingDrafts.set(item.library_id,state);return state}
function assignedEntryHex(item,entry){const state=materialMappingDrafts.get(item.library_id);if(state?.has(String(entry.entry_id)))return state.get(String(entry.entry_id));const mapping=(resources.preferences?.material_library_color_assignments||{})[item.library_id],match=Object.entries(mapping||{}).find(([,name])=>String(name).trim().toLowerCase()===String(entry.description).trim().toLowerCase());return String(match?.[0]||(mapping?'':entry.hex||'')).toUpperCase()}
function mappingLabel(hex){const swatch=officialSwatch(hex);return swatch?`${swatch.name} · ${swatch.hex}`:"Unassigned"}
function mappingOwner(item,targetHex){const hex=String(targetHex||"").toUpperCase();return hex?(item.summary?.entries||[]).find(candidate=>materialMappingState(item).get(String(candidate.entry_id))===hex)||null:null}
function mappingAssignment(item,targetHex){const assigned=Boolean(mappingOwner(item,targetHex));return {state:assigned?"assigned":"unassigned",label:assigned?"Assigned":"Not assigned"}}
function mappingStatusMarkup(status){return `<em class="mapping-choice-status" data-state="${status.state}">${esc(status.label)}</em>`}
function mappingPicker(item,entry){const hex=materialMappingState(item).get(String(entry.entry_id))||"",swatch=officialSwatch(hex),choices=(resources.palette||[]).map(option=>{const status=mappingAssignment(item,option.hex),owner=mappingOwner(item,option.hex),occupied=owner&&String(owner.entry_id)!==String(entry.entry_id);return `<button class="mapping-choice" type="button" data-map-hex="${esc(option.hex)}" aria-pressed="${String(option.hex).toUpperCase()===hex}" ${occupied?"disabled":""}><span class="mapping-choice-swatch" style="background:${esc(option.hex)}" aria-hidden="true"></span><span><strong>${esc(option.name)}</strong><small>${esc(option.hex)}</small>${mappingStatusMarkup(status)}</span></button>`}).join("");return `<div class="entry-mapping-editor"><span class="entry-mapping-title">Rasterizer swatch</span><button class="mapping-picker-toggle" type="button" aria-expanded="false"><span class="mapping-choice-swatch" style="background:${esc(swatch?.hex||'#30342f')}" aria-hidden="true"></span><span class="mapping-current-label">${esc(mappingLabel(hex))}</span></button><div class="mapping-options" hidden><div class="mapping-filter"><input class="mapping-filter-input" type="search" placeholder="Filter by color name or hex" aria-label="Filter Rasterizer swatches"></div><button class="mapping-choice mapping-unassigned" type="button" data-map-hex="" aria-pressed="${!hex}"><span class="mapping-choice-swatch unassigned" aria-hidden="true"></span><span><strong>Unassigned</strong><small>No Rasterizer swatch</small></span></button>${choices}<p class="mapping-no-results" hidden>No matching Rasterizer swatches.</p></div><button class="reset-entry-mapping" type="button">Reset to default</button></div>`}
function draftEntryDescription(card,entry){return card.querySelector(`[data-entry="${entry.entry_id}"] .editDescription`)?.value.trim()||entry.description}
function refreshMaterialMapping(card,item){const state=materialMappingState(item);for(const entry of item.summary?.entries||[]){const row=card.querySelector(`[data-entry="${entry.entry_id}"]`);if(!row)continue;const hex=state.get(String(entry.entry_id))||"",swatch=officialSwatch(hex),label=row.querySelector(".entry-mapping-label"),toggle=row.querySelector(".mapping-picker-toggle"),chip=toggle?.querySelector(".mapping-choice-swatch");if(label)label.textContent=`Rasterizer: ${mappingLabel(hex)}`;if(toggle){toggle.querySelector(".mapping-current-label").textContent=mappingLabel(hex);if(chip)chip.style.background=swatch?.hex||"#30342f"}for(const choice of row.querySelectorAll(".mapping-choice")){const targetHex=String(choice.dataset.mapHex||"").toUpperCase(),owner=mappingOwner(item,targetHex);choice.setAttribute("aria-pressed",String(targetHex===hex));choice.disabled=Boolean(targetHex&&owner&&String(owner.entry_id)!==String(entry.entry_id));const statusNode=choice.querySelector(".mapping-choice-status");if(statusNode){const status=mappingAssignment(item,targetHex);statusNode.textContent=status.label;statusNode.dataset.state=status.state}}}applyCardPreviews()}
function assignMaterialSwatch(card,item,entry,targetHex){const state=materialMappingState(item),entryId=String(entry.entry_id),hex=String(targetHex||"").toUpperCase();if(hex){const conflict=[...(item.summary?.entries||[])].find(candidate=>String(candidate.entry_id)!==entryId&&state.get(String(candidate.entry_id))===hex);if(conflict&&!confirm(`${mappingLabel(hex)} is currently assigned to "${draftEntryDescription(card,conflict)}". Move it to "${draftEntryDescription(card,entry)}"?`))return false;if(conflict)state.set(String(conflict.entry_id),"")}state.set(entryId,hex);refreshMaterialMapping(card,item);return true}
function overriddenOfficialHex(item,entry){const mapping=(resources.preferences?.material_library_color_assignments||{})[item.library_id],official=String(entry.hex||'').toUpperCase(),active=assignedEntryHex(item,entry).toUpperCase();return mapping&&official&&active!==official?official:''}
function nearestRasterizerSwatch(color){const match=/^#([0-9a-f]{6})$/i.exec(String(color||""));if(!match)return null;const rgb=[0,2,4].map(offset=>parseInt(match[1].slice(offset,offset+2),16));return (resources.palette||[]).reduce((best,swatch)=>{const candidate=/^#([0-9a-f]{6})$/i.exec(String(swatch.hex||""));if(!candidate)return best;const distance=[0,2,4].reduce((sum,offset,index)=>sum+(rgb[index]-parseInt(candidate[1].slice(offset,offset+2),16))**2,0);return !best||distance<best.distance?{...swatch,distance}:best},null)}
function palettePreview(items,holographic=false){const swatches=(items||[]).filter(item=>/^#[0-9a-f]{6}$/i.test(String(item.hex||"")));return `<div class="palette-preview" aria-label="Palette color preview">${swatches.map(item=>{const name=item.name?`${item.name} · ${item.hex}`:item.hex,angle=Number(item.angle_degrees||0)+90,spacing=Math.max(3,Math.min(12,Number(item.interval_mm||.05)*120));return `<span class="palette-preview-swatch${holographic?" holographic":""}" style="--preview-color:${esc(item.hex)};--preview-angle:${angle}deg;--preview-spacing:${spacing}px" title="${esc(name)}" aria-label="${esc(name)}"></span>`}).join("")||'<span class="palette-preview-empty">Preview unavailable</span>'}</div>`}
function setCardPreview(card,items,holographic=false){const signature=JSON.stringify([holographic,items]),html=palettePreview(items,holographic),preview=card.querySelector(":scope > .palette-preview");if(preview?.dataset.previewSignature===signature)return;if(preview)preview.outerHTML=html;else{const count=card.querySelector(":scope > p.muted");if(count){count.insertAdjacentHTML("beforebegin",html);count.remove()}}const rendered=card.querySelector(":scope > .palette-preview");if(rendered)rendered.dataset.previewSignature=signature}
function refreshRecipeCardPreview(card){const profile=recipeProfiles.get(card.dataset.recipe);if(!profile)return;setCardPreview(card,(profile.recipes||[]).map(item=>({name:item.name,hex:item.observed_hex,interval_mm:item.interval_mm,angle_degrees:item.angle_degrees})),true)}
function hatchValues(entry,editor=null){const angle=Number(editor?.querySelector('[data-setting="angle"]')?.value??entry.angle??entry.settings?.angle??0),interval=Number(editor?.querySelector('[data-setting="interval"]')?.value??entry.interval??entry.settings?.interval??.05);return {angle:Number.isFinite(angle)?angle:0,interval:Number.isFinite(interval)&&interval>0?interval:.05}}
function styleHatchSwatch(chip,color,angle,interval){chip.classList.add("hatch-pattern-swatch");chip.style.setProperty("--hatch-color",color||"#131713");chip.style.setProperty("--hatch-line-angle",`${angle+90}deg`);chip.style.setProperty("--hatch-line-spacing",`${Math.max(3,Math.min(14,interval*120))}px`)}
function applyMaterialHatchPatterns(){for(const card of materials.querySelectorAll("[data-material]")){const library=resources.material_libraries.find(item=>item.library_id===card.dataset.material);if(library?.library_intent!=="hatch_palette")continue;for(const row of card.querySelectorAll("[data-entry]")){const entry=library.summary?.entries?.find(item=>String(item.entry_id)===row.dataset.entry);if(!entry)continue;const values=hatchValues(entry,row.querySelector(".entry-editor"));styleHatchSwatch(row.querySelector(".entry-mini-swatch"),assignedEntryHex(library,entry),values.angle,values.interval)}}}
function orderedMaterialEntries(item){const order=new Map((resources.palette||[]).map((swatch,index)=>[String(swatch.hex).toUpperCase(),index]));return [...(item.summary?.entries||[])].sort((left,right)=>(order.get(assignedEntryHex(item,left).toUpperCase())??1000)-(order.get(assignedEntryHex(item,right).toUpperCase())??1000)||String(left.description).localeCompare(String(right.description)))}
function applyCardPreviews(){for(const card of materials.querySelectorAll("[data-material]")){const library=resources.material_libraries.find(item=>item.library_id===card.dataset.material),hatch=library?.library_intent==="hatch_palette";setCardPreview(card,orderedMaterialEntries(library).map(entry=>{const row=card.querySelector(`[data-entry="${entry.entry_id}"]`),values=hatchValues(entry,row?.querySelector(".entry-editor"));return {name:entry.description,hex:assignedEntryHex(library,entry),angle_degrees:values.angle,interval_mm:values.interval}}),hatch)}for(const card of depth.querySelectorAll("[data-depth]")){const palette=resources.depth_palettes.find(item=>item.palette_id===card.dataset.depth);setCardPreview(card,orderedDepthEntries(palette).map(entry=>({name:entry.name,hex:entry.hex})))}for(const card of recipes.querySelectorAll("[data-recipe]")){const recipe=resources.holographic_recipes.find(item=>item.recipe_id===card.dataset.recipe);setCardPreview(card,recipe?.metadata?.swatch_preview||[],true)}applyMaterialHatchPatterns()}
async function hydrateRecipePreviews(){await Promise.all((resources.holographic_recipes||[]).filter(item=>!item.metadata?.swatch_preview?.length).map(async item=>{try{const detail=await api(`/account/holographic-recipes/${item.recipe_id}`);recipeProfiles.set(item.recipe_id,detail.profile);const card=recipes.querySelector(`[data-recipe="${CSS.escape(item.recipe_id)}"]`);if(card)refreshRecipeCardPreview(card)}catch{}}))}
function downloadJson(profile,name){const blob=new Blob([`${JSON.stringify(profile,null,2)}\n`],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a"),base=String(name||profile?.profile_name||"holographic-palette").trim().replace(/[^A-Za-z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")||"holographic-palette";link.href=url;link.download=`${base.replace(/\.json$/i,"")}.json`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function recipeDraft(card,profile){const draft=structuredClone(profile),draftName=card.querySelector(".recipeProfileName")?.value.trim();if(draftName)draft.profile_name=draftName;draft.recipes=(draft.recipes||[]).map((item,index)=>{const editor=card.querySelector(`[data-recipe-index="${index}"] .recipe-entry-editor`);if(!editor)return item;const laserSettings=item.laser_settings?structuredClone(item.laser_settings):null;if(laserSettings?.settings)for(const input of editor.querySelectorAll("[data-recipe-setting]"))laserSettings.settings[input.dataset.recipeSetting]=input.value;return {...item,name:editor.querySelector(".editRecipeName")?.value||item.name,observed_hex:editor.querySelector(".editRecipeColor")?.value||item.observed_hex,interval_mm:Number(editor.querySelector(".editRecipeInterval")?.value??item.interval_mm),angle_degrees:Number(editor.querySelector(".editRecipeAngle")?.value??item.angle_degrees),...(laserSettings?{laser_settings:laserSettings}:{})}});return draft}
function materialCard(item){
  const entries=orderedMaterialEntries(item),panelId=`library-settings-${item.library_id}`,hatch=item.library_intent==="hatch_palette",paletteType=hatch?"Hatch palette":"Color palette",communityButton=hatch?"":`<button class="shareCommunity" type="button" data-community-kind="material" data-community-id="${item.library_id}">Community Set</button>`,resetButton=hatch?"":'<button class="resetMaterialMappings" type="button">Reset mappings</button>';
  const rows=entries.map(entry=>{const assignedHex=assignedEntryHex(item,entry),officialHex=overriddenOfficialHex(item,entry),assignment=hatch?"":`<small class="entry-mapping-label">Rasterizer: ${esc(mappingLabel(assignedHex))}</small>`;return `<div class="library-entry" data-entry="${entry.entry_id}" role="button" tabindex="0" aria-expanded="false"><div class="entry-head"><input class="entry-select" type="checkbox" ${selectedSettings.has(`${item.library_id}:${entry.entry_id}`)?"checked":""} aria-label="Select ${esc(entry.description)}"><span class="entry-mini-swatch" style="background:${esc(assignedHex||'#131713')}" aria-hidden="true"></span><span><strong>${esc(entry.description)}</strong><br><span class="muted">${esc(entry.type)}</span>${assignment}</span>${officialHex?`<span class="entry-official-swatch" style="background:${esc(officialHex)}" title="Official Rasterizer color overridden" aria-label="Official Rasterizer color overridden"></span>`:''}<span class="entry-accordion-indicator" aria-hidden="true">+</span></div></div>`}).join("");
  return `<div class="card" data-material="${item.library_id}"><div class="library-title-row"><input class="materialName" value="${esc(item.name)}" aria-label="Library name"><button class="saveMaterial" type="button">Save</button></div><span class="palette-kind">${paletteType}</span><p class="muted">${entries.length} settings</p><div class="actions library-card-actions"><button class="toggleLibraryEntries" type="button" aria-expanded="false" aria-controls="${panelId}">Settings</button>${resetButton}${communityButton}<button class="deleteMaterial danger">Delete</button></div><div id="${panelId}" class="library-entries" hidden>${rows}</div></div>`
}
function updateSelectedControls(){const count=selectedSettings.size;if(!count)document.querySelectorAll(".entry-select,.recipe-select").forEach(input=>input.checked=false);selectedCount.textContent=`${count} setting${count===1?"":"s"} selected`;clearSelected.disabled=!count;selectedActions.disabled=!count;document.querySelector("#selectedActionSummary").textContent=`${count} setting${count===1?"":"s"} from your saved libraries and palettes will be used.`}
function recipeCard(item){const count=Number(item.metadata?.recipe_count||0),selfContained=item.metadata?.self_contained===true||Number(item.metadata?.schema_version)>=2,panelId=`recipe-settings-${item.recipe_id}`;return `<div class="card holographic-recipe-card" data-recipe="${item.recipe_id}"><div class="library-title-row"><input class="recipeProfileName" value="${esc(item.name)}" aria-label="Fauxlographic Palette name"><button class="saveRecipe" type="button" ${selfContained?"":"disabled"}>Save</button></div><span class="palette-kind">Fauxlographic palette${selfContained?" · embedded settings":" · legacy"}</span><p class="muted">${count} measured swatches${item.metadata?.has_black_setting?" · Black setting included":""}</p><div class="actions library-card-actions"><button class="toggleRecipeEntries" type="button" aria-expanded="false" aria-controls="${panelId}">${selfContained?"Settings":"View"}</button><button class="downloadRecipeJson" type="button">Download JSON</button><button class="deleteRecipe danger" type="button">Delete</button></div><div id="${panelId}" class="recipe-entries" hidden><p class="muted">Loading fauxlographic swatches…</p></div></div>`}
function recipeRows(profile){return (profile.recipes||[]).map((item,index)=>{const settings=item.laser_settings?.settings||{},keys=[...editableSettingOrder.filter(key=>key in settings),...Object.keys(settings).filter(key=>!editableSettingOrder.includes(key)&&!['index','name','LinkPath'].includes(key)).sort()],selectionKey=`recipe:${profile.profile_id}:${index}`,official=nearestRasterizerSwatch(item.observed_hex);return `<div class="library-entry recipe-entry" data-recipe-index="${index}" role="button" tabindex="0" aria-expanded="false"><div class="entry-head"><input class="recipe-select" type="checkbox" ${selectedSettings.has(selectionKey)?"checked":""} aria-label="Select ${esc(item.name)}"><span class="entry-mini-swatch" style="background:${esc(item.observed_hex||'#131713')}" aria-hidden="true"></span><span><strong>${esc(item.name)}</strong><br><span class="muted">${esc(item.observed_hex)} · ${Number(item.interval_mm||0).toFixed(3)} mm · ${Number(item.angle_degrees||0).toFixed(1)}°</span></span>${official?`<span class="entry-official-swatch recipe-source-swatch" style="background:${esc(official.hex)}" title="Maps artwork color ${esc(official.name)} (${esc(official.hex)}) to this fauxlographic swatch" aria-label="Artwork mapping: ${esc(official.name)}, ${esc(official.hex)}"></span>`:""}<span class="entry-accordion-indicator" aria-hidden="true">+</span></div><div class="entry-editor recipe-entry-editor" hidden><label>Name<input class="editRecipeName" value="${esc(item.name)}"></label><label>Observed color<input class="editRecipeColor" type="color" value="${esc(item.observed_hex||'#000000')}"></label><label>Interval (mm)<input class="editRecipeInterval" type="number" min="0.001" max="10" step="0.001" value="${Number(item.interval_mm||0)}"></label><label>Angle (degrees)<input class="editRecipeAngle" type="number" min="0" max="179.999" step="0.1" value="${Number(item.angle_degrees||0)}"></label>${item.laser_settings?`<div class="entry-settings">${keys.map(key=>`<label>${esc(key)}<input data-recipe-setting="${esc(key)}" value="${esc(settings[key])}"></label>`).join("")}</div>`:`<p class="entry-save-note">Legacy Fauxlographic Palette: embedded laser settings are not available.</p>`}<p class="entry-save-note">Draft retained. Use the Save button at the top of this Fauxlographic Palette to save all edited swatches.</p></div></div>`}).join("")||"<p>No measured swatches were found.</p>"}
function applyRecipeSwatchPatterns(card){const profile=recipeProfiles.get(card.dataset.recipe);if(!profile)return;for(const row of card.querySelectorAll(".recipe-entry")){const item=profile.recipes?.[Number(row.dataset.recipeIndex)]||{},editor=row.querySelector(".recipe-entry-editor"),color=editor?.querySelector(".editRecipeColor")?.value||item.observed_hex||"#131713",interval=Number(editor?.querySelector(".editRecipeInterval")?.value??item.interval_mm??.05),angle=Number(editor?.querySelector(".editRecipeAngle")?.value??item.angle_degrees??0),chip=row.querySelector(".entry-mini-swatch"),official=nearestRasterizerSwatch(color),reference=row.querySelector(".recipe-source-swatch");chip.classList.add("recipe-hatch-swatch");chip.style.setProperty("--recipe-color",color);chip.style.setProperty("--recipe-line-angle",`${angle+90}deg`);chip.style.setProperty("--recipe-line-spacing",`${Math.max(3,Math.min(12,interval*120))}px`);if(reference&&official){reference.style.background=official.hex;reference.title=`Maps artwork color ${official.name} (${official.hex}) to this fauxlographic swatch`;reference.setAttribute("aria-label",`Artwork mapping: ${official.name}, ${official.hex}`)}}}
function addPaletteMaterialFields(){for(const card of materials.querySelectorAll("[data-material]")){const item=resources.material_libraries.find(candidate=>candidate.library_id===card.dataset.material),materialName=item?.material_name||item?.summary?.material_names?.[0]||"";card.querySelector(".palette-kind")?.insertAdjacentHTML("afterend",`<label class="palette-material-row"><span>Material</span><input class="paletteMaterialName" value="${esc(materialName)}" maxlength="160" required aria-label="Palette material name"></label>`)}}
function render(){materials.innerHTML=resources.material_libraries.map(materialCard).join("")||"<p>None saved.</p>";addPaletteMaterialFields();recipes.innerHTML=resources.holographic_recipes.map(recipeCard).join("")||"<p>None saved.</p>";depth.innerHTML=resources.depth_palettes.map(depthCard).join("")||"<p>None saved.</p>";applyCardPreviews();hydrateRecipePreviews();updateSelectedControls();notice.textContent="Saved assets are immediately available to your workflows."}
function updateCommunityCount(){const checked=communitySwatches.querySelectorAll("input:checked").length,total=communitySwatches.querySelectorAll("input").length;document.querySelector("#communitySwatchCount").textContent=`${checked} of ${total} swatches selected`;document.querySelector("#addToCommunity").disabled=!checked}
function communityMaterialRows(item){return orderedMaterialEntries(item).map(entry=>{const hex=assignedEntryHex(item,entry),official=(resources.palette||[]).find(color=>String(color.hex).toUpperCase()===String(hex).toUpperCase());return {index:Number(entry.entry_id),name:entry.description,detail:`${entry.material} · ${entry.type}`,hex:official?.hex||hex||"#131713",official:official?.name||"Unassigned"}})}
function communityRecipeRows(item,profile){return (profile.recipes||[]).map((swatch,index)=>{const official=nearestRasterizerSwatch(swatch.observed_hex);return {index,name:swatch.name||`Fauxlographic swatch ${index+1}`,detail:`${official?.name||"Nearest Rasterizer color"} · ${swatch.observed_hex||""}`,hex:official?.hex||swatch.observed_hex||"#131713",official:official?.name||"Nearest Rasterizer color"}})}
function renderCommunityRows(rows){communitySwatches.innerHTML=rows.map(row=>`<label class="community-swatch-option"><input type="checkbox" data-community-index="${row.index}" checked><span class="entry-mini-swatch" style="background:${esc(row.hex)}" aria-hidden="true"></span><span><strong>${esc(row.name)}</strong><small>${esc(row.detail)} · ${esc(row.official)}</small></span></label>`).join("");updateCommunityCount()}
async function openCommunityPublish(kind,id){let item,rows,profile={};if(kind==="material"){item=resources.material_libraries.find(candidate=>candidate.library_id===id);rows=item?communityMaterialRows(item):[]}else{item=resources.holographic_recipes.find(candidate=>candidate.recipe_id===id);if(item&&!recipeProfiles.has(id)){const detail=await api(`/account/holographic-recipes/${id}`);recipeProfiles.set(id,detail.profile)}profile=recipeProfiles.get(id)||{};rows=item?communityRecipeRows(item,profile):[]}if(!item||!rows.length)throw new Error("This palette has no publishable swatches");communityContext={kind,id,item};document.querySelector("#communityPublishSummary").textContent=`Choose the swatches from ${item.name} that you want to publish anonymously.`;document.querySelector("#communityLaser").value=item.laser_source||item.metadata?.laser_source||profile.grid?.laser_source||"";document.querySelector("#communityLens").value=item.lens_field_of_view||item.metadata?.lens_field_of_view||profile.grid?.lens_field_of_view_mm||"";document.querySelector("#communityNotes").value=item.notes||item.metadata?.notes||profile.notes||"";renderPublishableCommunityRows(rows);communityPublishPanel.hidden=false;document.querySelector("#communityLaser").focus()}
function closeCommunityPublish(){communityPublishPanel.hidden=true;communityContext=null}
function renderPublishableCommunityRows(rows){communitySwatches.innerHTML=rows.map(row=>{const publishable=row.official!=="Unassigned";return `<label class="community-swatch-option"><input type="checkbox" data-community-index="${row.index}" ${publishable?"checked":"disabled"}><span class="entry-mini-swatch" style="background:${esc(row.hex)}" aria-hidden="true"></span><span><strong>${esc(row.name)}</strong><small>${esc(row.detail)} - ${esc(publishable?row.official:"Assign an official Rasterizer swatch before publishing")}</small></span></label>`}).join("");updateCommunityCount()}
async function reload(){resources=await api("/account/resources");materialMappingDrafts.clear();render()}
function entriesFrom(card){return [...card.querySelectorAll(".depth-palette-entry")].map(row=>({hex:row.dataset.depthHex,depth:Number(row.querySelector(".entryDepth").value),influence:Number(row.querySelector(".entryInfluence").value),enabled:row.querySelector(".entryEnabled").checked}))}
materials.onclick=async event=>{
  const card=event.target.closest("[data-material]"),save=event.target.matches(".saveMaterial"),remove=event.target.matches(".deleteMaterial");
  if(!card||(!save&&!remove))return;
  try{
    if(save){
      notice.textContent="Saving palette, material, settings, and Rasterizer swatch assignments…";
      const library=resources.material_libraries.find(item=>item.library_id===card.dataset.material),mappingState=library?.library_intent==="hatch_palette"?null:materialMappingState(library);
      const paletteName=card.querySelector(".materialName").value.trim(),materialName=card.querySelector(".paletteMaterialName").value.trim(),savedMaterialName=String(library.material_name||library.summary?.material_names?.[0]||"").trim();
      if(paletteName!==String(library.name||"").trim()||materialName!==savedMaterialName)await api(`/account/material-libraries/${card.dataset.material}`,{method:"PATCH",body:JSON.stringify({name:paletteName,material_name:materialName})});
      for(const editor of card.querySelectorAll(".entry-editor")){
        const row=editor.closest(".library-entry"),entry=library.summary?.entries?.find(candidate=>String(candidate.entry_id)===row.dataset.entry),description=editor.querySelector(".editDescription").value.trim(),type=editor.querySelector(".editType").value,inputs=[...editor.querySelectorAll("[data-setting]")],settings=Object.fromEntries(inputs.filter(input=>input.value!=="").map(input=>[input.dataset.setting,input.value])),unsetSettings=inputs.filter(input=>input.value===""&&Object.prototype.hasOwnProperty.call(entry?.settings||{},input.dataset.setting)).map(input=>input.dataset.setting),settingsChanged=unsetSettings.length>0||Object.entries(settings).some(([name,value])=>String(value)!==String(entry?.settings?.[name]??""));
        if(entry&&(description!==String(entry.description||"")||type!==String(entry.type||"")||settingsChanged))await api(`/account/material-libraries/${card.dataset.material}/entries/${row.dataset.entry}`,{method:"PATCH",body:JSON.stringify({description,type,settings,unset_settings:unsetSettings})});
      }
      if(mappingState){const mapping={};for(const entry of library.summary?.entries||[]){const hex=mappingState.get(String(entry.entry_id))||"",description=draftEntryDescription(card,entry);if(hex&&description)mapping[hex]=description}const assignments={...(resources.preferences?.material_library_color_assignments||{}),[library.library_id]:mapping},result=await api("/account/preferences",{method:"PATCH",body:JSON.stringify({material_library_color_assignments:assignments})});resources.preferences=result.preferences||resources.preferences}
    }
    if(remove){
      if(!confirm("Permanently delete this saved Material Library?"))return;
      await api(`/account/material-libraries/${card.dataset.material}`,{method:"DELETE"});
    }
    await reload();
    if(save)notice.textContent="Palette name, material, settings, and Rasterizer swatch assignments saved.";
  }catch(error){notice.textContent=`Could not save palette: ${error.message}`}
};
materials.addEventListener("click",event=>{const card=event.target.closest("[data-material]"),library=resources.material_libraries.find(item=>item.library_id===card?.dataset.material);if(!card||!library||library.library_intent==="hatch_palette")return;if(event.target.matches(".resetMaterialMappings")){const state=materialMappingState(library);for(const entry of library.summary?.entries||[])state.set(String(entry.entry_id),defaultSwatchHex(draftEntryDescription(card,entry)));refreshMaterialMapping(card,library);notice.textContent="Default name-based mappings restored as a draft. Use Save to keep them.";return}const row=event.target.closest("[data-entry]"),entry=library.summary?.entries?.find(item=>String(item.entry_id)===row?.dataset.entry);if(!row||!entry)return;const toggle=event.target.closest(".mapping-picker-toggle");if(toggle){const options=toggle.nextElementSibling,opening=options.hidden;options.hidden=!opening;toggle.setAttribute("aria-expanded",String(opening));if(opening)options.querySelector(".mapping-filter-input")?.focus();return}const choice=event.target.closest(".mapping-choice");if(choice){if(assignMaterialSwatch(card,library,entry,choice.dataset.mapHex)){const options=choice.closest(".mapping-options"),picker=choice.closest(".entry-mapping-editor");options.hidden=true;picker.querySelector(".mapping-picker-toggle").setAttribute("aria-expanded","false");notice.textContent="Rasterizer swatch assignment updated as a draft. Use Save to keep it."}return}if(event.target.matches(".reset-entry-mapping")){const target=defaultSwatchHex(draftEntryDescription(card,entry));if(assignMaterialSwatch(card,library,entry,target))notice.textContent=target?"This setting was reset to its matching official swatch. Use Save to keep it.":"No official swatch matches this description, so the setting is now unassigned. Use Save to keep it."}});
materials.addEventListener("click",event=>{const card=event.target.closest("[data-material]");if(!card)return;if(event.target.matches(".toggleLibraryEntries")){const panel=card.querySelector(".library-entries"),opening=panel.hidden;panel.hidden=!opening;event.target.setAttribute("aria-expanded",String(opening));return}const row=event.target.closest(".library-entry");if(!row||event.target.closest(".entry-editor")||event.target.matches(".entry-select"))return;const library=resources.material_libraries.find(item=>item.library_id===card.dataset.material),entry=library?.summary?.entries?.find(item=>String(item.entry_id)===row.dataset.entry);if(!entry)return;let editor=row.querySelector(".entry-editor");const opening=!editor||editor.hidden;for(const other of card.querySelectorAll(".library-entry")){other.setAttribute("aria-expanded","false");const otherEditor=other.querySelector(".entry-editor");if(otherEditor)otherEditor.hidden=true}if(!opening)return;if(!editor){const settings=entry.settings||{},cutModes=[["Cut","Line"],["Scan","Fill"],["Image","Image"],["Offset","Offset Fill"]],controls=library.library_intent==="hatch_palette"?importedSettingMarkup(settings):colorPaletteSettingMarkup(settings);row.insertAdjacentHTML("beforeend",`<div class="entry-editor"><label>Description<input class="editDescription" value="${esc(entry.description)}"></label><label>Cut Mode<select class="editType">${cutModes.map(([value,label])=>`<option value="${value}" ${value===entry.type?"selected":""}>${label}</option>`).join("")}</select></label>${library.library_intent==="hatch_palette"?"":mappingPicker(library,entry)}<div class="entry-settings">${controls}</div><p class="entry-save-note">Draft retained. Use the Save button at the top of this palette to save all edited settings.</p></div>`);editor=row.querySelector(".entry-editor")}editor.hidden=false;row.setAttribute("aria-expanded","true")});
materials.addEventListener("keydown",event=>{const row=event.target.closest(".library-entry");if(row&&event.target===row&&(event.key==="Enter"||event.key===" ")){event.preventDefault();row.click()}});
materials.addEventListener("input",event=>{if(event.target.matches(".mapping-filter-input")){const options=event.target.closest(".mapping-options"),query=event.target.value.trim().toLowerCase();let shown=0;for(const choice of options.querySelectorAll(".mapping-choice")){const matches=!query||choice.textContent.toLowerCase().includes(query)||String(choice.dataset.mapHex||"").toLowerCase().includes(query);choice.hidden=!matches;if(matches)shown++}options.querySelector(".mapping-no-results").hidden=shown!==0;return}if(event.target.matches('[data-setting="angle"],[data-setting="interval"]'))applyCardPreviews()});
new MutationObserver(()=>applyMaterialHatchPatterns()).observe(materials,{childList:true,subtree:true});
materials.addEventListener("change",event=>{if(!event.target.matches(".entry-select"))return;const card=event.target.closest("[data-material]"),row=event.target.closest("[data-entry]"),key=`${card.dataset.material}:${row.dataset.entry}`,library=resources.material_libraries.find(item=>item.library_id===card.dataset.material),entry=library?.summary?.entries?.find(item=>String(item.entry_id)===row.dataset.entry);if(event.target.checked&&entry)selectedSettings.set(key,{library_id:card.dataset.material,entry_id:Number(row.dataset.entry),entry_description:entry.description,swatch_hex:assignedEntryHex(library,entry)});else selectedSettings.delete(key);updateSelectedControls()});
function updateSelectedActionFields(){const action=selectionAction.value,deleting=action==="delete",blankProject=action==="blank_project",destinationMaterial=action==="copy_existing",materialField=document.querySelector("#selectionMaterialNameField"),materialName=document.querySelector("#selectionMaterialName"),runButton=document.querySelector("#runSelectedAction");document.querySelector("#couponFields").hidden=action!=="coupon";document.querySelector("#existingLibraryField").hidden=!destinationMaterial;document.querySelector("#newLibraryField").hidden=action!=="copy_new";materialField.hidden=deleting||destinationMaterial;materialName.required=!deleting&&!destinationMaterial;document.querySelector("#selectionNameLabel").textContent=blankProject?"Project name":"Material name";document.querySelector("#targetLibrary").required=destinationMaterial;document.querySelector("#newLibraryName").required=action==="copy_new";runButton.textContent=action==="export"?"Download library":blankProject?"Download blank project":action==="coupon"?"Download coupon":deleting?"Delete selected settings":"Copy settings";runButton.classList.toggle("danger",deleting)}
function closeSelectedActions(){selectedActionsPanel.hidden=true}
clearSelected.onclick=()=>{selectedSettings.clear();document.querySelectorAll(".entry-select,.recipe-select").forEach(input=>input.checked=false);updateSelectedControls()};
selectedActions.onclick=()=>{document.querySelector("#targetLibrary").innerHTML=resources.material_libraries.map(item=>`<option value="${esc(item.library_id)}">${esc(item.name)}</option>`).join("");updateSelectedActionFields();selectedActionsPanel.hidden=false;selectionAction.focus()};
document.querySelector("#closeSelectedActions").onclick=closeSelectedActions;
selectedActionsPanel.addEventListener("click",event=>{if(event.target===selectedActionsPanel)closeSelectedActions()});
selectionAction.onchange=updateSelectedActionFields;
function fillCouponLabelEntries(){const libraryIds=new Set([...selectedSettings.values()].map(item=>item.library_id).filter(Boolean)),choices=[];for(const library of resources.material_libraries||[]){if(!libraryIds.has(library.library_id))continue;for(const entry of library.summary?.entries||[])choices.push({library_id:library.library_id,library_name:library.name,entry_id:Number(entry.entry_id),entry_description:entry.description})}const select=document.querySelector("#couponLabelEntry");select.replaceChildren(...choices.map((choice,index)=>new Option(`${choice.library_name} · ${choice.entry_description}`,String(index))));select.disabled=!choices.length;const automatic=choices.findIndex(choice=>String(choice.entry_description||"").trim().toLowerCase()==="labels"),selectedMatch=choices.findIndex(choice=>[...selectedSettings.values()].some(item=>item.library_id===choice.library_id&&Number(item.entry_id)===choice.entry_id));select.value=String(automatic>=0?automatic:selectedMatch>=0?selectedMatch:0);select._labelChoices=choices}
selectionAction.addEventListener("change",fillCouponLabelEntries);
selectedActions.addEventListener("click",fillCouponLabelEntries);
document.addEventListener("keydown",event=>{if(event.key!=="Escape")return;if(!communityPublishPanel.hidden)closeCommunityPublish();else if(!selectedActionsPanel.hidden)closeSelectedActions()});
document.querySelector("#selectedActionsForm").onsubmit=async event=>{
  event.preventDefault();
  const action=selectionAction.value,projectDownload=action==="coupon"||action==="blank_project",runButton=document.querySelector("#runSelectedAction"),payload={action,material_name:document.querySelector("#selectionMaterialName").value,selections:[...selectedSettings.values()]};
  if(action==="delete"&&!confirm(`Permanently delete ${selectedSettings.size} selected setting${selectedSettings.size===1?"":"s"} from their palettes? This cannot be undone.`))return;
  if(action==="coupon"){payload.coupon_width_mm=Number(document.querySelector("#couponWidth").value);payload.coupon_length_mm=Number(document.querySelector("#couponLength").value);const select=document.querySelector("#couponLabelEntry"),choice=select._labelChoices?.[Number(select.value)];if(choice)payload.label_selection={library_id:choice.library_id,entry_id:choice.entry_id,entry_description:choice.entry_description}}
  if(action==="copy_existing")payload.target_library_id=document.querySelector("#targetLibrary").value;
  if(action==="copy_new")payload.new_library_name=document.querySelector("#newLibraryName").value;
  notice.textContent=action==="delete"?"Deleting selected settings…":action==="blank_project"?"Preparing blank LightBurn project…":"Preparing selected settings…";runButton.disabled=true;
  try{
    const response=await rawApi("/account/material-libraries/selected-settings",{method:"POST",body:JSON.stringify(payload)});
    if(!response.ok){let message=`HTTP ${response.status}`;try{message=(await response.json()).message||message}catch{}throw new Error(message)}
    let result=null;
    if(projectDownload){const download=await response.json(),link=document.createElement("a");if(!download.download_url)throw new Error("Project download URL was not returned");link.href=download.download_url;link.download=download.filename||"selected-settings-project.lbrn2";document.body.append(link);link.click();link.remove()}
    else if(action==="export"){const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a"),base=(payload.material_name||"selected-settings").replace(/[^A-Za-z0-9._-]+/g,"-");link.href=url;link.download=`${base}-settings.clb`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
    else result=await response.json();
    selectedSettings.clear();
    if(action==="copy_existing"||action==="copy_new"||action==="delete")await reload();else{document.querySelectorAll(".entry-select,.recipe-select").forEach(input=>input.checked=false);updateSelectedControls()}
    closeSelectedActions();
    notice.textContent=action==="export"?"Selected settings downloaded.":action==="blank_project"?"Blank LightBurn project downloaded.":action==="coupon"?"Labeled LightBurn coupon downloaded.":action==="delete"?`${result?.deleted_settings||0} selected setting${result?.deleted_settings===1?"":"s"} deleted from ${result?.updated_palettes||0} palette${result?.updated_palettes===1?"":"s"}.`:"Selected settings copied successfully."
  }catch(error){notice.textContent=`Selected action failed: ${error.message}`}finally{runButton.disabled=false}
};
recipes.onclick=async event=>{
  const card=event.target.closest("[data-recipe]");if(!card)return;const recipeId=card.dataset.recipe;
  if(event.target.matches(".downloadRecipeJson")){
    const button=event.target;button.disabled=true;
    try{
      notice.textContent="Preparing Fauxlographic Palette JSON…";
      let profile=recipeProfiles.get(recipeId);
      if(!profile){const detail=await api(`/account/holographic-recipes/${recipeId}`);profile=detail.profile;recipeProfiles.set(recipeId,profile)}
      const draft=recipeDraft(card,profile);downloadJson(draft,draft.profile_name);
      notice.textContent="Fauxlographic Palette JSON downloaded with current edits.";
    }catch(error){notice.textContent=`Could not download Fauxlographic Palette JSON: ${error.message}`}finally{button.disabled=false}
    return
  }
  if(event.target.matches(".toggleRecipeEntries")){
    const panel=card.querySelector(".recipe-entries"),opening=panel.hidden;panel.hidden=!opening;event.target.setAttribute("aria-expanded",String(opening));
    if(opening&&!recipeProfiles.has(recipeId)){try{notice.textContent="Loading Fauxlographic Palette settings…";const detail=await api(`/account/holographic-recipes/${recipeId}`);recipeProfiles.set(recipeId,detail.profile);panel.innerHTML=recipeRows(detail.profile);notice.textContent="Fauxlographic Palette settings loaded."}catch(error){panel.innerHTML=`<p>Could not load Fauxlographic Palette: ${esc(error.message)}</p>`}}
    return
  }
  const row=event.target.closest(".recipe-entry");
  if(row&&!event.target.closest(".recipe-entry-editor")&&!event.target.matches(".recipe-select")){
    const editor=row.querySelector(".recipe-entry-editor"),opening=editor.hidden;for(const other of card.querySelectorAll(".recipe-entry")){other.setAttribute("aria-expanded","false");other.querySelector(".recipe-entry-editor").hidden=true}if(opening){editor.hidden=false;row.setAttribute("aria-expanded","true")}return
  }
  if(event.target.matches(".saveRecipe")){
    const profile=recipeProfiles.get(recipeId);if(!profile){notice.textContent="Open this Fauxlographic Palette before saving it.";return}
    const draft=recipeDraft(card,profile);
    try{notice.textContent="Saving Fauxlographic Palette and swatch settings…";await api(`/account/holographic-recipes/${recipeId}`,{method:"PUT",body:JSON.stringify({name:draft.profile_name,recipes:draft.recipes})});recipeProfiles.delete(recipeId);await reload();notice.textContent="Fauxlographic Palette and swatch settings saved."}catch(error){notice.textContent=`Could not save Fauxlographic Palette: ${error.message}`}
    return
  }
  if(event.target.matches(".deleteRecipe")&&confirm("Permanently delete this saved Fauxlographic Palette?")){try{await api(`/account/holographic-recipes/${recipeId}`,{method:"DELETE"});recipeProfiles.delete(recipeId);await reload()}catch(error){notice.textContent=error.message}}
};
document.addEventListener("click",async event=>{const button=event.target.closest(".shareCommunity");if(!button)return;try{notice.textContent="Preparing Community Set swatches...";await openCommunityPublish(button.dataset.communityKind,button.dataset.communityId);notice.textContent="Choose the swatches and machine details to publish."}catch(error){notice.textContent=`Could not prepare Community Set submission: ${error.message}`}});
document.querySelector("#closeCommunityPublish").onclick=closeCommunityPublish;
communityPublishPanel.addEventListener("click",event=>{if(event.target===communityPublishPanel)closeCommunityPublish()});
communitySwatches.addEventListener("change",updateCommunityCount);
document.querySelector("#communitySelectAll").onclick=()=>{communitySwatches.querySelectorAll("input:not(:disabled)").forEach(input=>input.checked=true);updateCommunityCount()};
document.querySelector("#communityClearAll").onclick=()=>{communitySwatches.querySelectorAll("input:not(:disabled)").forEach(input=>input.checked=false);updateCommunityCount()};
document.querySelector("#communityPublishForm").onsubmit=async event=>{event.preventDefault();if(!communityContext)return;const selectedIndexes=[...communitySwatches.querySelectorAll("input:checked")].map(input=>Number(input.dataset.communityIndex));if(!selectedIndexes.length){notice.textContent="Select at least one swatch for Community Set.";return}const submit=document.querySelector("#addToCommunity"),payload={source_kind:communityContext.kind,source_id:communityContext.id,selected_indexes:selectedIndexes,laser_source:document.querySelector("#communityLaser").value,lens:document.querySelector("#communityLens").value,notes:document.querySelector("#communityNotes").value};submit.disabled=true;notice.textContent="Adding selected swatches to Community Set...";try{const result=await api("/account/community-set",{method:"POST",body:JSON.stringify(payload)});closeCommunityPublish();await reload();notice.textContent=`${result.setting_count} swatch${result.setting_count===1?"":"es"} added anonymously to Community Set.`}catch(error){notice.textContent=`Community Set submission failed: ${error.message}`;submit.disabled=false}};
recipes.addEventListener("keydown",event=>{const row=event.target.closest(".recipe-entry");if(row&&event.target===row&&(event.key==="Enter"||event.key===" ")){event.preventDefault();row.click()}});
recipes.addEventListener("change",event=>{if(!event.target.matches(".recipe-select"))return;const card=event.target.closest("[data-recipe]"),row=event.target.closest("[data-recipe-index]"),key=`recipe:${card.dataset.recipe}:${row.dataset.recipeIndex}`,profile=recipeProfiles.get(card.dataset.recipe),recipe=profile?.recipes?.[Number(row.dataset.recipeIndex)],official=recipe?nearestRasterizerSwatch(recipe.observed_hex):null;if(event.target.checked&&recipe)selectedSettings.set(key,{recipe_id:card.dataset.recipe,recipe_index:Number(row.dataset.recipeIndex),recipe_name:recipe.name,recipe_hex:recipe.observed_hex,swatch_hex:official?.hex||""});else selectedSettings.delete(key);updateSelectedControls();updateSelectedActionFields()});
recipes.addEventListener("input",event=>{if(event.target.matches(".editRecipeColor,.editRecipeInterval,.editRecipeAngle"))applyRecipeSwatchPatterns(event.target.closest("[data-recipe]"))});
new MutationObserver(()=>recipes.querySelectorAll("[data-recipe]").forEach(card=>{applyRecipeSwatchPatterns(card);refreshRecipeCardPreview(card)})).observe(recipes,{childList:true,subtree:true});
depth.addEventListener("input",event=>{const row=event.target.closest(".depth-palette-entry");if(!row)return;if(event.target.matches(".entryDepth"))row.querySelector(".depthValue").textContent=depthDirectionLabel(event.target.value);if(event.target.matches(".entryInfluence"))row.querySelector(".influenceValue").textContent=`${Number(event.target.value)}%`});
depth.onclick=async event=>{const card=event.target.closest("[data-depth]");if(!card)return;if(event.target.matches(".toggleDepthEntries")){const panel=card.querySelector(".depth-palette-entries"),opening=panel.hidden;panel.hidden=!opening;event.target.setAttribute("aria-expanded",String(opening));return}const row=event.target.closest(".depth-palette-entry");if(row&&!event.target.closest(".depth-entry-editor")&&!event.target.matches(".entryEnabled")){const editor=row.querySelector(".depth-entry-editor"),opening=editor.hidden;for(const other of card.querySelectorAll(".depth-palette-entry")){other.setAttribute("aria-expanded","false");other.querySelector(".depth-entry-editor").hidden=true}if(opening){editor.hidden=false;row.setAttribute("aria-expanded","true")}return}const save=event.target.matches(".saveDepth"),remove=event.target.matches(".deleteDepth");if(!save&&!remove)return;try{if(save){notice.textContent="Saving Depth Palette…";await api(`/account/depth-palettes/${card.dataset.depth}`,{method:"PUT",body:JSON.stringify({name:card.querySelector(".depthName").value,entries:entriesFrom(card)})})}if(remove){if(!confirm("Permanently delete this Depth Palette?"))return;await api(`/account/depth-palettes/${card.dataset.depth}`,{method:"DELETE"})}await reload();if(save)notice.textContent="Depth Palette name and settings saved."}catch(error){notice.textContent=`Could not save Depth Palette: ${error.message}`}};
depth.addEventListener("keydown",event=>{const row=event.target.closest(".depth-palette-entry");if(row&&event.target===row&&(event.key==="Enter"||event.key===" ")){event.preventDefault();row.click()}});
document.querySelector("#newDepth").onclick=async()=>{const name=prompt("Name the new Depth Palette:","My Depth Palette");if(!name)return;try{await api("/account/depth-palettes",{method:"POST",body:JSON.stringify({name,entries:(resources.palette||[]).map(item=>({hex:item.hex,depth:50,influence:0,enabled:true}))})});await reload()}catch(error){notice.textContent=error.message}};
async function populateMaterialChoices(){const type=document.querySelector("#materialImportIntent").value,file=document.querySelector("#materialFile").files[0],field=document.querySelector("#materialSelectionField"),select=document.querySelector("#materialImportMaterial");field.hidden=true;select.required=false;select.innerHTML='<option value="">Choose a material</option>';if(!file||!["color_palette","hatch_palette"].includes(type))return;try{const documentXml=new DOMParser().parseFromString(await file.text(),"application/xml");if(documentXml.querySelector("parsererror")||documentXml.documentElement?.localName!=="LightBurnLibrary")throw new Error("The selected file is not a LightBurn Material Library.");const names=[...documentXml.documentElement.children].filter(node=>node.localName==="Material"&&[...node.children].some(child=>child.localName==="Entry")).map(node=>String(node.getAttribute("name")||"").trim()).filter(Boolean);for(const name of [...new Set(names)])select.add(new Option(name,name));if(!names.length)throw new Error("The selected library has no named materials containing settings.");field.hidden=false;select.required=true;if(select.options.length===2)select.selectedIndex=1;notice.textContent="Choose one of "+(select.options.length-1)+" material"+(select.options.length===2?"":"s")+" from the file."}catch(error){notice.textContent="Could not read palette materials: "+error.message}}
async function populateHatchImportBaseSettings(){const type=document.querySelector("#materialImportIntent").value,file=document.querySelector("#materialFile").files[0],materialName=document.querySelector("#materialImportMaterial").value,field=document.querySelector("#hatchImportBaseField"),select=document.querySelector("#hatchImportBaseSetting");field.hidden=type!=="hatch_palette";select.required=type==="hatch_palette";select.innerHTML='<option value="">Choose a setting</option>';if(type!=="hatch_palette"||!file||!materialName)return;try{const documentXml=new DOMParser().parseFromString(await file.text(),"application/xml"),material=[...documentXml.documentElement.children].find(node=>node.localName==="Material"&&String(node.getAttribute("name")||"").trim()===materialName),entries=[...(material?.children||[])].filter(node=>node.localName==="Entry");entries.forEach((entry,entryId)=>{const cut=[...entry.children].find(child=>child.localName==="CutSetting"),description=String(entry.getAttribute("Desc")||"(missing Description)").trim(),typeName=String(cut?.getAttribute("type")||"Setting"),label=typeName==="Scan"?"Fill":typeName==="Offset"?"Offset Fill":typeName;select.add(new Option(description+" · "+label,String(entryId)))});if(select.options.length===1)throw new Error("The selected material contains no setting entries.");if(select.options.length===2)select.selectedIndex=1}catch(error){notice.textContent="Could not read base settings: "+error.message}}
document.querySelector("#materialFile").onchange=async event=>{if(event.target.files[0]&&!document.querySelector("#materialImportName").value)document.querySelector("#materialImportName").value=event.target.files[0].name.replace(/\.[^.]+$/,"");await populateMaterialChoices();await populateHatchImportBaseSettings()};
document.querySelector("#materialImport").onsubmit=async event=>{event.preventDefault();const file=document.querySelector("#materialFile").files[0];notice.textContent="Uploading Material Library for validation…";try{const grant=await api("/account/imports",{method:"POST",body:JSON.stringify({kind:"material",filename:file.name,name:document.querySelector("#materialImportName").value,library_intent:document.querySelector("#materialImportIntent").value})});await upload(file,grant.upload);const result=await api(`/account/imports/${grant.import_id}/finalize`,{method:"POST",body:JSON.stringify({upload_token:grant.upload_token})});event.target.reset();await reload();showImportAdjustments(result)}catch(error){notice.textContent=`Import failed: ${error.message}`}};
document.querySelector("#recipeImport").onsubmit=async event=>{event.preventDefault();const file=document.querySelector("#recipeFile").files[0];notice.textContent="Uploading Fauxlographic Palette for validation…";try{const grant=await api("/account/imports",{method:"POST",body:JSON.stringify({kind:"recipe",filename:file.name,name:document.querySelector("#recipeImportName").value})});await upload(file,grant.upload);const result=await api(`/account/imports/${grant.import_id}/finalize`,{method:"POST",body:JSON.stringify({upload_token:grant.upload_token})});event.target.reset();await reload();notice.textContent=result.ignored_preserved_black?"Fauxlographic Palette imported. Preserved Black was left unchecked because its settings could not be read.":"Fauxlographic Palette imported."}catch(error){notice.textContent=`Import failed: ${error.message}`}};
function showImportAdjustments(result,success="Material Library imported."){const changes=result?.import_adjustments||[];notice.textContent=changes.length?`${success} ${changes.length} duplicate or missing setting description${changes.length===1?" was":"s were"} renamed automatically. Review and reassign those settings below.`:success}
async function importPalette(kind){const form=document.querySelector("#materialImport"),file=document.querySelector("#materialFile").files[0],name=document.querySelector("#materialImportName").value.trim(),materialName=document.querySelector("#materialImportMaterial").value,baseSetting=document.querySelector("#hatchImportBaseSetting").value;if(!file){notice.textContent="Choose a palette file first.";return}if(!name){notice.textContent="Provide a display name first.";return}if(kind==="material"&&!materialName){notice.textContent="Choose a material name from the palette file.";return}if(kind==="material"&&document.querySelector("#materialImportIntent").value==="hatch_palette"&&baseSetting===""){notice.textContent="Choose one setting from that material.";return}notice.textContent=kind==="recipe"?"Uploading Fauxlographic Palette for validation…":"Uploading Material Library for validation…";try{const payload={kind,filename:file.name,name};if(kind==="material"){payload.library_intent=document.querySelector("#materialImportIntent").value;payload.material_name=materialName;if(payload.library_intent==="hatch_palette"){payload.base_setting_id=Number(baseSetting);payload.hatch_operation=document.querySelector("#hatchImportOperation").value;payload.start_angle=document.querySelector("#hatchStartAngle").value;payload.angular_span=document.querySelector("#hatchAngularSpan").value;payload.first_interval=document.querySelector("#hatchFirstInterval").value;payload.last_interval=document.querySelector("#hatchLastInterval").value}}const grant=await api("/account/imports",{method:"POST",body:JSON.stringify(payload)});await upload(file,grant.upload);const result=await api(`/account/imports/${grant.import_id}/finalize`,{method:"POST",body:JSON.stringify({upload_token:grant.upload_token})});form.reset();updatePaletteAction();await reload();if(kind==="recipe")notice.textContent=result.ignored_preserved_black?"Fauxlographic Palette imported. Preserved Black was left unchecked because its settings could not be read.":"Fauxlographic Palette imported.";else showImportAdjustments(result,`Material ${materialName} imported.`)}catch(error){notice.textContent=`Import failed: ${importErrorMessage(error)}`}}
function updatePaletteAction(){const type=document.querySelector("#materialImportIntent").value,file=document.querySelector("#materialFile"),button=document.querySelector("#paletteAction"),help=document.querySelector("#paletteFileHelp"),depthType=type==="depth_palette",materialField=document.querySelector("#materialSelectionField"),materialSelect=document.querySelector("#materialImportMaterial"),planner=document.querySelector("#hatchPlannerFields"),baseField=document.querySelector("#hatchImportBaseField"),baseSelect=document.querySelector("#hatchImportBaseSetting");file.disabled=depthType;file.required=!depthType;materialField.hidden=true;materialSelect.required=false;baseField.hidden=true;baseSelect.required=false;planner.hidden=type!=="hatch_palette";if(type==="holographic_palette"){file.accept=".json,application/json";button.textContent="Import Fauxlographic Palette";help.textContent="Choose a Fauxlographic Palette JSON file."}else if(depthType){file.accept="";button.textContent="Create Depth Palette";help.textContent="Depth palettes start with the official Rasterizer colors; no file is needed."}else{file.accept=".clb,.lbmat,.lbrn";button.textContent=type==="hatch_palette"?"Import Planned Hatch Palette":"Import Color Palette";help.textContent=type==="hatch_palette"?"Choose a library, material, and one base setting.":"Choose a LightBurn Material Library.";populateMaterialChoices().then(populateHatchImportBaseSettings)}}
document.querySelector("#materialImport").onsubmit=async event=>{event.preventDefault();const type=document.querySelector("#materialImportIntent").value;if(type==="depth_palette"){const name=document.querySelector("#materialImportName").value.trim();if(!name){notice.textContent="Provide a display name first.";return}try{notice.textContent="Creating Depth Palette…";await api("/account/depth-palettes",{method:"POST",body:JSON.stringify({name,entries:(resources.palette||[]).map(item=>({hex:item.hex,depth:50,influence:0,enabled:true}))})});event.target.reset();updatePaletteAction();await reload();notice.textContent="Depth Palette created."}catch(error){notice.textContent=`Could not create Depth Palette: ${error.message}`}return}await importPalette(type==="holographic_palette"?"recipe":"material")};
document.querySelector("#materialImportIntent").onchange=updatePaletteAction;
document.querySelector("#materialImportMaterial").onchange=populateHatchImportBaseSettings;
document.querySelector("#importHolographic").onclick=()=>importPalette("recipe");
updatePaletteAction();
async function start(){config=await fetch("/config.json",{cache:"no-store"}).then(r=>r.json());if(!token){showRegisteredAccess(false);return}if(tokenExpiresSoon()){try{if(!await refreshSession()){showRegisteredAccess(false);return}}catch{showRegisteredAccess(false);return}}try{await reload();showRegisteredAccess(true)}catch(error){if(/401|unauthor|token|session/i.test(error.message)){showRegisteredAccess(false);return}showRegisteredAccess(true);notice.textContent=`Could not load Swatch Palette Vault: ${error.message}`}}
start().catch(error=>{if(!token){showRegisteredAccess(false);return}showRegisteredAccess(true);notice.textContent=`Could not load Swatch Palette Vault: ${error.message}`});
