import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class DepthMapGeneratorCoverageTests(unittest.TestCase):
    def test_unlisted_depthmap_page_uses_client_side_inference(self):
        home = (ROOT / "routes" / "home.py").read_text(encoding="utf-8")
        docs = (ROOT / "routes" / "docs.py").read_text(encoding="utf-8")
        chrome = (ROOT / "templates" / "_machine_chrome.html").read_text(encoding="utf-8")
        page = (ROOT / "templates" / "depthmap_generator.html").read_text(encoding="utf-8")
        script = (ROOT / "static" / "depthmap_generator.js").read_text(encoding="utf-8")

        self.assertIn('@routes.route("/depthmap-generator")', home)
        self.assertIn('"depthmap_generator.html"', home)
        self.assertIn("depth_palette=depth_palette", home)
        self.assertNotIn('"/depthmap-generator"', docs)
        self.assertNotIn('href="/depthmap-generator"', chrome)
        self.assertIn('content="noindex,nofollow"', page)
        self.assertIn('src="/static/depthmap_generator.js?v=1"', page)
        self.assertIn('pipeline("depth-estimation"', script)
        self.assertIn('options.device = "webgpu"', script)
        self.assertIn('CompressionStream("deflate")', script)
        self.assertIn('Download 16-bit PNG', page)
        self.assertIn('id="depth_output_width"', page)
        self.assertIn('id="depth_output_height"', page)
        self.assertIn("#depth_input::file-selector-button", page)
        self.assertIn("#depth_input::-webkit-file-upload-button", page)
        self.assertIn('id="depth_brush_size"', page)
        self.assertIn('id="color_guidance_panel"', page)
        self.assertIn('id="depth_palette_data"', page)
        self.assertIn('id="saved_depth_palette"', page)
        self.assertNotIn('id="depth_reset_guidance"', page)
        self.assertIn("configured only in", page)
        self.assertIn("Color-Guided Depth", page)
        self.assertIn("Smaller", page)
        self.assertIn("Bigger", page)
        self.assertIn('id="depth_brush_depth"', page)
        self.assertIn('id="depth_brush_depth" type="range" min="0" max="100" step="0.1"', page)
        self.assertIn('id="depth_brush_preview"', page)
        self.assertNotIn('id="depth_brush_gray_value"', page)
        self.assertNotIn("Paint value", page)
        self.assertIn("Farther", page)
        self.assertIn("Closer", page)
        self.assertIn('id="depth_clear_paint"', page)
        self.assertIn("outputDepth.fill(farthest)", script)
        self.assertIn('mapCanvas.addEventListener("pointerdown"', script)
        self.assertIn("paintedDepth[index] = proximity", script)
        self.assertIn("invertControl.checked ? 1 - proximity : proximity", script)
        self.assertIn("function updateBrushDepthPreview()", script)
        self.assertIn("function updateBrushSizePreview()", script)
        self.assertIn("brushDepthPreview.style.backgroundColor", script)
        self.assertIn("brushDepthPreview.style.width", script)
        self.assertIn("brushDepthPreview.style.height", script)
        self.assertIn("function createColorMatchMap()", script)
        self.assertIn("function applyColorGuidance()", script)
        self.assertIn("function boxBlur(", script)
        self.assertIn("outputDepth[index] * (.8 + shade * .2)", script)
        self.assertIn("invertControl.checked ? 1 - value : value", script)
        self.assertIn("async function loadSavedDepthPalettes()", script)
        self.assertIn("function selectDepthPalette()", script)
        self.assertIn('fetch("/account/depth-palettes"', script)
        self.assertNotIn('querySelector(".swatch-depth")', script)
        self.assertNotIn('querySelector(".swatch-influence")', script)
        self.assertIn('card.className = "color-card"', script)
        self.assertIn('square.className = "color-square"', script)
        self.assertIn('square.addEventListener("click"', script)
        self.assertIn("if (!savedDepthPaletteSelect.value) return", script)
        self.assertIn('square.setAttribute("aria-disabled", String(!paletteSelected))', script)
        self.assertIn('paletteSelected && !swatch.enabled', script)
        self.assertIn("awaiting-depth-palette", page)
        self.assertIn('classList.toggle("awaiting-depth-palette", !palette)', script)
        self.assertIn("guidedDepth[index] = adjustedDepth[index] * (1 - weight) + target * weight", script)
        self.assertIn("const farthest = invertControl.checked ? 1 : 0", script)
        self.assertIn("Math.min(outputWidth / depthWidth, outputHeight / depthHeight)", script)
        self.assertEqual(script.count("createImageData(outputWidth, outputHeight)"), 2)
        self.assertNotIn("createImageData(depthWidth, depthHeight)", script)


if __name__ == "__main__":
    unittest.main()
