import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class DepthMapGeneratorCoverageTests(unittest.TestCase):
    def test_unlisted_depthmap_page_uses_client_side_inference(self):
        home = (ROOT / "routes" / "home.py").read_text(encoding="utf-8")
        docs = (ROOT / "routes" / "docs.py").read_text(encoding="utf-8")
        chrome = (ROOT / "templates" / "_machine_chrome.html").read_text(encoding="utf-8")
        page = (ROOT / "templates" / "depthmap_generator.html").read_text(encoding="utf-8")
        script = (ROOT / "static" / "depthmap_generator.js").read_text(encoding="utf-8")

        self.assertIn('@routes.route("/depthmap-generator")', home)
        self.assertIn('"depthmap_generator.html"', home)
        self.assertIn("depth_palette=depth_palette", home)
        self.assertNotIn('"/depthmap-generator"', docs)
        self.assertNotIn('href="/depthmap-generator"', chrome)
        self.assertIn('content="noindex,nofollow"', page)
        self.assertIn('src="/static/depthmap_generator.js?v=1"', page)
        self.assertIn('pipeline("depth-estimation"', script)
        self.assertIn('options.device = "webgpu"', script)
        self.assertIn('CompressionStream("deflate")', script)
        self.assertIn('Download 16-bit PNG', page)
        self.assertIn('id="depth_output_width"', page)
        self.assertIn('id="depth_output_height"', page)
        self.assertEqual(page.count('id="depth_source_canvas"'), 1)
        self.assertLess(page.index('id="depth_input"'), page.index('id="depth_source_preview"'))
        self.assertLess(page.index('id="depth_source_preview"'), page.index('id="depth_workspace"'))
        self.assertEqual(page.count('id="depth_generate"'), 1)
        self.assertIn('>Initialize Depthmap</button>', page)
        self.assertLess(page.index('id="depth_source_preview"'), page.index('id="depth_processing_panel"'))
        self.assertLess(page.index('id="depth_processing_panel"'), page.index('id="depth_generate"'))
        self.assertLess(page.index('id="depth_generate"'), page.index('id="depth_progress"'))
        self.assertLess(page.index('id="depth_progress"'), page.index('id="depth_processing_status"'))
        self.assertLess(page.index('id="depth_processing_status"'), page.index('id="depth_processing_error"'))
        self.assertLess(page.index('id="depth_processing_error"'), page.index('id="depth_base_preview"'))
        self.assertEqual(page.count('id="depth_base_preview_canvas"'), 1)
        self.assertLess(page.index('id="depth_processing_error"'), page.index('id="color_guidance_panel"'))
        self.assertIn("#depth_input::file-selector-button", page)
        self.assertIn("#depth_input::-webkit-file-upload-button", page)
        self.assertIn('id="depth_brush_size"', page)
        self.assertIn('id="color_guidance_panel"', page)
        self.assertIn('id="depth_palette_data"', page)
        self.assertIn('id="saved_depth_palette"', page)
        self.assertNotIn('id="depth_reset_guidance"', page)
        self.assertIn("configured only in", page)
        self.assertIn("Color-Guided Depth", page)
        self.assertIn("Smaller", page)
        self.assertIn("Bigger", page)
        self.assertIn('id="depth_brush_depth"', page)
        self.assertIn('id="depth_brush_depth" type="range" min="0" max="100" step="0.1"', page)
        self.assertIn('id="depth_brush_preview"', page)
        self.assertNotIn('id="depth_brush_gray_value"', page)
        self.assertNotIn("Paint value", page)
        self.assertIn("Farther", page)
        self.assertIn("Closer", page)
        self.assertIn('id="depth_clear_paint"', page)
        self.assertIn("outputDepth.fill(farthest)", script)
        self.assertIn('mapCanvas.addEventListener("pointerdown"', script)
        self.assertIn("paintedDepth[index] = proximity", script)
        self.assertIn("invertControl.checked ? 1 - proximity : proximity", script)
        self.assertIn("function updateBrushDepthPreview()", script)
        self.assertIn("function drawBasePreview()", script)
        self.assertIn("const maximumSide = 1024", script)
        self.assertIn("context.drawImage(mapCanvas", script)
        self.assertIn("basePreview.hidden = true", script)
        self.assertIn("sourcePreview.hidden = false", script)
        self.assertIn("sourcePreview.hidden = true", script)
        self.assertIn("processingPanel.hidden = false", script)
        self.assertIn("processingPanel.hidden = true", script)
        self.assertIn("function setUploadStatus(message, isError = false)", script)
        self.assertIn("function setProcessingStatus(message, isError = false)", script)
        self.assertIn("acceptFile(input.files[0]).catch(cause => setUploadStatus", script)
        self.assertIn("Depth generation failed: ${cause.message || cause}", script)
        self.assertIn("function updateBrushSizePreview()", script)
        self.assertIn("brushDepthPreview.style.backgroundColor", script)
        self.assertIn("brushDepthPreview.style.width", script)
        self.assertIn("brushDepthPreview.style.height", script)
        self.assertIn("function createColorMatchMap()", script)
        self.assertIn("function applyColorGuidance()", script)
        self.assertIn("function boxBlur(", script)
        self.assertIn(".18 + shade * .65 + outputDepth[index] * .17", script)
        self.assertIn("invertControl.checked ? 1 - value : value", script)
        self.assertIn("async function loadSavedDepthPalettes()", script)
        self.assertIn("function selectDepthPalette()", script)
        self.assertIn('fetch("/account/depth-palettes"', script)
        self.assertNotIn('querySelector(".swatch-depth")', script)
        self.assertNotIn('querySelector(".swatch-influence")', script)
        self.assertIn('card.className = "color-card"', script)
        self.assertIn('square.className = "color-square"', script)
        self.assertIn('square.addEventListener("click"', script)
        self.assertIn("if (!savedDepthPaletteSelect.value) return", script)
        self.assertIn('square.setAttribute("aria-disabled", String(!paletteSelected))', script)
        self.assertIn('paletteSelected && !swatch.enabled', script)
        self.assertIn("awaiting-depth-palette", page)
        self.assertIn(".awaiting-depth-palette .color-card{width:32px}", page)
        self.assertIn(".awaiting-depth-palette .color-name,.awaiting-depth-palette .color-hex{display:none}", page)
        self.assertIn(".awaiting-depth-palette .color-square{width:32px;height:32px", page)
        self.assertIn('classList.toggle("awaiting-depth-palette", !palette)', script)
        self.assertIn("guidedDepth[index] = adjustedDepth[index] * (1 - weight) + target * weight", script)
        self.assertIn("const farthest = invertControl.checked ? 1 : 0", script)
        self.assertIn("Math.min(outputWidth / depthWidth, outputHeight / depthHeight)", script)
        self.assertIn("function syncOutputAspect(changedDimension)", script)
        self.assertIn('outputWidthControl.addEventListener("input", () => syncOutputAspect("width"))', script)
        self.assertIn('outputHeightControl.addEventListener("input", () => syncOutputAspect("height"))', script)
        self.assertIn("Editing either dimension automatically recalculates the other", page)
        self.assertEqual(script.count("createImageData(outputWidth, outputHeight)"), 2)
        self.assertNotIn("createImageData(depthWidth, depthHeight)", script)

    def test_material_vault_places_depth_palette_creation_with_hatch_palette(self):
        vault = (ROOT / "templates" / "material_libraries.html").read_text(encoding="utf-8")
        hatch_position = vault.index('id="new_hatch_palette"')
        depth_position = vault.index('id="new_depth_palette"')
        self.assertLess(hatch_position, depth_position)
        self.assertLess(depth_position - hatch_position, 180)
        self.assertEqual(vault.count('id="new_depth_palette"'), 1)
        self.assertIn("PALETTE &amp; MATERIAL SETTINGS CONSOLE", vault)
        self.assertIn("DEPTH PALETTE", vault)
        self.assertNotIn("DEPTH PALETTES CONSOLE", vault)
        self.assertIn("const depthDirectionLabel = value =>", vault)
        self.assertIn("depth < 50 ? 'farther' : 'closer'", vault)
        self.assertIn("if (depth === 50) return 'Neutral'", vault)
        self.assertIn('<button class="delete depth-palette-delete" type="button">Delete</button></div><div class="library-actions">', vault)
        self.assertIn('<button class="rename-button depth-palette-save" type="button">Save</button>', vault)
        self.assertIn('class="settings-toggle depth-palette-toggle"', vault)
        self.assertIn("event.target.matches('.depth-palette-toggle')", vault)
        self.assertIn("const depthPaletteResponse = async (response, fallback) =>", vault)
        self.assertIn("depthPaletteResponse(response, 'Could not save Depth Palette')", vault)
        self.assertNotIn("<summary>Swatch depth settings</summary>", vault)

        services = (ROOT / "services.py").read_text(encoding="utf-8")
        self.assertIn("table.put_item(Item=_dynamodb_values(item))", services)


if __name__ == "__main__":
    unittest.main()
