apiVersion: apps/v1
kind: Deployment
metadata:
  name: mopa-laser-rasterizer
  namespace: default
  labels:
    app: mopa-laser-rasterizer
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mopa-laser-rasterizer
  template:
    metadata:
      labels:
        app: mopa-laser-rasterizer
    spec:
      containers:
      - name: mopa-laser-rasterizer
        image: mopa-laser-rasterizer:local
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
#        livenessProbe:
#          httpGet:
#            path: /
#            port: http
#          initialDelaySeconds: 10
#          periodSeconds: 6
#          timeoutSeconds: 60
#          failureThreshold: 3
#        readinessProbe:
#          httpGet:
#            path: /
#            port: http
#          initialDelaySeconds: 5
#          periodSeconds: 6
#          timeoutSeconds: 60
#          failureThreshold: 150
        volumeMounts:
        - name: html
          mountPath: /app/html
          readOnly: true
        - name: cgi-bin
          mountPath: /app/cgi-bin
          readOnly: true
        - name: uploads
          mountPath: /app/uploads
          readOnly: false
      volumes:
      - name: html
        hostPath:
          path: /mnt/c/Users/chree/Desktop/mopa-laser-rasterizer/html
          type: Directory
      - name: cgi-bin
        hostPath:
          path: /mnt/c/Users/chree/Desktop/mopa-laser-rasterizer/cgi-bin
          type: Directory
      - name: uploads
        hostPath:
          path: /mnt/c/Users/chree/Desktop/mopa-laser-rasterizer/uploads
          type: DirectoryOrCreate
