apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

metadata:
  name: mopa-laser-rasterizer

commonLabels:
  app: mopa-laser-rasterizer
  managed-by: kustomize

commonAnnotations:
  description: "Re-rasterize color images into LightBurn MOPA Laser color engraving projects for your laser"

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml

replicas:
- name: mopa-laser-rasterizer
  count: 3

images:
- name: mopa-laser-rasterizer
  newName: mopa-laser-rasterizer
  newTag: "local"
