#!/usr/bin/env python3
"""
Example CGI script demonstrating Python CGI capabilities.
Access this at: http://localhost:8000/cgi-bin/example.py
"""

import cgi
import sys
from datetime import datetime

# Output HTTP headers
print("Content-Type: text/html; charset=utf-8")
print("Cache-Control: no-cache")
print()

# Get query parameters
form = cgi.FieldStorage()
name = form.getvalue('name', 'Guest')
message = form.getvalue('message', '')

# HTML output
html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CGI Example Script</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
        }}
        .container {{
            background: white;
            border-radius: 12px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
            padding: 40px;
            max-width: 600px;
        }}
        h1 {{
            color: #667eea;
            margin-bottom: 20px;
        }}
        .info {{
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
            border-left: 4px solid #667eea;
        }}
        .form {{
            margin: 30px 0;
        }}
        input, button {{
            padding: 10px;
            margin: 10px 5px 10px 0;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-size: 1em;
        }}
        button {{
            background: #667eea;
            color: white;
            border: none;
            cursor: pointer;
            font-weight: bold;
        }}
        button:hover {{
            background: #764ba2;
        }}
        .result {{
            background: #e7f3ff;
            padding: 15px;
            border-radius: 8px;
            margin: 20px 0;
            border-left: 4px solid #2196F3;
        }}
        .timestamp {{
            color: #999;
            font-size: 0.9em;
            margin-top: 20px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🐍 Python CGI Example</h1>
        
        <div class="info">
            <p><strong>This page is generated by a Python CGI script!</strong></p>
            <p>Edit or replace <code>cgi-bin/example.py</code> to customize this script.</p>
        </div>
        
        <div class="form">
            <form method="get">
                <input type="text" name="name" value="{cgi.escape(name)}" placeholder="Enter your name">
                <input type="text" name="message" value="{cgi.escape(message)}" placeholder="Enter a message">
                <button type="submit">Submit</button>
            </form>
        </div>
        
        <div class="result">
            <p><strong>Hello, {cgi.escape(name)}!</strong></p>
            {"<p>Your message: " + cgi.escape(message) + "</p>" if message else ""}
            <p>This response was generated dynamically by Python.</p>
        </div>
        
        <div class="info">
            <h3>📚 How to use CGI scripts:</h3>
            <ul>
                <li>Place Python scripts in the <code>cgi-bin/</code> folder</li>
                <li>Scripts must start with: <code>#!/usr/bin/env python3</code></li>
                <li>Always output HTTP headers first</li>
                <li>Access scripts at: <code>http://localhost:8000/cgi-bin/scriptname.py</code></li>
                <li>Use <code>cgi.FieldStorage()</code> to get form data</li>
            </ul>
        </div>
        
        <div class="timestamp">
            Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        </div>
        
        <p style="margin-top: 30px; text-align: center;">
            <a href="/" style="color: #667eea; text-decoration: none;">← Back to Home</a>
        </p>
    </div>
</body>
</html>
"""

print(html)
